### ISSUE TITLE
Add ${aspnet-request-posted-body} - log posted request body/payload

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#103]
Render posted value

Tricky because we need to reset the inputstream and set it back?

Also limit the chars (e.g. when a file is uploaded)

**Comment by 304NotModified** [comment]
code non-core:

```
var originalStream = new StreamReader(HttpContext.Current.Request.InputStream);
var content = originalStream.ReadToEnd();
```

**Comment by 304NotModified** [comment]
in .NET Core:

request.Body

**Comment by neoKushan** [comment]
Is there an update on this one? I came here via Google to one of the closed issues and the link in this thread is dead. Not sure?

**Comment by 304NotModified** [comment]
Nope, PR accepted ;)

I will try to find a working link...

**Comment by 304NotModified** [comment]
link updated!

**Comment by 304NotModified** [comment]
> Is there an update on this one

-> #339

**Comment by cbjpdev** [comment]
Hi, Is this feature available in NLog.Web.AspNetCore 4.8.0? I can see the code https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestPostedBody.cs, But I am clueless how to use it?

**Comment by 304NotModified** [comment]
Hi! This is fixed for 4.8.1, but not released yet. I will try to release this, this evening. (utc +1 here)

When released, you could use `${aspnet-request-posted-body}`

**Comment by cbjpdev** [comment]
Thank you very much.

**Comment by 304NotModified** [comment]
@cbjpdev 

published (currently indexing):

- https://www.nuget.org/packages/NLog.Web.AspNetCore/4.8.1
- https://www.nuget.org/packages/NLog.Web/4.8.1

usage: https://github.com/NLog/NLog/wiki/AspNet-Request-posted-body-layout-renderer

**Comment by cbjpdev** [comment]
Thanks, I applied, It works very well.

**Comment by 304NotModified** [comment]
Thanks for the confirmation 👍

**Comment by HinaSheikh** [comment]
Hey 
How can i reset input of  ${aspnet-request-posted-body} in code ?

**Comment by snakefoot** [comment]
@HinaSheikh Please create new issue, instead of waking up old issues. But I think the solution is that you create an advanced NLog LayoutRenderer that can parse a document (xml / json) and can specify transformations of property-values. Ex from `password: "xyz"` to `password: "***"`. Again create new issue or pull-request instead of continuing here.

**Comment by snakefoot** [comment]
#754 has reverted this in NLog.Web ver. 5.0

**Comment by snakefoot** [comment]
Thanks to @bakgerman now NLog.Web.AspNetCore v5.1 re-introduces [${aspnet-request-posted-body}](https://github.com/NLog/NLog/wiki/AspNet-Request-posted-body-layout-renderer) with help from middleware:
```c#
app.UseMiddleware<NLog.Web.NLogRequestPostedBodyMiddleware>();
```
It is no longer necessary to call `context.Request.EnableBuffering();` as it is handled by the middleware.
