### ISSUE TITLE
Add Raw query string option

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#104]
faster, and sometimes better:

https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.http.httprequest#Microsoft_AspNetCore_Http_HttpRequest_QueryString

**Comment by Giorgi** [comment]
@304NotModified The link is dead.

**Comment by 304NotModified** [comment]
I think this is an outdated idea. Thanks for the feedback
