### ISSUE TITLE
The logs's file on Centos 7 is error

### ISSUE THREAD

**Issue by DavidYamer** [NLog/NLog.Web#115]
![ts4g k s2sv oouu u53q2](https://cloud.githubusercontent.com/assets/20207629/23148087/8dffc012-f81e-11e6-8193-b7a2cc9e8849.png)
 "NLog.Web.AspNetCore": "4.3.1"
`<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogToConsole="false"
      internalLogToConsoleError="false"
      internalLogFile="Logs/internal-nlog.txt">
  
  <targets>
    
    <target xsi:type="File"
            name="allfile"
            fileName="Logs\nlog-all-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|${message} ${exception}" />
    <target xsi:type="File" 
            name="ownFile-web" 
            fileName="Logs\nlog-own-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|${message} ${exception}" />
    <target xsi:type="File"
            name="blackhole" 
            fileName="Logs\nlog-ms-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|${message} ${exception}" />
  </targets>
  <rules>
    
    
    <logger name="*" 
            minlevel="Error" 
            writeTo="allfile" />
    
    
    <logger name="Microsoft.*" 
            minlevel="Trace" 
            writeTo="blackhole" 
            final="true" />
    
    <logger name="*" 
            minlevel="Info" 
            writeTo="ownFile-web" />
  </rules>
</nlog>`
The OS is CentOS Linux release 7.3.1611 (Core)
Is it a bug or my config error?

**Comment by 304NotModified** [comment]
I think a config error. Please post the full config.

**Comment by DavidYamer** [comment]
@304NotModified thank you very much,i checked my config and find the filepath is error,now it is Ok!

**Comment by 304NotModified** [comment]
:+1:
