### ISSUE TITLE
Does not render exception and aspnet related templates

### ISSUE THREAD

**Issue by shawnmclean** [NLog/NLog.Web#116]
I have 2 projects, all my configuration is done in a class project using c# to configure the LogManager.

**Config Project (non aspnet web)**

_.csproj_

```xml
    <PackageReference Include="NLog.Web.AspNetCore">
      <Version>4.3.1</Version>
    </PackageReference>
```

_Config.cs_

```c#
// My DI registration
container.RegisterSingleton(() =>
{
  _loggerFactory.AddNLog();
  _applicationBuilder.AddNLogWeb();

  configure();

  return _loggerFactory;
});

container.Register(typeof(ILogger<>), typeof(Logger<>));


var config = new LoggingConfiguration();

var fileTarget = new FileTarget
{
  FileName = "C:/temp/${shortdate}.log",
  Layout = "${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|  ${message} ${exception}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}"
};
config.AddTarget("file", fileTarget);
config.LoggingRules.Add(new LoggingRule("*", NLog.LogLevel.Trace, fileTarget));

LogManager.Configuration = config;
```

In one of my controllers I have:

`_logger.LogInformation("Index page says hello", new object[0]);`

My log looks like:

`2017-02-24 01:06:26.1308|0|WebApi.Ping.PingController|INFO|  Index page says hello |url: |action: `

My exceptions look like:

`_logger.LogError("exception occured", ex);`

`2017-02-24 01:06:20.9673|0|WebApi.Middlewares.ExceptionLoggingMiddleware|ERROR|  exception occured |url: |action: `

Aspnet version: 1.1.0
SDK version: 1.0.0-preview4-004233

**Comment by shawnmclean** [comment]
I forgot to programmatically add the Assembly.

```
var assembly = Assembly.Load(new AssemblyName("NLog.Web.AspNetCore"));
NLog.Config.ConfigurationItemFactory.Default.RegisterItemsFromAssembly(assembly);
```

**Comment by 304NotModified** [comment]
Their are currently 3 methods inside Microsoft.Extensions.Logging


```c#
public static void LogInformation(this ILogger logger, string message, params object[] args);
public static void LogInformation(this ILogger logger, EventId eventId, string message, params object[] args);
public static void LogInformation(this ILogger logger, EventId eventId, Exception exception, string message, params object[] args);
```

See [code in Microsoft.Extensions.Logging](https://github.com/aspnet/Logging/blob/9506ccc3f3491488fe88010ef8b9eb64594abf95/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs#L134)

You need to call the 3rd one, e.g.

```c#
_logger.LogInformation(eventId, exception, "Index page says hello");
```

This is a limitation of the Microsoft.Extensions.Logging

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
