### ISSUE TITLE
Target to database using MySql Provider

### ISSUE THREAD

**Issue by ali-raza-iftikhar** [NLog/NLog.Web#117]
Can you tell me how .net core nlog work with MySql Provider?

**Comment by 304NotModified** [comment]
See here: https://github.com/damienbod/AspNetCoreNlog

and set the correct `dbProvider`, see https://github.com/NLog/NLog/wiki/Database-target

(dunno of `MySql.Data.MySqlClient ` is .NET core compatible)

**Comment by ali-raza-iftikhar** [comment]
Errors in D:\Projects\LoggingWebTesting\LoggingWebTesting.xproj
    Package MySql.Data 6.9.9 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package MySql.Data 6.9.9 supports:
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)

This is what i am getting on installing this package.

**Comment by 304NotModified** [comment]
Maybe this is helpful http://insidemysql.com/mysql-connector-net-for-net-core-1-0/

**Comment by ali-raza-iftikhar** [comment]
I have installed above package and another package from this source [MySqlConnectore](https://www.nuget.org/packages/MySqlConnector/)  
with this setting and specifying provider. "MySql.Data.MySqlClient"
<target name="database" xsi:type="Database"
             dbProvider="MySql.Data.MySqlClient"
             connectionString="server=localhost;Database=*****;user id=***;password=*******"
             >

but getting this error in internal log.


Error Error initializing target 'Database Target[database]'. Exception: System.TypeLoadException: Could not load type 'MySql.Data.MySqlClient' from assembly 'NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.

**Comment by ali-raza-iftikhar** [comment]
Problem sorted.

Installed this package [MySql.Data](https://www.nuget.org/packages/MySql.Data/7.0.6-IR31)

with following settings
<target name="database" xsi:type="Database"
             dbProvider="MySql.Data.MySqlClient.MySqlConnection, MySql.Data"
             connectionString="server=localhost;Database=loggingemptydb;user id=root;password=Liverpool1"
             >

**Comment by ali-raza-iftikhar** [comment]
Problem sorted.

Installed this package [MySql.Data](https://www.nuget.org/packages/MySql.Data/7.0.6-IR31)

with following settings
`<target name="database" xsi:type="Database"
             dbProvider="MySql.Data.MySqlClient.MySqlConnection, MySql.Data"
             connectionString="server=localhost;Database=*****;user id=****;password=*****"
             >`

**Comment by 304NotModified** [comment]
Thanks! Added it to https://github.com/NLog/NLog/wiki/Database-target
