### ISSUE TITLE
Documentation for UserAuthType and UserIdentity incorrect

### ISSUE THREAD

**Issue by AdamHess** [NLog/NLog.Web#118]
Accourding to: https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore/LayoutRenderers/AspNetUserIdentityLayoutRenderer.cs#L13

it should be apsnet-User-Identity

the same thing applies for UserAuthType should be User-AuthType 

both the documentation on the landing page wiki of this repo and NLog are incorrect.

**Comment by 304NotModified** [comment]
Its wrong on the wiki? Please feel free to edit.

**Comment by 304NotModified** [comment]
Fixed, thanks for reporting!
