### ISSUE TITLE
problems in AspNetRequestCookieLayoutRenderer

### ISSUE THREAD

**Issue by ymind** [NLog/NLog.Web#119]
### tests:
there still has some error, in my nlog.config, the rule is:
`${aspnet-request-cookie:CookieNames=XSRF-TOKEN;OutputFormat:JSON}`

the output log is:
`{"XSRF-TOKEN;OutputFormat="}`

then I chanage the rule to:
`${aspnet-request-cookie:CookieNames=XSRF-TOKEN,jnp.auth,.AspNetCore.ServerCookie,LAST_ONE;OutputFormat:JSON}`

it's output like:
`{"XSRF-TOKEN=HySuQS4Nv-31w76KQ"},{"jnp.auth=mR5Jsduhrqz_6Wc2zoPtQ"},{".AspNetCore.ServerCookie;OutputFormat="}`

third test rule is:
`${aspnet-request-cookie:CookieNames=XSRF-TOKEN,jnp.auth,.AspNetCore.ServerCookie,LAST_ONE;OutputFormat:JSON}`

output like:
`{"XSRF-TOKEN=HySuQS4Nv-31w76KQ"},{"jnp.auth=mR5Jsduhrqz_6Wc2zoPtQ"},{".AspNetCore.ServerCookie=GH2R-o1Npkj"},{"LAST_ONE;OutputFormat="}`

### the problems are:
1. json format is wrong, should be: `{"key": "value"}`
2. the last cookie name can not get the true value;
3. the string "OutputFormat=" should not in the output;

### some suggestion:
the [AspNetRequestQueryStringLayoutRenderer](https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestQueryStringLayoutRenderer.cs) is working fine _(but the last field is lost too)_, please refer to it.

**Comment by 304NotModified** [comment]
that are some serious bug. We need some more unit tests for these parts. 

Could use some help on that ;)

**Comment by 304NotModified** [comment]
> there still has some error, in my nlog.config, the rule is:
> ${aspnet-request-cookie:CookieNames=XSRF-TOKEN;OutputFormat:JSON}

I think this should be `${aspnet-request-cookie:CookieNames=XSRF-TOKEN:OutputFormat=JSON}` ? (colon, equals sign)

**Comment by 304NotModified** [comment]
working on this. The outputted JSON is indeed garbage :(
