### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mmaitre314** [NLog/NLog.Web#12]
Readme.md mentions BSD as license and the LICENSE file is GPL. Which one is the correct one?

**Comment by 304NotModified** [comment]
Bsd :)

**Comment by mmaitre314** [comment]
Is it ok if I send a pull request to correct that? I also noticed that docs mentioned that NLogHttpModule lived in the NLog.Extended while it looks like it is (now) in NLog.Web. I could send a patch for that too.

**Comment by 304NotModified** [comment]
That would be great!

**Comment by mmaitre314** [comment]
Sent PR for 0c5cb9e0f2feb0fa74c1f4941ef2691d0a7ab391 to update the license. Will send another PR for doc fix.
