### ISSUE TITLE
Schema doesn't recognise keepVariablesOnReload 

### ISSUE THREAD

**Issue by grokky1** [NLog/NLog.Web#120]
I've manually included (because I'm on .NET Core) the `NLog.xsd` file, so I get IntelliSense. I want to use the [`keepVariablesOnReload` attribute](https://github.com/NLog/NLog/wiki/Configuration-file#vars-since-nlog-41).

But the schema doesn't accept it: `The 'keepVariablesOnReload' attribute is not declared.`

**Comment by 304NotModified** [comment]
we're did you downloaded the XML schema?

**Comment by grokky1** [comment]
[From here](https://www.nuget.org/packages/NLog.Schema)

**Comment by 304NotModified** [comment]
OK thx!

It's partly generated, but not this part as is seems.  :)

**Comment by 304NotModified** [comment]
It will be fixed in NLog 4.4.4. Thanks for reporting!
