### ISSUE TITLE
Update documentation for visual studio 2017

### ISSUE THREAD

**Issue by HarelM** [NLog/NLog.Web#127]
Project.json is no longer supported. please update the getting started documentation.

**Comment by 304NotModified** [comment]
Do you have a link of the not supported announcement? Lot of users are still on project.json

**Comment by HarelM** [comment]
https://blogs.msdn.microsoft.com/dotnet/2016/10/19/net-core-tooling-in-visual-studio-15/

**Comment by 304NotModified** [comment]
PS: there are some nice examples here: (both project.json and csproj2017)

https://github.com/damienbod/AspNetCoreNlog

**Comment by 304NotModified** [comment]
If someone like to help with this, please do. I think the VS2017 docs should be next to the VS2015 docs

**Comment by HartleyOriginalJam** [comment]
Bit of a description about the project.json no longer being used in VS 2017 here:

https://csharp.christiannagel.com/2017/01/10/dotnetcoreversionissues/

I'm going through the process now, will update when complete

**Comment by HartleyOriginalJam** [comment]
Only thing I found missing that I needed was this:

`services.AddSingleton<ILoggerFactory, LoggerFactory>();`

**Comment by 304NotModified** [comment]
done

https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(csproj---vs2017)

**Comment by HarelM** [comment]
The documentation in the link start with:
>In Visual Studio 2015 Update 3.

Dependencies are not added in `project.json` anymore as far as I could tell, they are added in `csproj` file or through NuGet.
So the heading 
>Add dependency in project.json

 is miss-leading.

**Comment by 304NotModified** [comment]
Indeed. Feel free to edit (its a wiki). Thanks!

**Comment by HarelM** [comment]
Done! thought that this was intentional. Keep up the good work!

**Comment by 304NotModified** [comment]
no just copy-paste bug. Thanks!!
