### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#151]
>  NLog.Web.Tests -> C:\projects\nlogweb\NLog.Web.Tests\bin\Release\NLog.Web.Tests.dll
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\projects\nlogweb\NLog.Web.AspNetCore\NLog.Web.AspNetCore.csproj]
CSC : error CS1705: Assembly 'Microsoft.AspNetCore.Http.Abstractions' with identity 'Microsoft.AspNetCore.Http.Abstractions, Version=1.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Microsoft.AspNetCore.Http.Features, Version=1.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.AspNetCore.Http.Features' with identity 'Microsoft.AspNetCore.Http.Features, Version=1.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' [C:\projects\nlogweb\NLog.Web.AspNetCore\NLog.Web.AspNetCore.csproj]

after https://github.com/NLog/NLog.Web/pull/150

**Comment by 304NotModified** [comment]
@johnkors any idea?

**Comment by johnkors** [comment]
Ah, yes.

We need to bump 

`
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="1.0.2" />
`
to
`    
<PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="1.0.3" />
`

in `NLog.Web.AspNetCore.csproj` as well, it seems! Sorry.

**Comment by johnkors** [comment]
Do you need the direct reference to `Microsoft.AspNetCore.Http.Features/1.0.2` in `Microsoft.Web.AspNetCore.csproj` at all though? 

It builds and runs fine without it.

**Comment by 304NotModified** [comment]
https://github.com/RetireNet/dotnet-retire/blob/master/build.cmd#L10
