### ISSUE TITLE
NLog.Web.AspNetCore - LogError doesn't log anything when passing empty message and exception

### ISSUE THREAD

**Issue by tpodolak** [NLog/NLog.Web#159]
When I log error without error message (but with exception) nothing is logged. I have to provide any error message in order to make that work (whitespace string works as well). This is a result of NLog.Extensions.Logging bug NLog/NLog.Extensions.Logging#120.

**Comment by 304NotModified** [comment]
Yes I saw your other bug report. Try to review this week. Thanks for reporting!

**Comment by 304NotModified** [comment]
This has been released in NLog.Extensions.Logging 1.0.0-rtm-beta6, thus closing this.

Thanks for the contribution!
