### ISSUE TITLE
Core 2.0 version

### ISSUE THREAD

**Issue by xperiandri** [NLog/NLog.Web#165]
Is Core 2.0 version planned?

**Comment by 304NotModified** [comment]
Not yet. Is there something not working?

**Comment by xperiandri** [comment]
Well it is better to name `AddNLogWeb` as `UseNLogWeb` to correspond to other stuff.
Basically other things look like working

**Comment by grokky1** [comment]
Just upgraded to netcoreapp2.0 and also ran into this... lots of changes. Can still use the old pattern for config, and it works for me.

But now logging is spread over Program and Startup which is messy and confusing. Looking forward to NLog using the "new style".

**Comment by xperiandri** [comment]
It is not spread.
Standard loggers configure with `ILoggingBuilder` and `IHostingContext`.

You do [this](https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore/AspNetExtensions.cs#L26)
``` C#
public static void AddNLogWeb(this IApplicationBuilder app)
{
    ServiceLocator.ServiceProvider = app.ApplicationServices;
}
```

**Comment by 304NotModified** [comment]
closing this in favor of more specific issues 

(under the label asp.net core 2)
