### ISSUE TITLE
Feature Request: Config File in json format

### ISSUE THREAD

**Issue by geeForceOne** [NLog/NLog.Web#166]
It would be lovely to have the config options in a json file instead of xml, so that matches the appsettings.json (and configuration could just be sticked in there)

**Comment by 304NotModified** [comment]
Indeed, see:

https://github.com/NLog/NLog/issues/1588

**Comment by 304NotModified** [comment]
Closing in favor of https://github.com/NLog/NLog/issues/1588

**Comment by snakefoot** [comment]
Created https://github.com/NLog/NLog.Extensions.Logging/pull/263 for people who would like to test NLog-config from `appsettings.json`. Depends on NLog 4.6-rc1

**Comment by 304NotModified** [comment]
Cool!

**Comment by snakefoot** [comment]
NLog.Extensions.Logging ver. 1.5.0 have been released with support for NLog-config in appsettings.json

https://www.nuget.org/packages/NLog.Extensions.Logging
