### ISSUE TITLE
Missing Trace/Debug logs

### ISSUE THREAD

**Issue by irashid25** [NLog/NLog.Web#167]
Hi,

I'm following the following wiki to get Nlog up and running with an asp.net core 2.0 application. I have it working except that it is missing the trace and debug logs.

Ref; https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(csproj---vs2017)

I have referenced the following via nuget:
- PackageReference Include="NLog" Version="5.0.0-beta09"
- PackageReference Include="NLog.Web.AspNetCore" Version="4.4.1"

The code in my MVC controller is as follows:

```
public string Index()
        {
            this._logger.LogTrace("Tracing....");
            this._logger.LogDebug("Debugging....");
            this._logger.LogInformation("Information....");
            this._logger.LogWarning("Warning....");
            this._logger.LogError("Error....");
            this._logger.LogCritical("Critical");
            return string.Empty;
        }

```
I modified the nlog.config from the wiki, so that the minlevel for the internal log is also Trace.
After running the application i get the following output:

2017-08-21 16:06:08.1894|1|Microsoft.AspNetCore.Hosting.Internal.WebHost|INFO|Request starting HTTP/1.1 GET http://localhost:59663/   
2017-08-21 16:06:08.4325|1|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|INFO|Executing action method TestApp.Controllers.HomeController.Index (TestApp) with arguments ((null)) - ModelState is Valid 
2017-08-21 16:06:08.4405|0|TestApp.Controllers.HomeController|INFO|Information.... 
2017-08-21 16:06:08.4405|0|TestApp.Controllers.HomeController|WARN|Warning.... 
2017-08-21 16:06:08.4567|0|TestApp.Controllers.HomeController|ERROR|Error.... 
2017-08-21 16:06:08.4567|0|TestApp.Controllers.HomeController|FATAL|Critical 
...

As you can see, its not writing out the Trace and the Debug message. The other logs outputted show the same thing.
Any help would be appreciated. 

Thanks.

**Comment by 304NotModified** [comment]
Are you sure you're editing the correct NLog.config file? (For example in non .net core it could be also in the bin folder). 

If so, please post the full config.

**Comment by irashid25** [comment]
Hi

Below is a copy of my nlog.config file in the bin/Debug/netcoreapp2.0 folder.

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Trace"
      internalLogFile="c:\temp\internal-nlog.txt">

  
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  
  <targets>
    
    <target xsi:type="File" name="allfile" fileName="c:\temp\nlog-all-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|${message} ${exception}" />

    
    <target xsi:type="File" name="ownFile-web" fileName="c:\temp\nlog-own-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|  ${message} ${exception}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}" />

    
    <target xsi:type="Null" name="blackhole" />
  </targets>

  
  <rules>
    
    <logger name="*" minlevel="Trace" writeTo="allfile" />

    
    <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />
    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />
  </rules>
</nlog>

Thanks.

**Comment by 304NotModified** [comment]
Please change the `layout` attribute and check if this will be applied. 

I think you need to change the config in the root of your project

**Comment by irashid25** [comment]
I changed my config to just output the message in the layout;
```

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Trace"
      internalLogFile="c:\temp\internal-nlog.txt">

  <!-- Load the ASP.NET Core plugin -->
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <!-- the targets to write to -->
  <targets>
    <!-- write logs to file -->
    <target xsi:type="File" name="allfile" fileName="c:\temp\nlog-all-${shortdate}.log"
            layout="${message}" />

    <!-- another file log, only own logs. Uses some ASP.NET core renderers -->
    <target xsi:type="File" name="ownFile-web" fileName="c:\temp\nlog-own-${shortdate}.log"
            layout="${message}" />

    <!-- write to the void aka just remove -->
    <target xsi:type="Null" name="blackhole" />
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Trace" writeTo="allfile" />

    <!--Skip Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />
    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />
  </rules>
</nlog>
```

I still have the same issue, the logs now show the following:

Request starting HTTP/1.1 GET http://localhost:59663/  
Executing action method Oceano.Controllers.HomeController.Index (Oceano) with arguments ((null)) - ModelState is Valid
Information....
Warning....
Error....
Critical
Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
Executed action Oceano.Controllers.HomeController.Index (Oceano) in 71.9743ms
Request finished in 344.414ms 200 text/plain; charset=utf-8
Request starting HTTP/1.1 GET http://localhost:59663/favicon.ico  
Request finished in 5.9918ms 404 

Thanks.

**Comment by snakefoot** [comment]
Maybe you have to checkout:

`ILoggingBuilder.SetMinimumLevel()`

Think NetCore has Info as default minimum-level. Maybe combined with #169

**Comment by irashid25** [comment]
Thanks @snakefoot 

I changed my program.cs to 

```
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureLogging((host, builder) =>
                {
                    host.HostingEnvironment.ConfigureNLog("nlog.config");
                    builder.SetMinimumLevel(LogLevel.Trace);
                })
                .UseStartup<Startup>()
                .Build();
```
From my testing, even though the configure.Nlog code precedes setting the minimum log level, changing the nlog.config to log at levels higher than Trace works as expected.
My startup.cs file remained unchanged:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }


            //add NLog to ASP.NET Core
            loggerFactory.AddNLog();

            //add NLog.Web
            app.AddNLogWeb();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
```

Thanks for your help guys. Appreciate your hard work in helping out quickly, especially when there are a lot of changes happening with .netcore.

Happy for you to close this issue now.

**Comment by rdev5** [comment]
FYI, we're still seeing this behavior in the latest stable version **4.5.11** where merely specifying `minlevel` is not actually writing Debug messages to our log file.

Is it still necessary to configure logging in code *in addition to* setting `minlevel` in order for this setting to work?

**Comment by snakefoot** [comment]
@rdev5 Is your problem fixed by calling `SetMinimumLevel(...)` ? (See below)

https://github.com/NLog/NLog.Web/blob/6335740c3382797e7820675881bc26f5ca5ed4ad/examples/ASP.NET%20Core%202/Visual%20Studio%202017/ASP.NET%20Core%202%20-%20VS2017/Program.cs#L33-L40

**Comment by rdev5** [comment]
@snakefoot Sorry, I apparently can't see very well today. The code I was looking at where Debug was in use wasn't actually being _reached_ so I assumed it wasn't being logged. I went back to look at our logs and do see other parts of code that logged Debug just fine.

**Comment by snakefoot** [comment]
See also: https://github.com/NLog/NLog.Web/wiki/Missing-trace%5Cdebug-logs-in-ASP.NET-Core-2%3F
