### ISSUE TITLE
extend ILoggingBuilder for .net core 2.0

### ISSUE THREAD

**Issue by dozm** [NLog/NLog.Web#169]
Now，logging configuration have moved to IWebHostBuilder and  ILoggingBuilder.
we want to use NLog to output the log during host start.
we need make small changes:

    // in NLog ConfigureExtensions
    public  static ILoggingBuilder AddNLog(this ILoggingBuilder builder, NLogProviderOptions options)
    {
         //ignore this
         LogManager.AddHiddenAssembly(Assembly.Load(new AssemblyName("Microsoft.Extensions.Logging")));
         LogManager.AddHiddenAssembly(Assembly.Load(new AssemblyName("Microsoft.Extensions.Logging.Abstractions")));

          try
          {
               //try the Filter ext
               var filterAssembly = Assembly.Load(new AssemblyName("Microsoft.Extensions.Logging.Filter"));
               LogManager.AddHiddenAssembly(filterAssembly);
          }
          catch (Exception)
          {
                //ignore
          }

          LogManager.AddHiddenAssembly(typeof(ConfigureExtensions).GetTypeInfo().Assembly);

          builder.Services.AddSingleton<ILoggerProvider>(new NLogLoggerProvider(options));
          
          return builder;
     }

Use case:

     // in Program.cs
     webHostBuilder.ConfigureLogging((hostingContext, logging) =>
     {
         hostingContext.HostingEnvironment.ConfigureNLog("nlog.config");
         logging.AddNLog(default(NLogProviderOptions));
     });

**Comment by 304NotModified** [comment]
Could you send a PR? That's easier to discuss. 

Currently I have only internet on my mobile, so I'm limited with checking/building code.

**Comment by dozm** [comment]
I'm embarrassed，I can't use git very well.
