### ISSUE TITLE
${aspnet-request} how get the whole body as a string

### ISSUE THREAD

**Issue by Varorbc** [NLog/NLog.Web#174]
I need to get the full request information as a string, not one by parameter
Please tell me how to do it，thank you
https://github.com/NLog/NLog/wiki/AspNetRequest-layout-renderer

**Comment by 304NotModified** [comment]
This is not implement yet.

**Comment by 304NotModified** [comment]
I think this is https://github.com/NLog/NLog.Web/issues/103

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
