### ISSUE TITLE
ASP.NET Core 2 - simplify usage

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#177]
from https://github.com/NLog/NLog.Web/pull/173#issuecomment-326275019 (thanks @grokky1 !)

(renamed the method also - Julian)

> 
Using
````csharp
public static void UseNLog(this ILoggingBuilder builder)
{
  builder.AddNLog();                                      // NEW
  ServiceLocator.ServiceProvider = builder.Services;
}
````

Old:
````csharp
context.HostingEnvironment.ConfigureNLog("nlog.config");
builder.AddNLog();
builder.AddNLogWeb();
````

We can rather have this simpler config
````csharp
context.HostingEnvironment.ConfigureNLog("nlog.config");
builder.UseNLog();
````

----

great improvement!

**Comment by 304NotModified** [comment]
mmmm

>	Cannot implicitly convert type 'Microsoft.Extensions.DependencyInjection.IServiceCollection' to 'System.IServiceProvider'. An explicit conversion exists (are you missing a cast?)	NLog.Web.AspNetCore(netstandard2.0)	60	

@grokky1 any idea?

**Comment by grokky1** [comment]
@304NotModified I don't recall having that problem.

Did you find a fix?

**Comment by 304NotModified** [comment]
I moved to webhostbuilder: https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs#L41 (fyi indentation is wrong)
