### ISSUE TITLE
Log all the form variables

### ISSUE THREAD

**Issue by gelambert** [NLog/NLog.Web#194]
Hi,

Is it possible to log all the form variables without specifying each variable in the layout ?
For example, by using something like `${aspnet-request:form=*}` ?
I did not find the way to do it on [this page of the wiki](https://github.com/NLog/NLog/wiki/AspNetRequest-layout-renderer).
Thanks for your help.

**Comment by 304NotModified** [comment]
Currently this isn't possible. I think it's not that difficult to implement. Could you help us with that when I point you to the right direction?

**Comment by gelambert** [comment]
For sure, I need this feature so I can help !

**Comment by 304NotModified** [comment]
You need to create a new file in 

- NLog.Web.AspNetCore/LayoutRenderers
and link it in NLog.Web
![image](https://user-images.githubusercontent.com/5808377/31517284-b4bf89a0-af9b-11e7-90aa-3ba24bcf7bc5.png)

![image](https://user-images.githubusercontent.com/5808377/31517290-b7e78e20-af9b-11e7-82b6-b60384d4068a.png)



I think the code looks a bit like this one:

https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestCookieLayoutRenderer.cs

please try to add also some unit tests

**Comment by gelambert** [comment]
Thank you for your answer.
I should have specified that, but I am using ASP.NET MVC 5.2.3.
If I write some code in NLog.Web.AspNetCore/LayoutRenderers, will I be able to use it in an ASP.NET MVC project ?

**Comment by 304NotModified** [comment]
well we like to implement it for both. I think the differences will be small.  You can use `#if ASP_NET_CORE` for that. (see example)

When implementing for both, please include it in the NLog.Web.AspNetCore folder (as described)

If it's not feasible for ASP.NET Core, let me know, then we can look how to include this.

**Comment by DrewBrasher** [comment]
I have implemented this on a fork of NLog.Web.  I still need to write unit tests for it but the renderer is here:
https://github.com/DrewBrasher/NLog.Web/blob/add-aspnet-request-form-layout-renderer/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestFormLayoutRenderer.cs

**Comment by 304NotModified** [comment]
If the unit test is there, we really like to include it :)

**Comment by DrewBrasher** [comment]
@304NotModified  I have added the unit tests and created a pull request.

**Comment by 304NotModified** [comment]
Thanks! Reviewed!

**Comment by 304NotModified** [comment]
fixed by #313 :)
