### ISSUE TITLE
Add .NET standard 2 docs

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#196]

**Comment by 304NotModified** [comment]
Done

https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2

**Comment by ssczo** [comment]
Sample in doc is not running. In which package is NLogBuilder ?

**Comment by 304NotModified** [comment]
in this package (NLog.Web.AspNetCore): https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore/NLogBuilder.cs
