### ISSUE TITLE
Consider creating an AspNetLayoutRendererBase class

### ISSUE THREAD

**Issue by epignosisx** [NLog/NLog.Web#20]
I just went through the exercise of creating a few custom Layout Renderers for AspNet and I experienced some pain points that I wanted to share and provide a solution.

Problem
================

1- Looking at the LayoutRenderers that are part of the NLog.Web package there is a bit of duplication in all of them in the form:

```c#
    HttpContext context = HttpContext.Current;
    if (context == null)
    {
        return;
    }

    var httpRequest = context.Request;
    if (httpRequest == null)
    {
        return;
    }
```

2- The raw usage of the static **HttpContext.Current** in the layout renderers makes it hard to unit test. I looked at how the NLog.Web layout renderers were unit tested and most do not have unit tests. Maybe this is part of the reason.

Proposal
=================

Introduce the following two concepts: **IHttpContextProvider** and **AspNetLayoutRendererBase**:

```c#
    public interface IHttpContextProvider
    {
        HttpContextBase Get(); //returns HttpContextBase which is unit testable.
    }

    public class DefaultHttpContextProvider : IHttpContextProvider
    {
        public HttpContextBase Get()
        {
            if (HttpContext.Current == null)
                return null;
            return new HttpContextWrapper(HttpContext.Current);
        }
    }

    public abstract class AspNetLayoutRendererBase : LayoutRenderer
    {
        private readonly IHttpContextProvider _httpContextProvider;

        //this is the constructor that would run during "normal" mode
        protected AspNetLayoutRendererBase() : this(new DefaultHttpContextProvider())
        {
        }

        //this constructor can be used during unit tests to pass an implementation will return a
        //a mocked HttpContextBase
        protected AspNetLayoutRendererBase(IHttpContextProvider httpContextProvider)
        {
            _httpContextProvider = httpContextProvider;
        }

        //Expose a property that subclasses can use instead of the static HttpContext.Current
        public HttpContextBase HttpContext
        {
            get { return _httpContextProvider.Get(); }
        }

        protected override void Append(StringBuilder builder, LogEventInfo logEvent)
        {
            //do this check in the base class instead of in each Layout Renderer
            if (HttpContext == null)
                return;

            //subclasses implement this method with the assurance that they will have a valid HttpContext.
            AppendCore(builder, logEvent);
        }

        protected abstract void AppendCore(StringBuilder builder, LogEventInfo logEvent);
    }
```

Here is a sample Layout Renderer:

```c#
    [LayoutRenderer("aspnet-client-real-ip")]
    public class AspNetRealIpLayoutRenderer : AspNetLayoutRendererBase
    {
        public AspNetRealIpLayoutRenderer()
        {
        }

        public AspNetRealIpLayoutRenderer(IHttpContextProvider httpContextProvider) : base(httpContextProvider)
        {
        }

        protected override void AppendCore(StringBuilder builder, LogEventInfo logEvent)
        {
            var httpRequest = HttpContext.Request;

            string ip = httpRequest.Headers["True-Client-IP"] ?? httpRequest.Headers["X-Forwarded-For"];
            if (string.IsNullOrEmpty(ip))
            {
                return;
            }

            if (!IpValidator.IsValid(ip))
            {
                return;
            }

            builder.Append(ip);
        }
    }
```

Here is how the unit tests would look like:

```c#
    [Fact]
    public void NullHttpContextRendersEmptyString()
    {
        var renderer = new AspNetRealIpLayoutRenderer();

        string value = renderer.Render(new LogEventInfo(LogLevel.Debug, "LoggerName", "Msg"));
        
        Assert.Empty(value);
    }

    [Fact]
    public void RendersRealClientIp()
    {
        var ip = "1.0.0.1";
        var httpContext = Substitute.For<HttpContextBase>();
        var httpRequest = Substitute.For<HttpRequestBase>();
        var headers = new NameValueCollection { { "True-Client-IP", ip } };
        httpRequest.Headers.Returns(headers);
        httpContext.Request.Returns(httpRequest);
        var httpContextProvider = Substitute.For<IHttpContextProvider>();
        httpContextProvider.Get().Returns(httpContext);

        var renderer = new AspNetRealIpLayoutRenderer(httpContextProvider);
        
        string value = renderer.Render(new LogEventInfo(LogLevel.Debug, "LoggerName", "Msg"));

        Assert.Equal(ip, value);
    }
```

**Comment by 304NotModified** [comment]
> 1- Looking at the LayoutRenderers that are part of the NLog.Web package there is a bit of duplication in all of them in the form:
> 2- The raw usage of the static HttpContext.Current in the layout renderers makes it hard to unit test. I looked at how the NLog.Web layout renderers were unit tested and most do not have unit tests. Maybe this is part of the reason.

Agree with these. A refactor is good idea! 

About your proposal: looks nice, but I was more thinking about dependency injection by an internal property. like:
```c#
 public abstract class AspNetLayoutRendererBase : LayoutRenderer
    {
internal IHttpContextProvider ContextProvider {get;set;}

```
Internal properties can be set from an unit test (but only ours). What do you think?

And I think `AppendCore` should be `DoAppend()`, as it's a design pattern?

**Comment by epignosisx** [comment]
I agree with most of your suggestions. However, making the IHttpContextProvider internal makes unit testing very hard for layout renderer authors. They would have to roll out their own version of what we are trying to do here. We should provide a way to easily mock the HttpContext since any web layout renderer will need to get some data from it.

What is your reservation with making it public?

**Comment by 304NotModified** [comment]
> What is your reservation with making it public?

Maintenance, backwardscompaitblity. Private and internal stuff is great as we can change everything without worrying. 



> However, making the IHttpContextProvider internal makes unit testing very hard for layout renderer authors.

You're right! So I fully agree with your proposal! :)

PS: I changed your post as I'm lazy and so I like syntax highlighting ;)

**Comment by epignosisx** [comment]
Thanks, looks much better now with syntax highlighting. I have to read on how to do it.

I'll start working on the PR.
