### ISSUE TITLE
Using ${callsite} returns invalid classname

### ISSUE THREAD

**Issue by agentschmitt** [NLog/NLog.Web#200]
In 4.5.0-beta01 the ${callsite} layout renderer does not log the Classname from where i am logging.
But instead it returns "NLog.Extensions.Logging.NLogLogger.Log".

I found an issue where this was fixed already, but the bug seems to be back.https://github.com/NLog/NLog/issues/1512

Seems AspNetExtensions where the Bug was fixed is not longer in Nlog.Extensions but in Nog.Web project. Maybe the Fix can be added there too? Or it is required somewhere else in Nlog.Extensions?

Workaround:
```
            LogManager.AddHiddenAssembly(Assembly.Load(new AssemblyName("Microsoft.Extensions.Logging")));
            LogManager.AddHiddenAssembly(Assembly.Load(new AssemblyName("Microsoft.Extensions.Logging.Abstractions")));
            LogManager.AddHiddenAssembly(Assembly.Load(new AssemblyName("NLog.Extensions.Logging")));
```

**Comment by 304NotModified** [comment]
fixed in beta2

**Comment by FlorianHockmann** [comment]
> fixed in beta2

I just ran into this problem with _rtm-rc2_ 😕
The workaround posted by @agentschmitt also fixed this for me, so this really seems to be the same issue.

**Comment by 304NotModified** [comment]
It should be Fixed in NLog.web 4.5 beta 2

The rtm-rc is NLog.extensions.logging?

**Comment by FlorianHockmann** [comment]
Sorry, I didn't realize that this is a completely different repository. I got here by googling the problem.
NLog.Extensions.Logging also seems to already have an open issue for this: NLog/NLog.Extensions.Logging#165
