### ISSUE TITLE
Latest Stable NLog.Web.AspNetCore Depends On NLog 5.0 Beta

### ISSUE THREAD

**Issue by bburman** [NLog/NLog.Web#203]
The latest stable build of NLog.Web.AspNetCore, 4.4.1, currently depends upon NLog 5.0.0-beta07 or above. I'm not quite sure how it is possible for a stable build to be dependent upon an unstable build. Is this intentional or an oversight? If it is intentional, is the NLog 5 beta series really beta? If it is still beta, is there a work around that allows me to utilize the latest stable version of NLog against a version of NLog.Web.AspNetCore? I don't feel confident utilizing beta versions in a production environment...

Thanks.

**Comment by bburman** [comment]
If anyone else runs into this problem, I have a reasonable solution, but still require one pre-release assembly. Install the following:

NLog: 4.4.12
NLog.Web.AspNetCore: 4.2.4
NLog.Extensions.Logging: v1.0.0-rtm-beta7

Thanks.

**Comment by 304NotModified** [comment]
nlog.web.aspnetcore is stable, but only for full .NET 

NLog 5 is not RTM indeed. It was expected it would be earlier RTM.

So it's all intentional, but not perfect

**Comment by bburman** [comment]
Ok. Thanks for the info! I'll be awaiting NLog 5 RTM.

BTW - I love NLog. It's one of the first packages I always pull into a new solution. Thanks for all of your hard work.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
