### ISSUE TITLE
Additional Request Layout renderers + split into new layout renderers

### ISSUE THREAD

**Issue by epignosisx** [NLog/NLog.Web#21]
What do you think about including AspNet layout renderers for the following:

1.  User Agent: useful to correlate an issue with an specific browser or better yet to identify that a bot performed the request and ignore the error since must likely the bot passed invalid data.
2. Request Url: super important to try to reproduce the error. What page generated the error!
3. Referer Url: useful when trying to understand how a user end up in the current url.
4. Post Body: critical to know what data the user entered that generated the error. Caveat: we have to provide a way to mask certain information like PII and PCI.
5. IP Address: useful for analytics. You can understand where your users are coming from.
6. True Client IP Address: if a website is behind a CDN like Akamai or CloudFlare the IP address the web app receives is from one of the nodes of the CDN, they usually send the true client IP in a HTTP header. Caveat: each CDN uses a different headers so we will need to make it configurable but have a few of the major players.

**Comment by 304NotModified** [comment]
Sounds nice! We can do this all now I think, but all in a generic approach (`${aspnet-request}`).

6 is a bit to detailed, but we can make a `${aspnet-request-header}`?

I also miss some MVC related stuff now (route name, controller, action). Do you think is appropriate to add them to this repos?

**Comment by epignosisx** [comment]
You are right. Most of what I'm proposing can be obtained with {aspnet-request}. 
It is true (6) is too specific, but it can be done with ServerVariables, however, it is not very intuitive:

Say you send a header like this:

    X-Forwarded-For: 105.45.66.789

You would retrieve it like:

    Request.ServerVariables["HTTP_X_FORWARDED_FOR"]

Yes, prefixed with "HTTP_",  all uppercase, and dashes become underscores.

Creating a ${aspnet-request-header} would make it more intuitive, or we could also extend the ${aspnet-request} to have a **Header** property and look in **Request.Headers**.

======================

Personally I don't find the controller name and action name very useful. I can always infer it from the request url, but others may find them useful. The good thing is that the API to retrieve this information is not in **System.Web.Mvc**, but rather **System.Web.Routing**. I don't like the idea of taking a reference on **System.Web.Mvc** in NLog.Web. As a user, I wouldn't be happy to have a Web Forms only app, have NLog.Web put a System.Web.Mvc assembly in the bin folder.

**Comment by epignosisx** [comment]
I don't think we can get Number 4 (Post Body) from the current layout renderers. We are able to access individual keys of the Request.Form but not the whole body as a string.

**Comment by 304NotModified** [comment]
I'm not sure, but if it's possible, it's definitely (too) difficult. So added 4 is a good idea.

Not sure if I was clear before. Most of it is possible now, but I think your proposals are a really good addition. (when we replace 6 with something that looks in request header)

> Creating a ${aspnet-request-header} would make it more intuitive, or we could also extend the ${aspnet-request} to have a Header property and look in Request.Headers.

Both has up- and downsides. I think a separate is easier to implement and is easier to maintain, so that has my preference. Do you agree?

**Comment by epignosisx** [comment]
I agree with your reasons to have a separate **${aspnet-request-header}**.

However, it starts making the NLog.Web layout renderers API a little asymmetrical. Up until now, ${aspnet-request} was the way to get data from the request NameValueCollections. Headers are not different.

For symmetry I think we should break down ${aspnet-request} into:
- ${aspnet-request-querystring}
- ${aspnet-request-form}
- ${aspnet-request-cookie}
- ${aspnet-request-servervariable}

I think it makes for a better self-documented API/configuration.

**Comment by 304NotModified** [comment]
Agree with that. Of course we need to keep the old one for backwards compatibility.

**Comment by 304NotModified** [comment]
With the (breaking) changes in DNX, this would be a good time to implement.

**Comment by 304NotModified** [comment]
Fixed by https://github.com/NLog/NLog.Web/pull/54
