### ISSUE TITLE
Configure NLog in Main based on hosting environment

### ISSUE THREAD

**Issue by pholly** [NLog/NLog.Web#213]
ASP.NET Core 2.0

I see how it makes sense to configure NLog at the start of the program using this line in `Program.cs` `Main`:
`var logger = NLogBuilder.ConfigureNLog("NLog.config").GetCurrentClassLogger();`

But I have slightly different NLog.config files based on development or production environments: `nlog.config`, `nlog.dev.config`.

The hosting environment is not determined yet in `Main` of `Program.cs` so I can't pass in the file name based on the hosting environment.

Should I move the `ConfigureNLog` line to `Startup.cs`, where I can inject the `IHostingEnvironment`? If so, it will be called after `UseNLog()` on the `IWebHostBuilder` in `Program.cs`. Is that ok? If not, then I could call it from within `ConfigureAppConfiguration` of the `IWebHostBuilder` because the hosting environment is exposed there. That's what `CreateDefaultBuilder` uses: https://github.com/aspnet/MetaPackages/blob/dev/src/Microsoft.AspNetCore/WebHost.cs#L153

Thanks,
Philip

**Comment by pholly** [comment]
I ended up configuring it this way in `Program.cs`. NLog is not configured in `Main` but I'm ok with that. Let me know if there's a better way.

```C#
public class Program
    {
        public static void Main(string[] args)
        {
           BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    var env = hostingContext.HostingEnvironment;

                    var logConfigPath = "nlog.config";
                    if (env.IsDevelopment())
                    {
                        logConfigPath = "nlog.dev.config";
                    }
                    env.ConfigureNLog(logConfigPath);
                })
                .UseUrls("http://*:5004")
                .UseStartup<Startup>()
                .UseNLog()
                .Build();
    }
```

**Comment by 304NotModified** [comment]
I think this is a fine solution. The downside is that errors thrown by `BuildWebHost` aren't logged, but I think the change for that is low.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by kiapanahi** [comment]
I know this issue is closed but will share my experience in doing so anyway.

I ended up doing something like the following:

```csharp
       public static void Main(string[] args)
        {
            var configuringFileName = "nlog.config";

            //If we inspect the Hosting aspnet code, we'll see that it internally looks the 
            //ASPNETCORE_ENVIRONMENT environment variable to determine the actual environment
            var aspnetEnvironment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");

            var environmentSpecificLogFileName = $"nlog.{aspnetEnvironment}.config";

            if (File.Exists(environmentSpecificLogFileName))
            {
                configuringFileName = environmentSpecificLogFileName;
            }

            // NLog: setup the logger first to catch all errors
            var logger = NLogBuilder.ConfigureNLog(configuringFileName).GetCurrentClassLogger();
            try
            {
                logger.Debug("Application started");
                BuildWebHost(args).Run();
            }
            catch (Exception ex)
            {
                //NLog: catch setup errors
                logger.Error(ex, "Stopped program because of exception");
                throw;
            }
            finally
            {
                // Ensure to flush and stop internal timers/threads before application-exit (Avoid segmentation fault on Linux)
                LogManager.Shutdown();
            }
        }
```

And in my project, I have a number of different `nlog.{environment_name}.config` files just like `appsettings.{environment_name}.json`.

I understand that it may not be the perfect solution since it's not leveraging the injection if `IHostingEnvironment` but it gets the job done :)

**Comment by pholly** [comment]
Nice solution!

**Comment by mertabrak** [comment]
ASPNETCORE_ENVIRONMENT may be empty. That means it is Production (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.1). So your code should be modified a little:
 var aspnetEnvironment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
if (string.IsNullOrEmpty(aspnetEnvironment ))
   aspnetEnvironment = EnvironmentName.Production;

**Comment by pholly** [comment]
Production nlog config is usually nlog.config, not nlog.Production.config.
So if the environmental variable is empty, his code will not find a
"nlog..config" file so it will load the default nlog.config.

**Comment by mertabrak** [comment]
It's not clear at all. You are expecting of file nlog.{configuration}.config but surprisingly nlog.Production.config is not you are expected when configuration=Production. BTW I can set  ASPNETCORE_ENVIRONMENT=Production directly in VS or Azure portal. So if I have 2 files: nlog.config and nlog.Production.config I'll get different behavior depending on if ASPNETCORE_ENVIRONMENT=Production set directly or not

> Production nlog config is usually nlog.config, not nlog.Production.config.
So if the environmental variable is empty, his code will not find a
"nlog..config" file so it will load the default nlog.config.

**Comment by formalist** [comment]
If the differences between development  and production environments are are matter of 'variables' (e.g. the path of the log files, or the log levels), instead of having TWO nlog config files you can have **ONLY ONE SINGLE nlog.config** and use the **[ConfigSetting Layout Renderer](https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer)** to 'point' to settings in the respective **appsettings.development.json, appsettings.production.json** files. Ex.

nlog.config :
```
<nlog>
	<targets>
		<target fileName="${configsetting:item=LogPath}/MyLog.log"  [...]  />
	</targets>
<nlog>

```
appsetting.development.config :
```
{
    "LogPath":"C:/LogPathDev"
}
```

```
appsetting.production.config :
{
    "LogPath":"C:/LogPathProd"
}

```

**Comment by snakefoot** [comment]
Created wiki-page: https://github.com/NLog/NLog/wiki/Environment-specific-NLog-Logging-Configuration
