### ISSUE TITLE
Config file needs to be exactly NLog.config on Linux

### ISSUE THREAD

**Issue by rhyswat** [NLog/NLog.Web#214]
From https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(csproj---vs2017)

> Create nlog.config (lowercase all) file in the root of your project.

Lower-case all prevents the file from being loaded on Ubuntu (dotnet 1.1). The file needs to be `NLog.config` capital N capital L.

The troubleshooting guide alludes to this by refering to the file as `NLog.config` but doesn't spell it out (https://github.com/NLog/NLog/wiki/Logging-troubleshooting).

This might be true on other case-sensitive platforms as well.

**Comment by 304NotModified** [comment]
This should be fixed in the latest beta of NLog 4.5.

**Comment by 304NotModified** [comment]
(There is a relayed issue some where in NLog/NLog.web/NLog.extensions.logging repo, but can't find it now on mobile)

**Comment by rhyswat** [comment]
@304NotModified 10-4 thanks.

**Comment by 304NotModified** [comment]
Fixed by https://github.com/NLog/NLog/pull/2298

so NLog 4.5 beta 3
