### ISSUE TITLE
Dependency injection on custom target with aspnetcore

### ISSUE THREAD

**Issue by BennyM** [NLog/NLog.Web#216]
Hi

I'm trying to hook into the aspnet core dependency injection since my custom target has, well, a dependency.

When configuring via the solution as mentioned in the samples: `env.ConfigureNLog()` I get an error because I have a constructor argument. I also think it's being evaluated before `ConfigureServices` is being called and that's the earliest I can get a reference to my container and then configure the method `NLog.Config.ConfigurationItemFactory.Default.CreateInstance` to use the serviceprovider.

```
NLog.Config.ConfigurationItemFactory.Default.CreateInstance = (type) => provider.GetService(type);
```

I can get it to call the CreateInstance method if I remove `env.ConfigureNLog()` in `Startup` and use this in the `Configure` method.

```
loggerFactory.AddNLog();
loggerFactory.ConfigureNLog(env.ContentRootPath + "//nlog.config");
app.AddNLogWeb();
```
But then I get other errors as I think all dependencies are then expected to be returned by the serviceprovider.

**Comment by 304NotModified** [comment]
Do you have an example of the custom target?

**Comment by 304NotModified** [comment]
l think you need: https://stackoverflow.com/a/42101946/201303

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
