### ISSUE TITLE
targets not being created

### ISSUE THREAD

**Issue by FlavioRodr** [NLog/NLog.Web#217]
Tried to use the default configuration file nlog.config, writing to c:\temp...., in a windows 10 machine, using asp net core v2 and visual studio code and no file was created.

Tried replace the path files to C:\Users\{UserName}\Documents\temp\ and only the  internal-nlog.txt was created but none of the targets

Do I need more setup?

**Comment by 304NotModified** [comment]
Please post the issue here and fill in the template: 

https://github.com/NLog/NLog/issues/new

Also please post the internal log on trace level

**Comment by FlavioRodr** [comment]
like you say, the internal log showed me what was wrong. I wasn't defining rules, so the targets couldn't be created.

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
