### ISSUE TITLE
NLog with ASP.NET Core 2.0 logging to db: How to set connection string?

### ISSUE THREAD

**Issue by stjephan** [NLog/NLog.Web#219]
I like to log to DB with NLog in an asp.net core 2.0 webapplication.
I used the "official" tutorial on:
https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2
but I did not find a prober how to setup the project that I can inject the db connection string to a variable in nlog.config like
> LogManager.Configuration.Variables["connectionString"] = ; <-- The value I have not before Startup class called

**Comment by snakefoot** [comment]
Have you tried like this:

```
LogManager.Configuration.Variables["myConnectionString"] =  "MyValue";
logFactory.Configuration.KeepVariablesOnReload = true;
LogManager.Configuration.Reload();
```

Then you can use this  `${var:myConnectionString}` in you Nlog.config when configuring the ConnectionString-property for the database-target.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by Eirenarch** [comment]
This solution doesn't work for me. What works is this

```
foreach (DatabaseTarget target in LogManager.Configuration.AllTargets.Where(t => t is DatabaseTarget))
{
    target.ConnectionString = Configuration.GetConnectionString("DefaultConnection");
}

LogManager.Configuration.Variables["connectionString"] = Configuration.GetConnectionString("DefaultConnection");
```

Somehow this doesn't feel right, maybe there should be some Configure method that handles this

**Comment by snakefoot** [comment]
@Eirenarch Maybe something like this is easier for you to get working:

```
var defaultConnection = Configuration.GetConnectionString("DefaultConnection");
NLog.GlobalDiagnosticsContext.Set("defaultConnection", defaultConnection);
```

Then you can use ${gdc:item=defaultConnection} in your nlog.config:

`<target xsi:type="Database" connectionString="${gdc:item=defaultConnection}" />`

**Comment by Eirenarch** [comment]
@snakefoot Thanks this did work and I think it is better than my version but the discoverability sucks quite a bit. Other ASP.NET Core extensions have configuration in their UseX method with a builder pattern and here we are looking at magic static methods and some weird syntax in the config

**Comment by snakefoot** [comment]
Nothing is written in stone, and contributions are welcome.

Would this be an improvement:

> var logger = NLog.LogManager.LoadConfiguration ("nlog.config")
>    .WithGlobalContext("defaultConnection", defaultConnection)
> .GetCurrentClassLogger();



Sent from my Samsung device


-------- Original message --------
