### ISSUE TITLE
Unique Id per rule for search according a rule

### ISSUE THREAD

**Issue by stjephan** [NLog/NLog.Web#220]
Use case: change config on runtime in the case there are multiple rules with same LoggerNamePattern. I cannot different which is the Rule I like to change. Sample:
>     <logger name="*" minlevel="Trace" writeTo="allfile" />
>     <logger name="*" minlevel="Warning" writeTo="ownFile-web" />

I cannot change for example the fist rule to minLevel=Debug on runtime in code. We must provide a restendpoint which allows to enable some logging information in specific situations.

A property like "id" would help to identifiy.

**Comment by stjephan** [comment]
Found out that there is already a feature request for that:
https://github.com/NLog/NLog/issues/2394

**Comment by 304NotModified** [comment]
thanks for finding the duplicate. I will close this one to have the discussion at one place.

**Comment by 304NotModified** [comment]
l
