### ISSUE TITLE
The Name 'NLogBuilder' does not exist in the current context

### ISSUE THREAD

**Issue by rusdawg400** [NLog/NLog.Web#221]
In my 'asp.net core 2' project I am unable to configure Nlog as specified in the document located here:

https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2

Visual studio is providing an error message of: 
'The Name 'NLogBuilder' does not exist in the current context'

**Comment by 304NotModified** [comment]
is this https://github.com/NLog/NLog.Web/issues/208?

**Comment by rusdawg400** [comment]
I guess so, but It is not clear on how to resolve this issue.   Is the documentation up to date?

**Comment by rusdawg400** [comment]
The Example located at :   https://github.com/NLog/NLog.Web/blob/master/examples/ASP.NET%20Core%202/Visual%20Studio%202017/ASP.NET%20Core%202%20-%20VS2017/Program.cs

does not match the documentation.    Can this be updated to a working example?

**Comment by 304NotModified** [comment]
> does not match the documentation. Can this be updated to a working example?

Could you highlight the differences for me please? I'm currently working on .NET 4.6.1 to get it working on ASP.NET Core 2

**Comment by rusdawg400** [comment]
There is no using statement in the file.  So it could not possibly work

**Comment by 304NotModified** [comment]
I will check. The last time the sample builds and runs at my local machine. 

Maybe it's a different platform (netstandard 2.0 vs .net 4.6.1)

**Comment by 304NotModified** [comment]
Fixed in Fixed in Nlog.Web.AspNetCore 4.5 rc1
