### ISSUE TITLE
AssemblyVersionLayoutRenderer not working for net451 + net461

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.Web#222]
Think there are some problems

- NLog.Web.AspNetCore.csproj - This will cause net451to include PlatformAbstractions:
```
<ItemGroup Condition=" '$(TargetFramework)' != 'netstandard2.0' ">
   <PackageReference Include="Microsoft.Extensions.PlatformAbstractions" Version="1.0.0" />
```

- AssemblyVersionLayoutRenderer.cs - The first `#if` will match net451
```
#if ASP_NET_CORE && !NETSTANDARD2_0
        private static string GetAssemblyVersion()
        {
            return PlatformServices.Default.Application.RuntimeFramework.Version.ToString();
        }
#elif NETSTANDARD2_0
        private static string GetAssemblyVersion()
        {
            return System.Reflection.Assembly.GetEntryAssembly().GetName().Version.ToString();
        }
#else
```

There is also missing a null-check for GetEntryAssembly() for NETSTANDARD2_0, as it can return null. 

Not sure why NetStandard15 cannot use GetEntryAssembly() just like NETSTANDARD2_0?

Instead of using PlatformServices.Default.Application.RuntimeFramework.Version for NetStandard13, then it should be:

`Microsoft.Extensions.PlatformAbstractions.PlatformServices.Default.Application.ApplicationVersion`

**Comment by 304NotModified** [comment]
> NLog.Web.AspNetCore.csproj - This will cause net451to include PlatformAbstractions:
> <ItemGroup Condition=" '$(TargetFramework)' != 'netstandard2.0' ">
>    <PackageReference Include="Microsoft.Extensions.PlatformAbstractions" Version="1.0.0" />

Is this a problem? .NET 4.51+ is supported? https://www.nuget.org/packages/Microsoft.Extensions.PlatformAbstractions/

**Comment by snakefoot** [comment]
> Is this a problem? .NET 4.51+ is supported?

No just unnecessary dependencies. Only needed for NetStandard1.3, so maybe just move it to a seperate section for NetStandard1.3
