### ISSUE TITLE
Add MVC layout renderers

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#23]
Proposal:

add the following layout renderers.

- `${mvc-action}`
- `${mvc-controller}`
- `${mvc-route}`

Needs `System.Web.Mvc`. But that's I think now problem, as the layout renders just won't work if MVC is not included. 

It's unclear if we need `<assemblyBindings>` for the different MVC version (3,4,5 etc)

and what about API projects? (which has also actions and controllers)

**Comment by epignosisx** [comment]
I don't think we need a reference to System.Web.Mvc. All the routing stuff lives in System.Web.Routing which is part of the NET framework similar to System.Web.

**Comment by 304NotModified** [comment]
Thanks for the info! I think your right! 

I would find these mvc extensions useful. Any thoughts with the naming? (mvc VS rest api)

**Comment by epignosisx** [comment]
I don't think having mvc in the name is a good idea because Web Forms also [support routes](https://msdn.microsoft.com/en-us/library/cc668177.aspx) and the same code should work for both. Maybe:

- ${route-controller}
- ${route-action}
- ${route-name}

since **controller** and **action** are just keys maybe we could just have a generic:

- ${route:key=controller}

For WebApi we could probably use:

- ${webapi-controller}
- ${webapi-action}
- ${webapi-route-name}

**Comment by 304NotModified** [comment]
Do we need special layout renders for the Web API ? Those are also using routes?

I agree that the mvc prefix is problematic with Web Forms. We have also aware of possible name clashes. So I propose:

- ${aspnet-route-controller}
- ${aspnet-route-action}
- ${aspnet-route-name}

Note: Web API and Web Forms are also "ASP.NET"

**Comment by epignosisx** [comment]
I made the distinction between MVC/WebForms and WebAPI because I believe WebAPI uses its own routing mechanism. I have to confirm, though.

**Comment by Page-Not-Found** [comment]
@epignosisx 
>I don't think we need a reference to System.Web.Mvc. All the routing stuff lives in System.Web.Routing which is part of the NET framework similar to System.Web.

I trying to implement the same as part of #53 But I am not able to access these information in Routing Namespace. Do you have any idea?

**Comment by Page-Not-Found** [comment]
Any help with this.?

**Comment by 304NotModified** [comment]
@Page-Not-Found will check this, this weekend

**Comment by Page-Not-Found** [comment]
Thank you. A pointers would be good.

**Comment by 304NotModified** [comment]
> I trying to implement the same as part of #53 But I am not able to access these information in Routing Namespace. Do you have any idea?

This build, but dunno if it works. Can you test this?

```c#
            var context = new HttpContextWrapper(HttpContext.Current);
            var routeData = RouteTable.Routes.GetRouteData(context);
            var controller = routeData.Values["controller"];
```

**Comment by 304NotModified** [comment]
fixed by https://github.com/NLog/NLog.Web/pull/54
