### ISSUE TITLE
ASP.NET Core 2 - SetMinimumLevel not working with UseNLog()

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#234]
I can confirm the SetMinimumLevel isn't working in the sample anymore in ASP.NET Core 2 when using the NLogBuilder

the debug and trace logs are still removed when using the DI logger

related https://github.com/NLog/NLog.Web/issues/193, https://github.com/NLog/NLog.Web/issues/175, https://github.com/NLog/NLog.Web/issues/167

this works, but is not using `UseNLog` but the older `ConfigureNLog`

```c#
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureLogging((host, builder) =>
                {
                    host.HostingEnvironment.ConfigureNLog("nlog.config");
                    builder.SetMinimumLevel(LogLevel.Trace);
                })
                .UseStartup<Startup>()
                .Build();
```

**Comment by snakefoot** [comment]
This works for me:

```
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .ConfigureLogging((h,l) =>
                {
                    h.HostingEnvironment.ConfigureNLog("nlog.config");
                    l.SetMinimumLevel(LogLevel.Trace);
                })
                .UseApplicationInsights()
                .UseNLog()
                .Build();
```

**Comment by snakefoot** [comment]
But not this:

```
        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureLogging((h, l) =>
                {
                    h.HostingEnvironment.ConfigureNLog("nlog.config");
                    l.SetMinimumLevel(LogLevel.Trace);
                })
                .UseApplicationInsights()
                .UseNLog()
                .Build();
```

**Comment by snakefoot** [comment]
It now seems that `appsettings.json` (Or `appsettings.Development.json` when debugging). Have higher priority:

Changing `Default`-level will fix everything.

```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Trace",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}
```

**Comment by snakefoot** [comment]
But if I remove the `"Default": "Trace",` completely from appsettings.json then SetMinimumLevel also works.

Guess it matches the documentation:

> There is a minimum level setting that takes effect only if no rules from configuration or code apply

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x

And it seems configuration override takes higher priority than code.

```
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using NLog.Web;

    public static class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureAppConfiguration((builderContext, config) => {
                    IHostingEnvironment env = builderContext.HostingEnvironment;
                    config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                    .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);
                })
                .ConfigureLogging(logging =>
                {
                    logging.ConfigureNLog("nlog.config");
                    logging.SetMinimumLevel(LogLevel.Trace);
                })
                .UseApplicationInsights()
                .UseNLog()
                .Build();
```

**Comment by 304NotModified** [comment]
Funny, tried also the default in the json, but I didn't work. Thanks for checking, will read your analysis in depth and will retest.

**Comment by stjephan** [comment]
@304NotModified Sorry for this question. Did you changed the right appsettings.json File? I had the same problem that I couldn't reproduce the what snakefoot described. I did not change the settings inside the right appsettings.json 
The code from snakefoot contains following line:
`(.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);`

I can confirm what snakefoot described: 

> It now seems that appsettings.json (Or appsettings.Development.json when debugging). Have higher priority:

My code:
```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Critical"
    }
  }
}

```
 public static IWebHost BuildWebHost(string[] args)
        {
            //return WebHost.CreateDefaultBuilder(args)
            //    .UseStartup<Startup>() // use NLog for DI Logger
            //    .UseNLog()
            //    .Build();
            var builder = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    var env = hostingContext.HostingEnvironment;

                    config.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                        .AddJsonFile("mappersettings.json", false, true)
                        .AddJsonFile("loggersettings.json", false, true)
                        .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);

                    if (env.IsDevelopment())
                    {
                        var appAssembly = Assembly.Load(new AssemblyName(env.ApplicationName));
                        if (appAssembly != null)
                        {
                            config.AddUserSecrets(appAssembly, optional: true);
                        }
                    }

                    config.AddEnvironmentVariables();

                    if (args != null)
                    {
                        config.AddCommandLine(args);
                    }
                })
                .ConfigureLogging((hostingContext, logging) =>
                {
                    //logging.AddConsole();
                    logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
                    //logging.AddDebug();                    
                    logging.SetMinimumLevel(LogLevel.Trace);
                })
                .UseIISIntegration()
                .UseDefaultServiceProvider((context, options) =>
                {
                    options.ValidateScopes = context.HostingEnvironment.IsDevelopment();
                })
                .ConfigureServices(services =>
                {
                    services.AddTransient<IConfigureOptions<KestrelServerOptions>, KestrelServerOptionsSetup>();
                });

            return builder.UseStartup<Startup>().UseNLog().Build();
        }
```
```

**Comment by 304NotModified** [comment]
in summary, this fixes the issue. See the example in git

```xml
{
    "Logging": {
        "IncludeScopes": false,
        "LogLevel": {
            "Default": "Trace",
            "Microsoft": "Information"
        }
    }
}
```

**Comment by 304NotModified** [comment]
> I propose to remove all other logging provider in the case of using NLOG. My opinion is that all settings for logging should be in one file. So in the case of NLOG use only nlog.config.

Please open a new issue for this. Unfortunately, others has stated otherwise in the past.
