### ISSUE TITLE
Use LoggerFactory instead of LoggerProvider

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#235]
current pro and cons:

pro
- faster (less overhead)
- MEL-Filtering ignored (less confusion for some)

con:
- AddConsole and other MS stuff not working - see https://github.com/NLog/NLog.Web/issues/199
- Init config of AddConsole etc ignored
- MEL-Filtering ignored (more confusion for some)

**Comment by 304NotModified** [comment]
also related: https://github.com/NLog/NLog.Extensions.Logging/pull/202

**Comment by alexandrejobin** [comment]
pros
- you only have one configuration file to configure everything instead of two
- a lot less confusion

cons
- you have to choose between Microsoft Logger framework and NLog because you can't use both but since that nlog already have targets for Console et Debug, you don't really lose any feature

My opinion is that if you want to register a new provider in the LoggerProvider, you must fully follow the way it work. It must be driven only by the Logger configuration.

Since that nlog is not a real provider for the Logger but a full logging framework, I think it make sens that nlog should take full control of the logging system. Why choose AddConsole and AddDebug when nlog already have targets for them?

**Comment by 304NotModified** [comment]
Thanks! I think you're right. It would be nice if we could support both (referring to `you have to choose between Microsoft Logger framework and NLog because you can't use both `).

This is a breaking change, thus I think it should be V5 if applied

**Comment by alexandrejobin** [comment]
When you call UseNLog, maybe we can pass a parameter to tell if you want to use it as a full framework or a provider for Logger?

**Comment by alexandrejobin** [comment]
So what are you suggesting? You've said that you wanted to support both :)

**Comment by snakefoot** [comment]
See also https://github.com/aspnet/Logging/issues/420

**Comment by snakefoot** [comment]
Just some random noise. It is only  `serilog-aspnetcore` that performs the LoggerFactory replace.

While `serilog-extensions-logging` is playing nice with Microsoft Extension Logging-framework.

Looks like `serilog-extensions-logging` is more widely used than `serilog-aspnetcore`:

https://www.nuget.org/packages/Serilog.Extensions.Logging/
https://www.nuget.org/packages/serilog.aspnetcore/

**Comment by nblumhardt** [comment]
@snakefoot _Serilog.AspNetCore_ has a dependency on _Serilog.Extensions.Logging_, so the latter will always be ahead in download counts :-) It's also much older, so there's a lot of outdated documentation/blog posts/tutorials out there that still point to the older package. Cheers!

**Comment by snakefoot** [comment]
If wanting Serilog to live along with AppInsights-Telemetry, then one will have to step around Serilog.AspNetCore. Because of the LoggerFactory-swap-trick:

https://github.com/serilog/serilog-aspnetcore/issues/60
https://github.com/SteeltoeOSS/Management/issues/21

**Comment by snakefoot** [comment]
Serilog is now working on implementing their own custom version of LoggerFactory with full support of external LoggerProviders. Special headaches might arrive in supporting the same new features that arrives with the official LoggerFactory for new platform versions, while still trying to support older platform versions (Ex. `IExternalScopeProvider`)

https://github.com/serilog/serilog-extensions-logging/pull/132

**Comment by snakefoot** [comment]
Resolved by  #657 that adds the option `ReplaceLoggerFactory` (And `RemoveLoggerFactoryFilter` that will become enabled by default with ver. 5)
