### ISSUE TITLE
Main() Error:System.ArgumentOutOfRangeException:“Index and count must refer to a location within the string.”

### ISSUE THREAD

**Issue by haijiandong** [NLog/NLog.Web#237]
- VS version:15.4.0
- Windows version:Windows10
- ASP.NET CORE:2.0
- NLog:5.0.0-beta11
- NLog.Web.AspNetCore:4.5.0-rc2

Program=>Main:
```cSharp
var logger = NLogBuilder.ConfigureNLog("NLog.config").GetCurrentClassLogger();
try
 {
       logger.Debug("init main");
       BuildWebHost(args).Run();
}
catch (Exception e)
{
       logger.Error(e, "Stopped program because of exception");
        throw;
}
```
![image](https://user-images.githubusercontent.com/12838659/33753092-81556aec-dc20-11e7-87bd-fc4d29290975.png)

**Comment by snakefoot** [comment]
Could you paste the callstack here also ? (exception.ToString())

Could you try and use NLog 4.5 rc02 instead of NLog 5.0. Because NLog 5.0 BETA  is very stale, and should no longer be used.

**Comment by snakefoot** [comment]
If possible then please activate NLog InternalLogger, and attach the log-file. See https://github.com/NLog/NLog/wiki/Internal-Logging

**Comment by haijiandong** [comment]
@snakefoot  Sorry, I forgot the attached callstack.
StackTrace:
```Shell
   at System.String.CopyTo(Int32 sourceIndex, Char[] destination, Int32 destinationIndex, Int32 count)
   at System.Uri.GetCanonicalPath(Char[] dest, Int32& pos, UriFormat formatAs)
   at System.Uri.ReCreateParts(UriComponents parts, UInt16 nonCanonical, UriFormat formatAs)
   at System.Uri.GetUnescapedParts(UriComponents uriParts, UriFormat formatAs)
   at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
   at System.Uri.ToString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at NLog.Config.XmlLoggingConfiguration..ctor(String fileName, Boolean ignoreErrors, LogFactory logFactory)
   at NLog.Web.NLogBuilder.ConfigureNLog(String configFileName)
```

**Comment by snakefoot** [comment]
Strange. It looks like a bug in `System.Uri.ToString`

Have you tried NLog 4.5 rc02 ?

**Comment by haijiandong** [comment]
@snakefoot Yes, I try to NLog 4.5 rc-02, still so.
[Error example](https://drive.google.com/file/d/1VPzSoTm8SgIZo_QSBHO6JgJkRPUJyh71/view)
Thank you.

**Comment by 304NotModified** [comment]
what's in the rar?

Please share your full config, thanks!

**Comment by snakefoot** [comment]
> what's in the rar?

It contains the entire solution. Including the NLog.config

>Please share your full config, thanks!

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="info"
      internalLogFile="c:\temp\internal-nlog.txt">

  <!-- the targets to write to -->
  <targets>
    <!-- write logs to file  -->
    <target xsi:type="File" name="allfile" fileName="c:\temp\nlog-all-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|${message} ${exception}" />

    <!-- another file log, only own logs. Uses some ASP.NET core renderers -->
    <target xsi:type="File" name="ownFile-web" fileName="c:\temp\nlog-own-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|${message} ${exception}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}|${callsite}" />

    <!-- write to the void aka just remove -->
    <target xsi:type="Null" name="blackhole" />
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Trace" writeTo="allfile" />

    <!--Skip Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />
    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />
  </rules>
</nlog>
```

**Comment by snakefoot** [comment]
@304NotModified Why is it that full path is not used for `ConfigureNLog`, will it not be a random current directory ? (Maybe check if not full path then prefix with LogFactory.CurrentAppDomain.BaseDirectory)

@haijiandong When the exception occurs in the debugger, could you show the output of current directory? `System.IO.Directory.GetCurrentDirectory()`

**Comment by snakefoot** [comment]
@haijiandong Could you also show the output from `Path.GetFullPath("NLog.config")` when the exception occurs?

**Comment by haijiandong** [comment]
@snakefoot OK.
![image](https://user-images.githubusercontent.com/12838659/33795203-29522efe-dd18-11e7-8416-f79d63f2ba17.png)
![image](https://user-images.githubusercontent.com/12838659/33795208-4a28450a-dd18-11e7-8e2a-3779962cc53d.png)

**Comment by snakefoot** [comment]
What happens if you place the application in path that only uses the letters  A-Z (without Asian sign letters)



Sent from my Samsung device


-------- Original message --------

**Comment by haijiandong** [comment]
@snakefoot  Oops..I forget such an important matter,can run after removed the path of the Chinese characters.
Thank you for your help!

**Comment by heidgert** [comment]
I had the exact same problem. Turned out I had the Swedish character "ä" in one of my folders' names. 

The problem disappeared after changing this character to an "a" instead.

**Comment by zousq19910623** [comment]
![image](https://user-images.githubusercontent.com/27879494/37021029-f85bd69e-2158-11e8-9a29-4149a9284c1a.png)

when i start my .net core project.
when proceed to here,,then turn out this error.

**Comment by zousq19910623** [comment]
![image](https://user-images.githubusercontent.com/27879494/37021099-5301afe2-2159-11e8-8006-eea9f7127cf1.png)

the error detail.

**Comment by zousq19910623** [comment]
is there any one who know how to solve this problem.
thx.

**Comment by 304NotModified** [comment]
Well it seems to be a bug in `System.Uri.ToString`, so currently the work around is to use ASCII characters

**Comment by 304NotModified** [comment]
related https://github.com/dotnet/corefx/issues/25519

**Comment by rmkerr** [comment]
Yep, the URI issue you're seeing should be fixed in .NET Core 2.1. If you'd like to check it out yourself, the first pre-release is available now.

**Comment by zousq19910623** [comment]
thx for your help.
@304NotModified @rmkerr

**Comment by 304NotModified** [comment]
I'm closing this as it's an external issue
