### ISSUE TITLE
Nlog does not log Trace events in asp.net core 2

### ISSUE THREAD

**Issue by xumix** [NLog/NLog.Web#238]
NLog.Web.AspNetCore 4.5.0-beta04, asp.net core 2.0.3

The code: https://gist.github.com/xumix/3cfb305dfd0f3cb743f9f25908212e4e
I add in Startup.cs
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole();
            loggerFactory.AddDebug();
            app.UseMiddleware<RequestLoggingMiddleware>();

            LayoutRenderer.Register("basedir", (logEvent) => env.ContentRootPath);
}
```
```<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="info"
      internalLogFile="c:\temp\internal-nlog.txt">
  <!-- the targets to write to -->
  <targets>
    <target xsi:type="File" name="request-file" fileName="${basedir}/logs/request-${shortdate}.log"
            layout="${longdate}|${uppercase:${level}}|${logger}|${message}" />
  </targets>

 <rules>
    <logger name="*RequestLoggingMiddleware*" writeTo="request-file" final="true" />
  </rules>
</nlog>

```

If I change ```logger.LogInformation(requestLog);``` to ```logger.LogTrace(requestLog);``` then no logging occurs, even if I add minlevel="Trace"

**Comment by 304NotModified** [comment]
Use configureLogging and 

 builder.SetMinimumLevel()

PS on mobile now

**Comment by snakefoot** [comment]
Program.cs should be extended to include `ConfigureLogging(l => l.SetMinimumLevel(LogLevel.Trace))` :

```
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>()
            .ConfigureLogging(l => l.SetMinimumLevel(LogLevel.Trace))
            .UseNLog()
            .Build();
```

See also https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x

**Comment by 304NotModified** [comment]
> Program.cs should be extended to include ConfigureLogging(l => l.SetMinimumLevel(LogLevel.Trace)) :

This works with AddNLog (ASP.NET Core 1 style), but not with UseNLog (see #https://github.com/NLog/NLog.Web/issues/234) - any idea?

**Comment by 304NotModified** [comment]
> No idea. Just copy pasting random information :). Not developing ASP NET Applications.

Hopefully that doesn't mean WinForms ;)

**Comment by xumix** [comment]
@304NotModified @snakefoot  thanks!

**Comment by snakefoot** [comment]
> Hopefully that doesn't mean WinForms ;)

No just backend developer on various data-processing engines.

**Comment by snakefoot** [comment]
@304NotModified Tried to upgrade the old (now deleted) `aspnet-core-example-vs2017` to netcoreapp2.0, and it stopped logging trace.

I removed the `AddNLog()` calls from startup.cs, and instead called `.UseNLog()` in program.cs.

But when adding `.ConfigureLogging(l => l.SetMinimumLevel(LogLevel.Trace))` in program.cs, then trace worked again.

**Comment by snakefoot** [comment]
@xumix Maybe my rant at #234 might be useful. Seems asp.net core 2 will choose appsettings.json LogLevel-config when available.

**Comment by georgiosd** [comment]
@snakefoot you sir, are awesome. I would have never guessed that in a million years. Thank you. 

Removing config from appsettings.json and setting minimum level worked for me.

**Comment by 304NotModified** [comment]
See  https://github.com/NLog/NLog.Web/wiki/Missing-trace%5Cdebug-logs-in-ASP.NET-Core-2%3F

**Comment by paulostradioti** [comment]
Hi guys, 

It looks like this is still a problem in .NET Core 3.1.
Any advice, please?

**Comment by snakefoot** [comment]
Please create new issue instead of waking up old issues with your random problems. Remember to fill out the template with details about how you setup NLog


Sent from my Sony Xperia


---- Paulo Ricardo Stradioti wrote ----


Hi guys,

It looks like this is still a problem in .NET Core 3.1.
Any advice, please?

**Comment by 304NotModified** [comment]
@paulostradioti checked https://github.com/NLog/NLog.Web/wiki/Missing-trace%5Cdebug-logs-in-ASP.NET-Core-3%3F ?
