### ISSUE TITLE
System.IO.FileNotFoundException: Microsoft.Extensions.Logging.Filter

### ISSUE THREAD

**Issue by jimmy84** [NLog/NLog.Web#241]
During debug mode in net core 2.0, the below exception was thrown on line

`var logger = NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();`

I believe Microsoft.Extensions.Logging.Filter was no longer available after net core 1.1, or am I missing something here?

> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Filter, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> File name: 'Microsoft.Extensions.Logging.Filter, Culture=neutral, PublicKeyToken=null'
>    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
>    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)

**Comment by 304NotModified** [comment]
What version are you using? Please try the latest (prerelease), thx!

**Comment by snakefoot** [comment]
@jimmy84 I'm guessing this is the line causing the issue, and the application runs fine after the exception has occurred.

`SafeAddHiddenAssembly("Microsoft.Extensions.Logging.Filter", false);`

Must admit I also hate "expected" exceptions, as I often prefer to run with catch-all-exceptions.

Guess one could improve the logic, so there is a soft-check using (iterate the array and check if the assembly is available):

`AppDomain.CurrentDomain.GetAssemblies()`

Would probably change the `SafeAddHiddenAssemblies` to receive an HashSet of assembly-names.

**Comment by georgiosd** [comment]
What is the effect of this? I can't seem to get my logging to work... only the Microsoft namespace is logged!

**Comment by georgiosd** [comment]
Ok, not related to this. It was this, for anyone looking here: https://github.com/NLog/NLog.Web/issues/238#issuecomment-361683443

**Comment by snakefoot** [comment]
@304NotModified Resolved with #245

**Comment by 304NotModified** [comment]
Thanks!
