### ISSUE TITLE
aspnet-request-url doesn't include port

### ISSUE THREAD

**Issue by fvasquezc23** [NLog/NLog.Web#243]
Hi NLog team,

I'm using the "aspnet-request-url" placeholder on aspnet core 2.0 and the output is not rendering the port which the server is binded.

I'm expecting the value http://localhost:8080/api/test, but it prints http://localhost/api/test

Grettings

**Comment by 304NotModified** [comment]
Use the IncludePort property, see https://github.com/NLog/NLog/wiki/AspNetRequest-Url-Layout-Renderer

**Comment by fvasquezc23** [comment]
Thanks for the reply.

I'm closing the thread now.
