### ISSUE TITLE
How to close the log in the asp.net core mvc pipeline

### ISSUE THREAD

**Issue by cheesebar** [NLog/NLog.Web#244]
such as these logs
User profile is available. Using 'C:\Users\Jack\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/1.1 GET http://localhost:5000/  
Executing action method CopyCenter.DefaultController.Index (CopyCenter) with arguments ((null)) - ModelState is Valid

**Comment by 304NotModified** [comment]
Please elaborate, I don't understand your question.

What do you mean with "Close the log"?

**Comment by cheesebar** [comment]
now every request will write three logs about asp.net core mvc pipeline, i think these logs are meaningless and taking up the IO,so i want to close these logs and only recoed some log i want

**Comment by cheesebar** [comment]
such as these logs in action
 Logger.LogTrace("LogTrace");
 Logger.LogInformation("LogInformation");
 Logger.LogWarning("LogWarning");
 Logger.LogError("LogWarning");
 Logger.LogDebug("LogDebug");
 the constructor in controller
 public DefaultController(ILogger<DefaultController> logger)

**Comment by snakefoot** [comment]
@cheesebar Have you read the tutorial about setting up a `blackhole` to discard the Microsoft-logging-events:

https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2

**Comment by cheesebar** [comment]
This is my rules in nlog.config,but the logger name begin with 'Microsoft.*' still write to datebase
 <rules>
    
    <logger name="*" minlevel="Trace" writeTo="allfile" />
    <logger name="*" minlevel="Trace" writeTo="database" />
    
    <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />
    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />
  </rules>

**Comment by snakefoot** [comment]
@304NotModified Think this can be closed
