### ISSUE TITLE
Filename nlog.config should be NLog.config for Linux

### ISSUE THREAD

**Issue by hiren929** [NLog/NLog.Web#247]
Following statement at https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2
is incorrect : 
Create nlog.config (lowercase all) file in the root of your project. 

When project is deployed on linux, it looks for NLog.config instead of nlog.config. Everything works on Windows since file name casing doesn't matter.

Please fix.

**Comment by snakefoot** [comment]
@hiren929 Thank you for telling. Have updated the wiki for you.

**Comment by 304NotModified** [comment]
This is fixed already. Which nlog version are you using?

**Comment by snakefoot** [comment]
> This is fixed already. Which nlog version are you using?

It is the wiki-code-example that was faulty, where the explicit nlog.config load was performed with `NLog.config` (instead of `nlog.config`)

Your fix don't help in the situation where the filename is provide explicitly.

**Comment by 304NotModified** [comment]
Ok, thanks!
