### ISSUE TITLE
Support for different schema (other than dbo)

### ISSUE THREAD

**Issue by arunprasathv** [NLog/NLog.Web#251]
Does Nlog support different schema other than DB to write logs? @304NotModified @snakefoot 

It doesn't write logs to the table on different schema - Logging.Log.

**Comment by 304NotModified** [comment]
Yes, I use it daily. Maybe it's the permissions?

If this still an issue, please open an issue on the main repo: https://github.com/NLog/NLog/issues/new

**Comment by arunprasathv** [comment]
@304NotModified I noticed its not even logging on the table in dbo.logging. am i missing something? I'm using .Net Core API to log.

**Comment by 304NotModified** [comment]
>If this still an issue, please open an issue on the main repo: https://github.com/NLog/NLog/issues/new

**Comment by snakefoot** [comment]
@arunprasathv Have you tried like this:

```
var connectionString = Configuration.GetConnectionString("DbConnectionString");
LogManager.Configuration.Variables["connectionString"] = connectionString;
LogManager.Configuration.KeepVariablesOnReload = true;
LogManager.Configuration.Reload();
```

Alternative you could just use the GDC `${gdc:item=connectionString}` then no reload is needed:

```
var connectionString = Configuration.GetConnectionString("DbConnectionString");
GlobalDiagnosticsContext.Set("connectionString", connectionString);
```

**Comment by arunprasathv** [comment]
@snakefoot @304NotModified 

Here's my configuration, i have both file and DB as target. I see logs in file. I dont see any error as well. 

<target xsi:type="Database" name="dbTarget">
      <connectionString>${var:connectionString}</connectionString>
      <commandText>
        insert into [dbo].[DiagnosticsLogging] (Message, SeverityType, EntityType, LogTime, UserName, ExceptionMessage, Details)
        values (@Message, @SeverityType, @EntityType, @LogTime, @UserName, @UserIpAddress, @ExceptionMessage, @Details)">
      </commandText>  
      <parameter name="@SeverityType" layout="${level}" />
      <parameter name="@EntityType" layout="${event-context:EntityType}" />
      <parameter name="@Message" layout="${event-context:Message}" />
      <parameter name="@UserName" layout="${event-context:UserName}" />
      <parameter name="@ExceptionMessage" layout="${event-context:ExceptionMessage}" />
      <parameter name="@Details" layout="${event-context:Details}" />
      <parameter name="@LogTime" layout="${date}" />
    </target>

**Comment by arunprasathv** [comment]
@snakefoot LogManager.Configuration.KeepVariablesOnReload = true;

doesn't exist. i'm using 4.5, may be not supported in 4.5 ?

**Comment by snakefoot** [comment]
@arunprasathv Please don't post more random information here. Instead just follow the issue-template. This issue has nothing todo with the NLog.Web.AspNetCore integration, but learning how to use the database-target in NetCore (P.S. Have you tried `LogManager.KeepVariablesOnReload = true`, or any of the other advice given?)

**Comment by arunprasathv** [comment]
It works. Thanks. Internal log helped to find the issue.

**Comment by snakefoot** [comment]
Happy to hear. But remember the NLog.Web has its focus on the AspNetCore-integration. Standard NLog configuration issues goes here: https://github.com/NLog/NLog/issues/new :)
