### ISSUE TITLE
IWebHostBuilder doesn't contain definition for UseNLog()

### ISSUE THREAD

**Issue by devon-stanley** [NLog/NLog.Web#254]
I'm using the latest version of Nlog.Web.AspNetcore (4.5.0-rc3) but can't use the UseNLog method. 

As a workaround I had to update my Startup.cs with the following to add NLog to the configuration:

```
public void Configure(IApplicationBuilder app, 
    IHostingEnvironment env,
    ILoggerFactory loggerFactory)
{
    ...

    loggerFactory.AddNLog();
    app.AddNLogWeb();

    ...
}

```

And in my Program.cs

```
public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()            
        .ConfigureLogging((host, logging) =>
        {
            // Clear providers so logs don't get written to console
            logging.ClearProviders();
            host.HostingEnvironment.ConfigureNLog("nlog.config");
        })
        .Build();

```

This gets everything working but I'm getting  an obsolete warning
```
Startup.cs(38,13): warning CS0618: 'AspNetExtensions.AddNLogWeb(IApplicationBuilder)' is obsolete: 
'Use UseNLog() on IWebHostBuilder'
```

Is there something I'm missing here?

**Comment by 304NotModified** [comment]
Are you using .net core 1 or 2?

**Comment by snakefoot** [comment]
@devon-stanley Do you have this in top of your `Program.cs`

`using NLog.Web;`

**Comment by devon-stanley** [comment]
@304NotModified 
I'm using .net core 2.0:
`    <TargetFramework>netcoreapp2.0</TargetFramework>
`

@snakefoot 
Yes, I've included `NLog.Web` in my Program.cs file. 

I originally was following the 'Getting Started' link you referenced but had the following issue:
```
'LogManager' does not contain a definition for 'LoadConfiguration' 
```

Which is why I was using the `host.HostingEnvironment` to load the nlog.config file.

**Comment by BlueInt32** [comment]
Same issue here... On the screen shot you can see that NLog.Web isn't used.

![image](https://user-images.githubusercontent.com/2920038/37073961-44d24c58-21ca-11e8-910a-7d983d2548b9.png)

**Comment by snakefoot** [comment]
You are using the wrong version of NLog (Nlog 5 is now obsolete). Please read the tutorial link in my previous comment to see what version of Nlog and NLog.Web.AspNetCore to use



Sent from my Samsung device


-------- Original message --------

**Comment by devon-stanley** [comment]
@snakefoot
Based on the link you provided, we should be using:
NLog.Web.AspNetCore 4.5+
and
NLog 4.5.x for .NET Core 2

Is this wiki outdated? Should we be instead using NLog 4.4.X?

**Comment by BlueInt32** [comment]
Oh you're right, sorry. The "user-friendly" Nuget Manager in Visual Studio does not show the prereleases  by default so I blindly clicked on 4.4 version. 

Also the ConfigureLogging builder extension is in the Microsoft.Extensions.Logging package and while getting started with asp.net core and NLog at the same time, we can get confused wether the missing extensions come from a NLog setup problem or something else.

Anyway I ran : 

`dotnet add package NLog.Web.AspNetCore --version 4.5.0-rc3`

and made sure I had these usings : 

`using Microsoft.Extensions.Logging;
using NLog;
using NLog.Web;`

**Comment by devon-stanley** [comment]
So I'm not sure what was wrong with my local environment, but I was finally able get `UseNLog()` and `LoadConfiguration` working by:
1. Explicitly referencing NLog in the .csproj file by adding `<PackageReference Include="NLog" Version="4.5.0-rc06" />`
2. Clearing my nuget packages with `dotnet nuget locals --clear all`
3. Restore my dependencies `dotnet restore`

Thanks @snakefoot , @304NotModified and @BlueInt32  for the pointers!

**Comment by amrastanov-nitka** [comment]
<PackageReference Include="NLog.Web.AspNetCore" Version="4.9.3" />

**Comment by EricHerlitz** [comment]
Install NLog.Web.AspNetCore
Inject `ILoggingBuilder loggingBuilder`
and add
```
loggingBuilder.AddNLog();
loggingBuilder.AddNLogWeb();
```
