### ISSUE TITLE
[Suggestion] Add "using Microsoft.Extensions.Logging;" in Getting started

### ISSUE THREAD

**Issue by imxzjv** [NLog/NLog.Web#262]
From default template Core 2.0 applications users will see an error message while following the getting started guide (https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2) with two methods `ClearProviders `and `SetMinimumLevel `not found.

```
                .ConfigureLogging(logging =>
                {
                    logging.ClearProviders();
                    logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
                })
```

Guide mentions add `using NLog.Web;` but it should also mention the required `using Microsoft.Extensions.Logging;`. This needed reference is not being auto-found by visual studio/resharper with ALT+ENTER and therefore is not obvious.

**Comment by 304NotModified** [comment]
good idea, feel free to edit (it's a wiki)

**Comment by imxzjv** [comment]
ahh yep, so it is. done.

**Comment by 304NotModified** [comment]
Thanks!

**Comment by PJ-students** [comment]
Thanks :)

**Comment by hosseinRezaei188** [comment]
Thanks jeff
