### ISSUE TITLE
asp.net core 2 ${callsite-linenumber} not working

### ISSUE THREAD

**Issue by zzs89117920** [NLog/NLog.Web#267]
var logger = NLog.LogManager.LoadConfiguration("nlog.config").GetCurrentClassLogger();
logger.Info("test");
${callsite-linenumber}  work well

private readonly ILogger<HomeController> _logger;
public HomeController(ILogger<HomeController> logger)
{
	_logger = logger;
}
_logger.LogInformation("test");
${callsite-linenumber} not working

**Comment by 304NotModified** [comment]
Please check the internal log. See https://github.com/nlog/nlog/wiki/Logging-troubleshooting


If that's not helping,

Could you please describe the expected and current result and give us the versions of the nlog components (nlog, nlog.extensions.logging and nlog.web.aspnetcore)

**Comment by zzs89117920** [comment]
Nlog 4.5.0
Nlog.Extensions.Logging 1.0.0
Nlog.WebAspNetCore 4.5.0

![1](https://user-images.githubusercontent.com/5515847/38063672-c449d5e6-332c-11e8-979b-bcfcb838beb9.png)
![2](https://user-images.githubusercontent.com/5515847/38063675-ca764a12-332c-11e8-9fc1-89b397a4a9ac.png)
[2018-03-29 08:36:48.7091] INFO  testNlog.Program:
Main:23 
Program.cs linenumber:23

[2018-03-29 08:36:52.5714] INFO  testNlog.Controllers.HomeController:
LogInformation:0 
HomeController.cs linenumber:21

nlog.config
<target name="INFO_LOG_FILE"
		xsi:type="File"
		layout="[${longdate}] ${pad:padding=-5:inner=${level:uppercase=true}} ${logger}:${newline}${callsite:className=false}:${callsite-linenumber} ${newline}${message}${onexception:inner=${newline}${exception:format=ToString}}${newline}"
		fileName="Log/${var:logInfo:default=LogInfo}/${date:format=yyyy}/${date:format=yyyyMM}/${shortdate}.log" />

**Comment by snakefoot** [comment]
@zzs89117920 Try upgrading to Nlog.Extensions.Logging 1.0.1
