### ISSUE TITLE
custom provider for NLog doesn't wire up aspnet web layouts due to ServiceLocator pattern

### ISSUE THREAD

**Issue by timdoke** [NLog/NLog.Web#270]
In looking at the core code of the extension method UseNLog, I discovered there is an internal class called ServiceLocator where it sets the ServiceProvider, based on IServiceCollection during initialization.

I need to make a custom version of the service provider as I want to do some things that I don't believe are supported (creating a different loglevel on the logger based on a header value).  If I add the code for UseNLog and my code to add my provider, those missing log attributes get added, but there are two loggers now.. And I get duplicate logs.

If I don't call UseNLog, I get this error from the internal logger:(https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore/LayoutRenderers/AspNetLayoutRendererBase.cs)

Missing serviceProvider, so no HttpContext.

The attributes do not work correctly as they have a dependency on the ServiceLocator ServiceProvider being populated..

        <attribute name="requestIp" layout="${aspnet-Request-IP}"/>
        <attribute name="controller" layout="${aspnet-MVC-Controller}"/>
        <attribute name="action" layout="${aspnet-MVC-Action}"/>
        <attribute name="identity" layout="${identity}"/>

Please assist..

**Comment by timdoke** [comment]
Inside Configure, I pass an instance if ILoggerFactory as logging.

Then, I add a provider with this code:

```
logging.AddProvider(LoggingFactory.GetInstanceForStartup(context));

```
I have to pass the instance of context in for the aspnet core logging to get wired up..

```
        public static LoggingFactory GetInstanceForStartup(IHttpContextAccessor contextAccessor)
        {
            return new LoggingFactory(contextAccessor);
        }

        private LoggingFactory(IHttpContextAccessor contextAccessor)
        {
            this.HttpContextAccessor = contextAccessor;
            
        }


```
This class implements two interfaces.. one of mine, and ILoggerProvider..

I recently switched from log4net because I didn't want to implement json logging, so I'm still using my interface for getting this..  

I have this type of code inside a controller.. The ILoggingFactory gets created via dependency injection..

```
        private ILoggingFactory LoggingFactory { get; set; }
        private ILogging _log;
        private ILogging Logger
        {
            get
            {
                if (_log == null)
                {
                    _log = LoggingFactory.GetLogger(typeof(ServiceStatusController).FullName);
                }
                return _log;
            }
        }


```

This factory looks reads from the header for the loglevel..   The factory creates a new NLog.Logger instance and uses that. And then I write a log like this, from the api method..

```
Logger.LogInfo("Log Test - Status Entry Information Message");

```
And is implemented like this..

```
public void LogInfo(string message)
        {
            if (this.LogLevel.HasFlag(LogLevel.Info))
            {
                Logger.Info(JsonConvert.SerializeObject(ErrMessage));
                
            }
        }

```

Logger is an instance of NLogger.Logger

It's very straightforward.  The problem is during the UseNLog extension method implementation, it makes a call to an internal class ServiceLocator.. And then that gets used to get the httpContext on the layout providers I mentioned above..

**Comment by timdoke** [comment]
If this class could be made public static, instead of internal static, I could work with it..

https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore/DependencyInjection/ServiceLocator.cs

**Comment by timdoke** [comment]
@snakefoot I saw your comment from here, https://github.com/NLog/NLog.Web/issues/264#issuecomment-379476155; it turns out that this was the core issue (when I turned on the internal debug flag).. Do you think that upgrading Nlog.Extensions.Logging to 1.0.1 will fix this issue?

**Comment by snakefoot** [comment]
@timdoke Not sure I understand this issue. Besides that you get duplicate logging.

NLog.Extensions.Logging ver. 1.0.1 improves the automatic assembly loading to make callsite logic work better (and also pre-register aspnetcore-layoutrenderers).

The important part in aspnetcore is to follow the [wiki](https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2) and use this line for loading the nlog.config:

`var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();`

**Comment by timdoke** [comment]
@snakefoot  I don't have my source code in front of me.. But, I remember the issue was if I didn't add .AddNLog during the initialization, several layout providers would fail because they didn't have access to the IServiceProvider instance (ServiceLocator.ServiceProvider).  I have a custom logging implementation provided above.  If I did add .AddNLog, I get duplicate logs.  When I installed NLog a few days ago, I would have gotten everything most current.  So, if for some reason the extension you provided above wasn't installed by default, I could try adding it.  

I did add the ConfigureNLog code you had in your comment.  During .AddNLog, it sets a reference to that IServiceProvider (shown below)..

I see this code, from this file: https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore/AspNetExtensions.cs

```
 services.AddSingleton<ILoggerProvider>(serviceProvider =>

                {

                    ServiceLocator.ServiceProvider = serviceProvider;

                    return new NLogLoggerProvider(options);

                });

```

That serviceProvider being set is what's missing..

**Comment by snakefoot** [comment]
@timdoke Created PR  #273 with new method `SetupNLogServiceLocator`

**Comment by timdoke** [comment]
@snakefoot  perfect, thanks a lot!

**Comment by 304NotModified** [comment]
Publishing now :)

**Comment by timdoke** [comment]
It works perfectly.. Thanks a lot @304NotModified and @snakefoot.
