### ISSUE TITLE
HttpContextAccessor.HttpContext is null in second target in FallBackgroup when extending AspNetLayoutRendererBase

### ISSUE THREAD

**Issue by neothor** [NLog/NLog.Web#271]
I have extended the AspNetLayoutRendererBase to create a custom layout renderer which uses the HttpContext. The layoutrenderer does it work perfectly when I only use one filetarget. But when I introduce a fallback group, for example writing to network and than to file, the second target has no more HttpContext.

```c#
protected override void DoAppend(StringBuilder builder, LogEventInfo logEvent) 
{
        HttpRequestBase request = HttpContextAccessor.HttpContext?.Request;

        if (request == null)
        {
            return;
        }

        var options = new Func<string>[]
        {
            () => request.Headers["True-Client-IP"],
            () => request.Headers["X-Forwarded-For"],
            () => request.ServerVariables["REMOTE_ADDR"]
        };

        foreach (var option in options)
        {
            var ip = option();
            if (string.IsNullOrEmpty(ip))
            {
                continue;
            }

            builder.Append(ip);
            return;
        }
}
```

```xml
<target xsi:type="FallbackGroup" name="mainlog" returnToFirstOnSuccess="true">
        <target xsi:type="Network" name="elklog" address="tcp://127.0.0.1:8000" newLine="true">
          <layout xsi:type="JsonLayout">
            <attribute name="ip" layout="${blp-request-ip}" />
          </layout>
        </target>
        <target xsi:type="File" name="filelog" filename="${basedir}\Logs\log.current.json" archiveFileName="${basedir}\Logs\log.{#}.json" archiveEvery="Day" archiveNumbering="Date" archiveDateFormat="yyyyMMdd">
          <layout xsi:type="JsonLayout">
            <attribute name="ip" layout="${blp-request-ip}" />
          </layout>
        </target>
    </target>
```

Looking at some search results it has probably something to to with that every target is executed in a new thread that than has no knowlegde of the HttpContext.

**Comment by 304NotModified** [comment]
Is this ASP.NET or ASP.NET Core?

**Comment by snakefoot** [comment]
> Looking at some search results it has probably something to to with that every target is executed in a new thread that than has no knowlegde of the HttpContext.

Very good diagnose, that you have made. The problem is that the fallback occurs when the exception occurs, but it happens on an async thread.

The FallbackGroup wrapper should call PrecalculateVolatileLayouts on the fallbacktargets, when the the initial target doesn't complete right away, so it has been prepared. You should register this as a [bug](https://github.com/NLog/NLog/issues/new)

**Comment by snakefoot** [comment]
Resolved by https://github.com/NLog/NLog/pull/2644

@neothor Please upgrade to NLog 4.5.2 and see if your problem is fixed.

**Comment by neothor** [comment]
Quick response guys. I have updated to 4.5.2 and I have information in the fallback target from the HttpContext. Great work

**Comment by 304NotModified** [comment]
Thanks for the feedback!

**Comment by 304NotModified** [comment]
And thanks to @snakefoot  for the fix :)
