### ISSUE TITLE
${aspnet-request-ip} has not been updated to use TryGetRequest

### ISSUE THREAD

**Issue by ytzhakov** [NLog/NLog.Web#274]
As a result, it still throws an HttpException with the message: "Request is not available in this context"
Please change it to use TryGetRequest in order to avoid this exception.

**Comment by 304NotModified** [comment]
Could you please create a PR?

Thanks!

**Comment by 304NotModified** [comment]
I have time to look at this, so will try to fix this

**Comment by ytzhakov** [comment]
Hi. I'm not really familiar with github.
You can instruct me of how to create the PR if you want, or I can send you
the specific line of code where it should be corrected. whichever works for
you.
thanks!

**Comment by 304NotModified** [comment]
This is ASP.NET and not ASP.NET Core, isn't?

**Comment by 304NotModified** [comment]
I've made already a PR :)

**Comment by ytzhakov** [comment]
Wow you are quick.
It is ASP.NET, not Core.

**Comment by 304NotModified** [comment]
It's now publishing.

**Comment by 304NotModified** [comment]
It's online! https://www.nuget.org/packages/NLog.Web/4.5.3

**Comment by ytzhakov** [comment]
this was the fastest issue solving/publishing that I had ever witnessed.
Thanks!
