### ISSUE TITLE
HttpContextAccessor is null 

### ISSUE THREAD

**Issue by Kiwi15** [NLog/NLog.Web#279]
Hello, 

I want to use the extensions of Nlog to get the id of the user on the HttpContextAccessor.
This accessor is always null on my NLogExtensions class but in my controller it has some value.
So all the layout who use this are null like ${aspnet-User-Identity}.
How it's possible ? Thanks
PS: I'm using Asp net Core 2 

```
[LayoutRenderer("user")]
    public class Nlog : AspNetLayoutRendererBase
    {
        protected override void Append(StringBuilder builder, LogEventInfo logEvent)
        {
            if (HttpContextAccessor?.HttpContext == null)
                return;

            DoAppend(builder, logEvent);
        }

        protected override void DoAppend(StringBuilder builder, LogEventInfo logEvent)
        {
            var httpRequest = HttpContextAccessor?.HttpContext;
            string user = null;
            if (httpRequest.User.FindFirst(ClaimTypes.NameIdentifier) != null)
            {
                user = httpRequest.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            }

            builder.Append(user);
        }
    }
```

**Comment by snakefoot** [comment]
@Kiwi15 Have you followed the [Wiki](https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2#4-update-programcs) about using following call to load `nlog.config` (Notice NLogBuilder)

`var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();`

**Comment by Kiwi15** [comment]
Yes, i have followed the tutorial but nothing work in my project.
I use an extension of ExceptionFilterAttribute in which i pass my logger ( private readonly ILogger _logger;) 

In my ConfigureServices on Startup.cs

```
{
            services.AddScoped<ApiExceptionFilterAttribute>();
            LoggerFactory loggerFactory = ConfigureLogging();
            services.AddSingleton<ILoggerFactory>(loggerFactory);
            

            services.AddMvc(options =>
            {
                options.Filters.Add(new ApiExceptionFilterAttribute(loggerFactory.CreateLogger<ApiExceptionFilterAttribute>()));
            })
            .AddXmlSerializerFormatters();
}

        private LoggerFactory ConfigureLogging()
        { 
            LayoutRenderer.Register<Nlog>("user");

            var loggerFactory = new LoggerFactory();
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            loggerFactory.AddNLog();

            return loggerFactory;
        }

```

 ```
public class ApiExceptionFilterAttribute : ExceptionFilterAttribute
    {
        public ApiExceptionFilterAttribute(ILogger<ApiExceptionFilterAttribute> logger)
            : base(logger)
        {

        }

        protected override void RegisterExceptionConfigurations()
        {
            RegisterWarning<EntityAlreadyExistsException>(HttpStatusCode.Conflict);
            RegisterWarning<InvalidOperationException>(HttpStatusCode.NotFound, exportMessage: false);
        }
    }
```

**Comment by 304NotModified** [comment]
What are the version of NLog.Web.AspNetCore, NLog and NLog.Extensions.Logging that you're using?

**Comment by Kiwi15** [comment]
NLog.Web.AspNetCore : 4.5.2 
NLog: 4.5.2 
NLog.Extensions.Logging: 1.0.1

**Comment by snakefoot** [comment]
Cannot see the code that displays that you have loaded the nlog.config correctly.

But you need to register any custom layout renders before you load the nlog.config. Looks like you are doing it after (Else you need to reload the config again)



Sent from my Samsung device


-------- Original message --------

**Comment by Kiwi15** [comment]
I have loaded my nlog.config in the startup like that.
`env.ConfigureNLog("nlog.config");`
Is it the same that NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger(); ?

**Comment by snakefoot** [comment]
Wiki states that you need to call UseNLog in Asp.Net.Core ver. 2.Please follow the Wiki


Sent from my Samsung device


-------- Original message --------

**Comment by Kiwi15** [comment]
I call UseNLog in the Program.cs
```
 public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
.UseNLog()
                .Build();
    }
```

**Comment by snakefoot** [comment]
And call LayoutRenderer.Register before ConfigureNLog? If so then you probably have to activate the NLog internal logger



Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
bump @Kiwi15
