### ISSUE TITLE
Should NLog fully replace Microsoft Logger in Core 2.0

### ISSUE THREAD

**Issue by alexandrejobin** [NLog/NLog.Web#280]
I was playing with ASPNet Core 2.0 and NLog this week and faced the problem that even if nlog is configured to log everything (trace, debug, etc), nlog will only receive what is configured with Microsoft Logger. By default, Microsoft logger only send messages with level Information and up. It's seems to have confused a lot of people here (#167, #171, #128, #175, #166, #234, #238, etc).

Is there any talks about replacing the Microsoft Logger entirely with nlog instead of putting nlog behind it? Serilog is replacing the Microsoft Logger completly and it seems more natural in my opinion. Otherwise, it is like saying that nlog is a provider for Microsoft Logger but you need to configure 2 frameworks to make it work correctly so it might be confusing.

So instead of the actuel implementation flow where the LoggerInformation is responsable of dispatching the log by following his own rules and then follow the nlog rules:

`Microsoft.Extensions.Logging.Logger -> Microsoft.Extensions.Logging.LoggerInformation -> NLog.Extensions.Logging.NLogLogger`

nlog would be fully responsable of what he is doing with this flow :

`Microsoft.Extensions.Logging.Logger -> NLog.Extensions.Logging.NLogLogger`

So you need to choose between Microsoft Logger OR NLog but not both. Any thoughts?

**Comment by 304NotModified** [comment]
> Is there any talks about replacing the Microsoft Logger entirely with nlog instead of putting nlog behind it? Serilog is replacing the Microsoft Logger completly and it seems more natural in my opinion

yes, but there are downsides also. Replacing = create custom factory, and that is: https://github.com/NLog/NLog.Web/issues/235

**Comment by 304NotModified** [comment]
maybe continue on #235 and close this one, OK?

**Comment by alexandrejobin** [comment]
alright!
