### ISSUE TITLE
Override NLog configuration, when called from integration test.

### ISSUE THREAD

**Issue by greenmooseSE** [NLog/NLog.Web#289]
**Type**: Question
**NLog.Web.AspNetCore version**:  4.5.4
**Platform**: . .NET Core 2 

I am trying to combine what's on [wiki](https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2) with an [integration test](https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing?view=aspnetcore-2.0) i.e.
```
 _server = new TestServer(new WebHostBuilder()
            .UseStartup<Startup>());
 _client = _server.CreateClient();
```
Now, since the wiki wires up the logging in Program.cs, and that is not invoked when using above integration test, I cannot intercept my API logging from my test.

Is there a recommended way of how to go about it?
In aspNetCore 1 I would have a custom starutp class in the test library, override the logging configuration in it and then logging will be done towards the test library's logger. 
In aspNetCore 2 I don't see a good way of handling it since logging is configured in Program.Main.

Thanks.

(To complicate things further I want 1 IServiceCollection instance for the test environment and 1 IServiceCollection for the api I am testing, so I can keep services I use for test vs production separated in 2 containers, but I think that is out of scope for this particular problem).

**Comment by snakefoot** [comment]
Not that experienced with AspNetCore and UnitTests, but maybe this can help:

https://github.com/NLog/NLog.Web/blob/79e273b94ae189c85b1a64b4346b65d598f61446/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs#L127-L138

**Comment by greenmooseSE** [comment]
Thanks, not sure how to adapt that in my tests but I got the logging itself working by by invoking Program.Main from the test (and customize behavior in Main a bit so it can be invoked by test).

Although that leads me to the next issue; I have only 1 log configuration shared between both app/api being tested and test itself.

Is it possible to have NLog log to "isolated" targets with respect to their IServiceProvider instances? I can illustrate my problem with below test.
Thanks
```csharp
using System;

namespace MiscTests.WithoutTestSuite
{
    using System.Linq;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Logging;
    using NLog.Config;
    using NLog.Extensions.Logging;
    using NLog.Layouts;
    using NLog.Targets;
    using NUnit.Framework;
    using WebApi;

    [TestFixture]
    internal class MultipleNLogConfigsTest
    {
        #region Public members

        [Test]
        public void CanHaveMultipleLoggingProviders()
        {
            var services1 = new ServiceCollection();
            services1.AddSingleton<ILoggerFactory, LoggerFactory>();
            var services2 = new ServiceCollection();
            services2.AddSingleton<ILoggerFactory, LoggerFactory>();
            services1.AddLogging(builder => builder.SetMinimumLevel(LogLevel.Trace));
            services2.AddLogging(builder => builder.SetMinimumLevel(LogLevel.Trace));


            ServiceProvider provider1 = services1.BuildServiceProvider();
            ServiceProvider provider2 = services1.BuildServiceProvider();

            var logFactory1 = provider1.GetRequiredService<ILoggerFactory>();
            var logFactory2 = provider2.GetRequiredService<ILoggerFactory>();

            logFactory1.AddNLog(new NLogProviderOptions
            {
                CaptureMessageTemplates = true,
                CaptureMessageProperties = true
            });
            logFactory2.AddNLog(new NLogProviderOptions
            {
                CaptureMessageTemplates = true,
                CaptureMessageProperties = true
            });

            var logger1 = provider1.GetRequiredService<ILogger<MultipleNLogConfigsTest>>();
            var logger2 = provider2.GetRequiredService<ILogger<MultipleNLogConfigsTest>>();


            //What to do with the 2 configurations?
            LoggingConfiguration config1 = LogConfigurer.zCreateNLogConfiguration("Services1");
            LoggingConfiguration config2 = LogConfigurer.zCreateNLogConfiguration("Services2");

            //How can I log to the 2 different providers?
            logger1.LogInformation("From container1!");
            logger2.LogInformation("From container2!");
        }

        #endregion

        #region Private members

        private static MemoryTarget zhCreateMemoryTarget(LoggingConfiguration config, string name,
            string layout)
        {
            //We need to set name in ctor otherwise it will not appear in Configuration.AllTargets
            var memoryTarget = new MemoryTarget("memoryTarget");
            memoryTarget.Layout = new SimpleLayout(layout);
            config.AddTarget(memoryTarget);
            var memoryTargetRule = new LoggingRule("*", NLog.LogLevel.Debug, memoryTarget);
            config.LoggingRules.Add(memoryTargetRule);
            return memoryTarget;
        }

        private static LoggingConfiguration zhCreateNLogConfiguration(string logPrefix)
        {
            var config = new LoggingConfiguration();

            //Console target
            {
                var consoleTarget = new ConsoleTarget("consoleTarget");
                consoleTarget.Layout = new SimpleLayout(
                    $"[{logPrefix}]" +
                    " ${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}");
                config.AddTarget(consoleTarget);
                var consoleTargetRule = new LoggingRule("*", NLog.LogLevel.Debug, consoleTarget);
                config.LoggingRules.Add(consoleTargetRule);
            }

            //Memory target
            {
                zhCreateMemoryTarget(config, "memoryTarget",
                    $"[{logPrefix}]" +
                    " ${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}");
            }


            return config;
        }

        #endregion
    }
}

```

**Comment by 304NotModified** [comment]
Even in .NET Core, you could set NLog.Configuration = ..

If you really need 2 logger configuration at the same time, then you should use advanced tricks of the DI. (e.g. in Autofac you could register a lambda)

**Comment by greenmooseSE** [comment]
> Even in .NET Core, you could set NLog.Configuration = ..

Yeah but I have 2 ```IServiceProvider``` instances (1 for test and 1 for app) I want to configure with 2 different log configurations.

> If you really need 2 logger configuration at the same time, then you should use advanced tricks of the DI.

Hrm but how do I go about do to that, AFAICT the NLogLoggerProvider relies on the static LogManager members resolve loggers?
![image](https://user-images.githubusercontent.com/31244330/46130084-a959ec80-c238-11e8-8eca-613437200715.png)

**Comment by snakefoot** [comment]
See also https://github.com/NLog/NLog.Extensions.Logging/issues/252 and https://github.com/NLog/NLog.Extensions.Logging/pull/248

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
