### ISSUE TITLE
Features from NLog AssemblyVersionLayoutRenderer

### ISSUE THREAD

**Issue by alexangas** [NLog/NLog.Web#293]
**Type**: Bug (unexpected behaviour)

**NLog version**: 4.5.6

**NLog.Web/NLog.Web.AspNetCore version**: 4.5.4

**NLog.Extensions.Logging version**: N/A

**Platform**: .NET Core 2 

**Current NLog config**: N/A

I implemented nlog/nlog#2480 expecting to be able to use the features added in an ASP.NET Core 2.0 application. After the official release came out, I noticed it didn't appear to be working correctly but only recently had time to investigate. After many hours I found that it is being overridden by the AssemblyVersionLayoutRenderer in this project. So documentation bug - this needs to be clear in the README! 😅 

However the more important question! Is it possible to address this override instead to either:

1. Inherit from the NLog AssemblyVersionLayoutRenderer, so that these features can be picked up. As part of the aforementioned work I split out the methods so it shouldn't take much work to be able to inherit from it (but would require minor code changes).

2. Move the logic for retrieving the assembly from HTTP context into NLog and remove from this project altogether so it is only in one place?

I'm happy to work on this.

**Comment by 304NotModified** [comment]
this AssemblyVersionLayoutRenderer should overwrite the one in NLog.dll. It's a bit strange if that won't work. Do you have a `<extensions>` in your config file?

**Comment by alexangas** [comment]
Hello! Yes this is exactly what happens, and why I raise this issue. :smile: Please re-read the original post, perhaps I was not clear.

**Comment by alexangas** [comment]
After reviewing the code, decided to take option 3 - copy from NLog. Maybe for ASP.NET it makes sense just to do this, although I think there is a code maintenance issue here. Not sure how this should be addressed properly.

**Comment by 304NotModified** [comment]
> Hello! Yes this is exactly what happens, and why I raise this issue

Oops sorry, missed that. 

> After reviewing the code, decided to take option 3 - copy from NLog.

I prefer option 1 (inherit),  is that still possible or is a good reason to pick option 3?

**Comment by alexangas** [comment]
I ended up choosing Option 3 because the Option 1 approach hadn't been done for any other renderer thus far. It also introduces a source/binary dependency on the AssemblyVersionLayoutRenderer class in NLog, and requires a change there to make at least one of the methods `virtual`.

The benefit is, I can ensure almost all of the logic exists in NLog, except for the ASP.NET non-core specifics of getting the entry assembly from HttpContext.

So if that tradeoff is acceptable, i'm happy to switch the approach over to Option 1. Please let me know!

(By the way, is there a Gitter or Slack chat for this project to help with discussion-type topics?)

**Comment by 304NotModified** [comment]
> So if that tradeoff is acceptable, i'm happy to switch the approach over to Option 1. Please let me know!

I really prefer option 1, even when making methods virtual. If we then add some things to the original layout renderer, it will be also available here. 



> (By the way, is there a Gitter or Slack chat for this project to help with discussion-type topics?)

There was a Gitter, but unfortunately it wasn't very active and took more time that was available for me.
