### ISSUE TITLE
aspnet-request-cookie Value Only

### ISSUE THREAD

**Issue by alexangas** [NLog/NLog.Web#294]
**Type**: Bug (documentation) / Feature Request

**NLog version**: 4.5.6

**NLog.Web/NLog.Web.AspNetCore version**: 4.5.4

**NLog.Extensions.Logging version**: N/A

**Platform**: ASP.NET Core 2.0

**Current NLog config**:

```
layout="${aspnet-request-cookie:CookieNames=TestCookie}"
```

In case of a BUG:

- What is the current result?
Will print
```
TestCookie=TheCookieValue
```

- What is the expected result?
As per [documentation](https://github.com/NLog/NLog/wiki/AspNetRequest-Cookie-Layout-Renderer), value of the cookie *not including its name* written to the log.
```
TheCookieValue
```

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? No, not an error.

- Please post full exception details (message, stacktrace, inner exceptions): N/A

- Are there any workarounds? No

- Is there a version in which it did work? Don't Know

- Can you help us by writing an unit test? Absolutely

In case of a FEATURE REQUEST:
 
If this is a feature that should be added, perhaps as a flag like `ValueOnly`...

- Why do we need it?
Our logs are parsed and having the key/value pair syntax causes a problem for this. We need the value only if possible.

I'm happy to add this feature if that is OK.

**Comment by 304NotModified** [comment]
> I'm happy to add this feature if that is OK.

👍 I propose a new option to the layout renderer. Please add some unit tests if possible.
