### ISSUE TITLE
System.ArgumentOutOfRangeException in Chinese Path

### ISSUE THREAD

**Issue by syy110112** [NLog/NLog.Web#298]
I found when i create a project with Chinese path,the NLog initialize 
will error
`var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();`
Length cannot be less than zero
and i used Mac for .net core 2.0

**Comment by snakefoot** [comment]
Duplicate of #237 ? (Try upgrading to the recently released NetCore 2.1)

**Comment by 304NotModified** [comment]
I think this is also #237. Please try to upgrade to .NET Core 2.1.

If that won't resolve your problem, please let us know!

**Comment by syy110112** [comment]
it was only released 2.1v yesterday in China，when i upgrade to 2.1v ,it will be ok.
thank you！
