### ISSUE TITLE
Is Asp net core 2.1 supported? The documentation is unclear

### ISSUE THREAD

**Issue by SamuelWr** [NLog/NLog.Web#300]
Ten days ago the following line was added to the quickstart guide for Asp net core:

ℹ️ Do not work on ASP.CORE 2.1

This is the only reference i can find to NLog not working in 2.1, was it added in error?

**Comment by nholling** [comment]
Would be great to know why too.

**Comment by iamkarlson** [comment]
We probably have to invite @atrodriguez88 to that discussion.

**Comment by snakefoot** [comment]
I had no trouble using NLog with AspNetCore 2.1:

https://github.com/NLog/NLog/issues/2789#issuecomment-400821387

Though I had to add settings to force use of NetCore 2.1

**Comment by snakefoot** [comment]
Think the problem is that with AspNetCore2, then it looks like this:

```c#
public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .ConfigureLogging(logging =>
        {
            logging.ClearProviders();
            logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
        })
        .UseNLog()  // NLog: setup NLog for Dependency injection
        .Build();
```

With AspNetCore21, then it should look like this:

```c#
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureLogging(logging =>
                {
                    logging.ClearProviders();
                    logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
                })
                .UseNLog();
```

So the copy-paste of the guide needs to be updated, to match Microsofts latests recommendations. See also **Migrating an ASP.NET Core 2.0.x project to 2.1.0** here: https://blogs.msdn.microsoft.com/webdev/2018/04/12/asp-net-core-2-1-0-preview2-now-available/

**Comment by dyardyGIT** [comment]
Not sure why yet, but while implementing nlog with asp.net core 2.1 visual studio locks up and I have to kill the process and restart vs.net.

**Comment by snakefoot** [comment]
@dyardyGIT Sounds like a different problem. Visual Studio is usually super helpful, but can turn into a horrible monster that gnaws your hand off.

You can try and make a fulldump of the stalled application, and then debug the memory dump with visual studio :) (Done that myself to fix broken VS-extensions and friends). But this is a NLog support forum, not random chatter.

**Comment by 304NotModified** [comment]
To be clear, ASP.NET CORE 2.1 is supported.

This line was added by @atrodriguez88 and it looks like abuse. 👎 

I will revert it and consider blocking @atrodriguez88.
