### ISSUE TITLE
Port AspNetBufferingWrapper to ASP.NET Core

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#304]
From https://github.com/NLog/NLog/issues/2806

Port to middleware. 

Current docs: https://github.com/nlog/nlog/wiki/AspNetBufferingWrapper-target

**Comment by Baklap4** [comment]
Any progress to this?

**Comment by 304NotModified** [comment]
Nope. This isn't started. Do you need it?

**Comment by 304NotModified** [comment]
Feel free to create a PR 👍

**Comment by 304NotModified** [comment]
https://docs.microsoft.com/en-us/aspnet/core/migration/http-modules?view=aspnetcore-2.2

**Comment by milton-ballon-incontact** [comment]
+1

**Comment by antonio-schlappa-incontact** [comment]
+1

**Comment by marcos-bustos-nice** [comment]
+1

**Comment by pablo-daza-incontact** [comment]
+1

**Comment by david-pierola-incontact** [comment]
+1

**Comment by ferd-altamirano** [comment]
+1

**Comment by 304NotModified** [comment]
Please use the thumbs up in the start post. Thanks!

**Comment by muchachopolo** [comment]
+ 1

**Comment by jenunez** [comment]
+1

**Comment by jdpapiero** [comment]
+1

**Comment by 304NotModified** [comment]
Sending a +1 message (and notification) every minute won't help in implementing this...

**Comment by 304NotModified** [comment]
Guess this should be followed for implementing this: https://docs.microsoft.com/en-us/aspnet/core/migration/http-modules?view=aspnetcore-5.0

Source code of the current wrapper: https://github.com/NLog/NLog.Web/blob/master/src/NLog.Web/Targets/Wrappers/AspNetBufferingTargetWrapper.cs

**Comment by 304NotModified** [comment]
@jdpapiero @jenunez @david-pierola-incontact @muchachopolo @ferd-altamirano @marcos-bustos-nice @antonio-schlappa-incontact @milton-ballon-incontact

If I create middleware for this, so this will work in ASP.NET Core, could one of you test it? I will create a pre-release package then.

**Comment by milton-ballon-incontact** [comment]
Sure. I will.

**Comment by miltonballon** [comment]
Sure. I will. @304NotModified

**Comment by bakgerman** [comment]
I submitted a PR for review for this

**Comment by snakefoot** [comment]
Pre-Release from #816 is available here:

https://ci.appveyor.com/project/nlog/nlog-web/builds/44192166/artifacts

**Comment by snakefoot** [comment]
Pre-Release from #816 is available here:

https://ci.appveyor.com/project/nlog/nlog-web/builds/44350768/artifacts

If people want to help test/verify/review the direction. The following middleware must be enabled:
```csharp
 app.UseMiddleware<NLog.Web.NLogBufferingTargetWrapperMiddleware>();
```

@jdpapiero @jenunez @david-pierola-incontact @muchachopolo @ferd-altamirano @marcos-bustos-nice @antonio-schlappa-incontact @milton-ballon-incontact @Baklap4 @justhoma

**Comment by bakgerman** [comment]
Thank you snakefoot for the pull request to close this issue.

**Comment by snakefoot** [comment]
https://www.nuget.org/packages/NLog.Web.AspNetCore v5.2.1 has been released with support for `AspNetBufferingWrapper` on ASP.NET Core via `NLogBufferingTargetWrapperMiddleware`.

- https://github.com/NLog/NLog/wiki/AspNetBufferingWrapper-target
