### ISSUE TITLE
how to config log path in docker?

### ISSUE THREAD

**Issue by kongkong56** [NLog/NLog.Web#311]
how to config log path in docker?

**Comment by 304NotModified** [comment]
please fill in the template

**Comment by kongkong56** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    autoReload="true"
    throwExceptions="false"
    internalLogLevel="Off"
    internalLogFile="..\logs\nlog-internal.log">

  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>
    
    <target xsi:type="File" name="all-file" fileName="..\logs\${shortdate}-all.log"
            layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}" />

    
    <target xsi:type="File" name="app-file" fileName="..\logs\${shortdate}-app.log"
            layout="${longdate}|${event-properties:item=EventId_Id:whenEmpty=0}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}" />
  </targets>
  <rules>
       <logger name="*" minlevel="Trace" writeTo="all-file" />
    <logger name="Microsoft.*" maxLevel="Info" final="true" />
    <logger name="*" minlevel="Trace" writeTo="app-file" />
  </rules>
</nlog>

**Comment by 304NotModified** [comment]
This is too unclear. We cannot help I you refuse to give the needed info.
