### ISSUE TITLE
Include nlog.web.aspnetcore for ${configsetting}

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#316]
Add here:

- https://nlog-project.org/config/?tab=layout-renderers&search=configsetting
and here:
- https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer

**Comment by 304NotModified** [comment]
done

**Comment by boboyunduoer** [comment]
"ConfigSetting Layout Renderer" could not be founded in NLog.Web.AspNetCore 4.7, could you check again?

**Comment by snakefoot** [comment]
For those being confused: https://github.com/NLog/NLog.Extensions.Logging/issues/250

**Comment by snakefoot** [comment]
Updated the Wiki with NLog.Web.AspNetCore ver. 4.8.0: https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer
