### ISSUE TITLE
docs ${aspnet-request-form}

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#319]
- [x] wiki
- [x] https://github.com/NLog/NLog.github.io/blob/master/config/layout-renderers.json

See #313

**Comment by snakefoot** [comment]
See also https://github.com/NLog/NLog/wiki/AspNetRequest-Form-Layout-Renderer
See also https://github.com/DrewBrasher/NLog.github.io/commit/1aab227888d90d29644b6f42f9de76eaa4cd3f1d

**Comment by 304NotModified** [comment]
Thanks @snakefoot !
