### ISSUE TITLE
Add an option in AspNetRequestIpLayoutRenderer to check for X-Forwarded-For header

### ISSUE THREAD

**Issue by Giorgi** [NLog/NLog.Web#324]
**Type** (choose one):

- Feature request

Add an option in AspNetRequestIpLayoutRenderer to check for X-Forwarded-For header. This is needed because if the server is behind a proxy the real client ip address value is in this header.

**Comment by snakefoot** [comment]
@Giorgi PullRequests are always welcome

**Comment by 304NotModified** [comment]
closed by #325 -  thanks!

**Comment by 304NotModified** [comment]
@Giorgi thanks for the reminder, working now on it! #332

**Comment by 304NotModified** [comment]
build broken :(  some config issue I think.

**Comment by 304NotModified** [comment]
@Giorgi  publishing now! (thanks to @snakefoot !)

**Comment by 304NotModified** [comment]
online now :)
