### ISSUE TITLE
Add a layout renderer for correlation ID

### ISSUE THREAD

**Issue by Giorgi** [NLog/NLog.Web#328]
**Type** (choose one):

In case of a FEATURE REQUEST:
 
 - Asp.net Web Api allows to assign unique id to every request by calling [HttpRequestMessageExtensions.GetCorrelationId Method](https://docs.microsoft.com/en-us/previous-versions/aspnet/mt174862(v=vs.118)) The correlation Id is useful for tracing, diagnostics, etc so it will be helpful to have a renderer for it.

Should I send a PR ?

**Comment by snakefoot** [comment]
There is already something called `${aspnet-traceidentifier}` coming from `HttpContext.TraceIdentifier`:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.traceidentifier?view=aspnetcore-2.1

**Comment by Giorgi** [comment]
`${aspnet-traceidentifier}` is only in NLog.Web.AspNetCore not in NLog.Web.AspNetCore

**Comment by Giorgi** [comment]
What if I implement ${aspnet-traceidentifier} so that it uses `HttpRequestMessageExtensions.GetCorrelationId` on full Framework?

**Comment by 304NotModified** [comment]
is this for full .net or .net core?

**Comment by snakefoot** [comment]
Must admit my skills in ASP.NET MVC + Core are weak. So I have a hard time knowing how to lookup the different ids:

- The unique requestid from the client
- The unique traceid on the server when handling the request (connects all logging for one request)
- The unique correlationid that connects the requestid and traceid together (connects all logging across multiple requests)

See also here https://github.com/aspnet/Hosting/pull/1394

**Comment by Giorgi** [comment]
@304NotModified This is for full .net

**Comment by 304NotModified** [comment]
OK,

if we don't need more dependencies, then NLog package is OK for this. 

If not, then we need a NLog.WebApi or something like that. I have to admit I don't have much time to setup a new package (and unfortunately it always takes more time then it should be)

**Comment by Giorgi** [comment]
@304NotModified so do you agree with implementing `${aspnet-traceidentifier}` in full .Net using HttpRequestMessageExtensions.GetCorrelationId or do you prefer creating a new layout renderer?

**Comment by Giorgi** [comment]
@304NotModified Looks like we will need dependency on Microsoft.AspNet.WebApi.Core nuget package

**Comment by 304NotModified** [comment]
OK, then the layout renderer could be `${webapi-traceidentifier}` ;)

**Comment by Giorgi** [comment]
Yes, but we will need a new project in the solution and new nuget package so that we don't introduce new dependency for NLog.web users

**Comment by snakefoot** [comment]
The specification of ´GetCorrelationId` :

> Retrieves the Guid which has been assigned as the correlation ID associated with the given request. The value will be created and set the first time this method is called.

So it sounds like the `traceidentifier`. The source-code is this:

https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Web.Http/HttpRequestMessageExtensions.cs#L759

Where it attempts 3 lookups:

1) Lookup of `HttpPropertyKeys.RequestCorrelationKey`  from HttpRequestMessage.Properties
2) Fallback lookup of `Trace.CorrelationManager.ActivityId` (Unless equals Guid.Empty)
3) Fallback lookup of Guid.NewGuid();

If fallback is required then the fallback Guid is stored using `HttpPropertyKeys.RequestCorrelationKey`.

Because there is no HttpRequestMessage (and building one from HttpContextBase will have a huge overhead and will not be the same). Then I suggest the following:

https://github.com/NLog/NLog/wiki/Trace-Activity-Id-Layout-Renderer

**Comment by Giorgi** [comment]
Yes, I currently use ${activityid} as a workaround to log correlation id

**Comment by snakefoot** [comment]
@Giorgi I'm curious if GetCorrelationId works when used from HttpRequestBase. I have my doubts.

**Comment by Giorgi** [comment]
`GetCorrelationId` accepts an HttpRequestMessage object. How can it work for HttpRequestBase? I check and in Asp.Net web api you can access HttpRequestMessage instance by calling `HTTPContext.Current.Items["MS_HttpRequestMessage"]` but we will need to copy code from `GetCorrelationId` to avoid dependency on Microsoft.AspNet.WebApi.Core nuget package

**Comment by snakefoot** [comment]
@Giorgi That lookup will only work if some other code has already injected HttpRequestMessage  into the HttpRequestBase.Items-dictionary. Again not a ASP.NET wizard so maybe HttpRequestBase is always created together with an HttpRequestMessage-object. I know Microsoft loves to execute unnecessary code to help Intel sell more CPUs, but sometimes there are surprises.

**Comment by Giorgi** [comment]
@snakefoot So what do you suggest?

**Comment by snakefoot** [comment]
I just suggested that some investigation should be done. Again not an expert in traceid handling in Asp Net Mvc. Maybe some one else has a good idea? What is wrong with ActivityId?

Sent from my Sony Xperia


---- Giorgi wrote ----


@snakefoot<https://github.com/snakefoot> So what do you suggest?

**Comment by snakefoot** [comment]
@Giorgi Found this random code from the JsNLog-library:

```
        /// <summary>
        /// Creates an ID that is unique hopefully.
        /// 
        /// This method initially tries to use the request id that IIS already uses internally. This allows us to correlate across even more log files.
        /// If this fails, for example if this is not part of a web request, than it uses a random GUID.
        /// 
        /// See
        /// http://blog.tatham.oddie.com.au/2012/02/07/code-request-correlation-in-asp-net/
        /// </summary>
        /// <returns></returns>
        public override string IISRequestId()
        {
            var provider = (IServiceProvider)HttpContext.Current;
            if (provider != null)
            {
                var workerRequest = (HttpWorkerRequest)provider.GetService(typeof(HttpWorkerRequest));
                if (workerRequest != null)
                {
                    Guid requestIdGuid = workerRequest.RequestTraceIdentifier;
                    if (requestIdGuid != Guid.Empty)
                    {
                        return requestIdGuid.ToString();
                    }
                }
            }

            return null;
        }
```

Maybe this can be used to implement `${aspnet-traceidentifier}` for System.Web ?

**Comment by snakefoot** [comment]
@Giorgi Created #330 that might provide what you are looking for.
