### ISSUE TITLE
Memory target performance option "MaxLogsCount" is missing/not supported.

### ISSUE THREAD

**Issue by JMan7777** [NLog/NLog.Web#347]
**Type**:
- Bug/Feature request

**NLog.Web/NLog.Web.AspNetCore version**:
4.8 

**Platform**: 
.NET Core 2 

**Issue Details**:
Memory target performance option "MaxLogsCount" is missing/not supported.
This option was introduced with NLog v4.6. but it is not supported in this NLog.Web.AspNetCore version.

Thx a lot.

**Comment by 304NotModified** [comment]
Have you update NLog to 4.6 (currently RC1)?

**Comment by 304NotModified** [comment]
In your csproj

```xml
<PackageReference Include="NLog.Web.AspNetCore" Version="4.8.0" />
<PackageReference Include="NLog" Version="4.6.0-rc1" />
```

**Comment by JMan7777** [comment]
Hello,

Thx. 
Upgrading to "NLog" Version="4.6.0-rc1" solved the issue. 
Originally I didn't install the "NLog" as I was thinking (based on the version number)
that the "NLog.Web.AspNetCore" already included a higher NLog version.

Issue can be closed.

**Comment by 304NotModified** [comment]
👍
