### ISSUE TITLE
NLog layout renderer for ASP.NET Core HTTP response

### ISSUE THREAD

**Issue by raymond-holmboe** [NLog/NLog.Web#348]
When looking at the renderers for ASP.NET Core here: https://nlog-project.org/config/?tab=layout-renderers&search=package:nlog.web.aspnetcore
I could not find any renderer for the response, or more specifically, the http response body. Is it something I am missing, if not is it possible to create such a renderer?

**Comment by 304NotModified** [comment]
It's possible with some C# attributes/code, but not sure if that would work with a layout renderer as it could be rendered before the response is built.

Anyway, it's not in NLog.Web/NLog.Web.AspNetCore, a PR would be highly appreciated !

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
