### ISSUE TITLE
.NET Core 3.0 with IHostEnvironment

### ISSUE THREAD

**Issue by jasonycw** [NLog/NLog.Web#350]
In .NET Core 2.X we can use `IHostingEnvironment` to `.ConfigureNLog(...)` which NLog.config file to be used. 
But with .NET Core 3.0, `IHostingEnvironment` will become obsoleted and will become be replaced by `IHostEnvironment` eventually according to https://github.com/aspnet/AspNetCore/issues/7749
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#hostbuilder-replaces-webhostbuilder

Any planing on when will NLog support .NET Core 3.0 ?

**Comment by 304NotModified** [comment]
> But then the door to merge-hell suddenly opens up. And explaining why feature in one branch is not in latest netcore3-branch-preview-release (Happy memories from Nlog 5 forever branch).

True, confusing, but it did work ;)

Anyway, a PR and a PR package (from AppVeyor) sounds the best for me.

**Comment by huanbd** [comment]
Hi, I've got an error when load Nlog.config in my project run on NET Core 3.0, I think it relative to this issue.
`var logger = NLogBuilder.ConfigureNLog("Nlog.config").GetCurrentClassLogger();`
`System.IO.FileNotFoundException: 'Could not load the specified file.'`

So,If it possible, Is there any immediate solution?

**Comment by snakefoot** [comment]
@jasonycw When looking at the NetCore3 sample code from your link, then it shows the use of `IHostBuilder`. 

The `UseNLog` extension method for `IHostBuilder` has been added with this PR #335 (Available with NLog.Web.AspNetCore ver. 4.8.0)

What else is missing to support NetCore3?

**Comment by 304NotModified** [comment]
bump @jasonycw

**Comment by 304NotModified** [comment]
I guess we need to make an extension on IWebHostEnvironment then

For now you could assign LogManager.Configuration with `new XmlLoggingConfiguration(path)`

**Comment by snakefoot** [comment]
@mareklinka Just curious why do you need extension-methods for [IHostEnvironment](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostenvironment)-interface ? 

Why not just use the IHostBuilder as recommended by all [NetCore3 samples](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0#add-providers)?

**Comment by mareklinka** [comment]
I don't think we necessarily *need* the extension method. I was just migrating our existing code base and the project was using the `ConfigureNLog` extension method since its inception (Core 2.0). I will need to rewrite the host buildup anyway for Core 3.0, I might as well rewrite the logging configuration. Thanks for pointing me to the recommended practice.

**Comment by snakefoot** [comment]
@mareklinka Think the correct approach for NLog.Extension.Logging is to obsolete all usage of `ILoggerFactory` and  `IHostingEnvironment` for NetStandard2

**Comment by snakefoot** [comment]
Created https://github.com/NLog/NLog.Web/pull/478 and https://github.com/NLog/NLog.Extensions.Logging/pull/342

**Comment by 304NotModified** [comment]
Fixed by those PRs :)
