### ISSUE TITLE
DNX / ASP 5 - ${aspnet-request:serverVariable result in System.NotSupportedException

### ISSUE THREAD

**Issue by sgutkin** [NLog/NLog.Web#39]
The documentation [https://github.com/NLog/NLog/wiki/AspNetRequest-layout-renderer](url)

implies that serverVariable  works for asp.net5 /coreclr but the source code

[https://github.com/NLog/NLog.Web/blob/master/NLog.Web.ASPNET5/LayoutRenderers/AspNetRequestValueLayoutRenderer.cs](url)

explicitly seems to throw an exception :

`else if (this.ServerVariable != null)`
`    { `
`    #if !DNX `
`        builder.Append(httpRequest.ServerVariables[this.ServerVariable]); `
`    #else `
`        throw new NotSupportedException(); `
`    #endi `

For example in my nlog.config, the first 3 parameters work fine but the last two throw internal nlog exceptions (Warn Exception in layout renderer. Exception: System.NotSupportedException: Specified method is not supported.)

- parameter name="@requestMethod" layout="${aspnet-item:variable=RequestMethod}"/
- parameter name="@responseParamThree" layout="${aspnet-request:header=X-Forwarded-For}"/
- parameter name="@responseParamFour" layout="${aspnet-request:serverVariable=REMOTE_ADDR}"/
- parameter name="@responseParamFive" layout="${aspnet-request:serverVariable=ALL_RAW}"/

From project.json

  "dependencies": {
.....
    "NLog": "4.4.0-beta1",
    "NLog.Config": "4.3.0-beta1",
    "NLog.Extensions.Logging": "1.0.0-rc1-final-2016-03-11",
    "NLog.Schema": "4.3.0-beta1",
    "NLog.Web.ASPNET5": "4.2.1",
.......

**Comment by 304NotModified** [comment]
That's sloppy documentation.  We can't read the server variables in dnx (or AFAIK)

**Comment by sgutkin** [comment]
Yeah I figured as much.   In RC1 the remote IP isn't readily accessible on  Microsoft.AspNet.Http.HttpContext.  I think they plan to fix it for RC2.

**Comment by 304NotModified** [comment]
superseded by https://github.com/NLog/NLog.Web/issues/44
