### ISSUE TITLE
Parellel calls to ConfigureNlog timeout

### ISSUE THREAD

**Issue by blalonde** [NLog/NLog.Web#398]
**Type** (choose one): Bug

**NLog version**: (e.g. 4.2.3) 4.5.11

**NLog.Web/NLog.Web.AspNetCore version**:  NLog.Web.AspNetCore 4.8.1

**NLog.Extensions.Logging version**: 1.4.0

**Platform**:  .NET Core 2 

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogToConsole="false"
      internalLogFile="c:\logs\auditing\internal-nlog.txt">

  <targets>
    <target xsi:type="File"
            name="controller-file"
            fileName="c:\logs\auditing\auditing-${shortdate}.log"
            layout="${longdate} | ${uppercase:${level}} | ${logger} | ${message} | ${exception:format=ShortType,Message,StackTrace:maxInnerExceptionLevel=5} | url: ${aspnet-request-url} | action: ${aspnet-mvc-action}" />
  </targets>

  <rules>
    <logger name="*"
            minlevel="Trace"
            writeTo="controller-file"
            final="true" />
  </rules>
</nlog>


```

In case of a BUG:

- What is the current result?
Takes a really long time to execute

- What is the expected result?
Pretty fast

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes

- Please post full exception details (message, stacktrace, inner exceptions)
2019-04-17 12:27:30.6791 Error Error with flush. Exception: NLog.NLogRuntimeException: Asynchronous exception has occurred. ---> System.TimeoutException: Timeout.
   --- End of inner exception stack trace ---
   at NLog.Common.AsyncHelpers.RunSynchronously(AsynchronousAction action)
   at NLog.LogFactory.Flush(TimeSpan timeout)

- Are there any workarounds? yes/no
not really

- Is there a version in which it did work? 
not that i know of

- Can you help us by writing an unit test?
```csharp
Parallel.For(
	0,
	100,
	i =>
	{
		var client = new TestServer(
				new WebHostBuilder()
					.ConfigureAppConfiguration(
						(context, configBuilder) =>
						{
							var environment = context.HostingEnvironment;
							environment.ConfigureNLog("nlog.config");
						})
					.UseNLog()
					.UseStartup<MyStartup>())
			.CreateClient();
	});
```

I got this issue when trying to execute some integration tests using the WebApplicationFactory pattern described by Microsoft (https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2). Case is, my tests are passing in my real aspnet core web api Program.cs so i get maximum coverage. Since tests are ran in parallel by xunit, they all pass in ConfigureNlog method. Sometimes my tests are really fast but most often than not, they seem to run indefinitely. When I comment out ConfigureNlog it goes really fast. Also it goes fast when I remove my filetarget in nlog.config and this is what I will do for now I think.

Should ConfigureNlog be more robust ?
What is the best way for me to use my real code and nlog.config in my tests ?

**Comment by 304NotModified** [comment]
You need a ConfigureNlog once for an application. So why the parallel? 

Related: https://stackoverflow.com/a/54406989/201303

**Comment by blalonde** [comment]
As I explained, my integration tests use my real Program.cs which ConfiguresNlog and my tests are ran in parallel

**Comment by 304NotModified** [comment]
Yes, that's clear it's used in the test. But IMO the integration tests should be testing a real life scenario, and this isn't like that.

Please note that your setup will change things on the global scope (eg logmanager) and so that isn't a good idea when running in parallel. 

I would recommend to run those tests without parallelism

**Comment by blalonde** [comment]
alright. I think I had similar code using web package 4.4.0 which didn't fail. 
Maybe you should still add some safe guard somehow.

**Comment by snakefoot** [comment]
@blalonde NLog usually has a single global logging configuration. When having multiple threads constantly updating the same global logging configuration, then it will most likely create issues.

If wanting to create multiple `WebHostBuilder` objects, then you should make sure that they each use their own NLog LogFactory:

https://github.com/NLog/NLog.Extensions.Logging/blob/2b9b02164a124ecb383b8fdbfa66db036593c1d1/src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs#L52

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
