### ISSUE TITLE
After deployment, log cannot be written, no exceptions

### ISSUE THREAD

**Issue by amwitx** [NLog/NLog.Web#400]
Development and debugging can be written to the log, but not after deployment. What's the reason? There are no internal exceptions. But use NLog. Web. NLogBuilder. ConfigureNLog ("nlog. config"). GetCurrentClassLogger (); this way can be written

thanks

**Comment by 304NotModified** [comment]
- Please check the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)

**Comment by amwitx** [comment]
2019-04-26 09:48:25.8235 Trace Opening D:\logs\xxxxx\2019-04\nlog-04-26-Debug.log with allowFileSharedWriting=False

It seems that the reason is this.
**AllowFileSharedWriting = False**
But why is Trace, not Warn?
I've set all permissions on everyone, and the problem still exists.

**Comment by amwitx** [comment]
Has been resolved, folder permissions are not normal, thank you.

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
