### ISSUE TITLE
How to turn off Microsoft.AspNetCore.Mvc Logs in AspNetCore 2.2

### ISSUE THREAD

**Issue by chenzhe014** [NLog/NLog.Web#410]
The following is my Logs .

> [2019-05-07 15:55:38.4270][PC-20170829ROEW][Info] 
> Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
> Accept-Encoding:gzip, deflate, br
> Accept-Language:zh-CN,zh;q=0.9
> Connection:close
> Cookie:IsPwdTip=IsPwdTip=1; U573df595-544e-4916-9de8-f43f08bfdbd5=1; Abp.Localization.CultureName=zh-CN; Ub0b00d6f-f612-4b11-86f5-662705e2146b=0; trainFromCity=%E4%B9%89%E4%B9%8C; trainToCity=%E6%9D%AD%E5%B7%9E; flightIndexCooks=%7B%22gocity%22%3A%22%E5%B9%BF%E5%B7%9E%22%2C%22tocity%22%3A%22%E6%98%86%E6%98%8E%22%2C%22godate%22%3A%222019-05-15%22%2C%22interGocity%22%3A%22%22%2C%22intertocity%22%3A%22%22%2C%22intergodate%22%3A%22%22%7D; hotelIndexCooks=%7B%22gocity%22%3A%22%E6%9D%AD%E5%B7%9E%22%2C%22godate%22%3A%222019-05-13%22%2C%22todate%22%3A%222019-05-16%22%7D; trainIndexCooks=%7B%22gocity%22%3A%22%E4%B9%89%E4%B9%8C%22%2C%22tocity%22%3A%22%E6%9D%AD%E5%B7%9E%22%2C%22godate%22%3A%222019-05-07%22%7D; sid=Fe26.2**482a47f9725771375b7ebde16fbab533df89393b7789feddd4768f92582bbf50*UorzjTUok1YRJuwJ75cSWA*P_gafwRj-GeiEeIk-pPOb9B6VIP1iyqqXNbwlAkPZkBLVSi0XZXs6cMlMead6lf9lcqXnf4qEIVCjXCmFYHp1yh99n3plC_MfW7CtdERqWn2DCxM90CGOMrU_5_QV13THZAI7QnqGBZQrO3f1MMrNA**338cc50154dec963051f2ad4c4e0a00f31d584f3245154a0565fc26093c1fbe9*YZsegCbyaee55cBvVvWiIEJPsu4iHUVUtvFnJXgaTD4
> Host:localhost:44323
> User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
> upgrade-insecure-requests:1
> dnt:1
> Request body:
>  
> [2019-05-07 15:55:38.4929][PC-20170829ROEW][Info] Route matched with {action = "Get", controller = "Values"}. Executing action QunarFlight.Web.Controllers.ValuesController.Get (QunarFlight.Web) 
> [2019-05-07 15:55:38.5798][PC-20170829ROEW][Info] Executing action method QunarFlight.Web.Controllers.ValuesController.Get (QunarFlight.Web) - Validation state: Valid 
> [2019-05-07 15:55:38.6066][PC-20170829ROEW][Info] Executed action method QunarFlight.Web.Controllers.ValuesController.Get (QunarFlight.Web), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 22.6363ms. 
> [2019-05-07 15:55:38.6066][PC-20170829ROEW][Info] Executing ObjectResult, writing value of type 'System.String[]'. 

**I want to close all Microsoft default logs( Last four records ), only keep the logs I have recorded( the first one record).**
i modify appsettings.json on the following
```
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore.Hosting": "Warning",
      "Microsoft.AspNetCore.Routing": "Warning",
      "Microsoft.AspNetCore.Mvc": "Warning"
    }
```
 in this case, my  recorded logs will not be output. if i remove `"Microsoft.AspNetCore.Mvc": "Warning"` my recorded logs will be output .How should I modify it?

**appsettings.json**
```
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore.Hosting": "Warning",
      "Microsoft.AspNetCore.Routing": "Warning",
      "Microsoft.AspNetCore.Mvc": "Warning"
    }
```
**configure in Startup.cs**
```
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            env.ConfigureNLog("NLog.config");
            loggerFactory.AddNLog();
            app.UseMiddleware<CustomMiddleware>();
            app.UseMvc();
        }
```
**Program.cs**
```
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args).ConfigureAppConfiguration((builderContext, config) =>
            {
                config.AddJsonFile("appsetting.json", optional: true, reloadOnChange: true)
                 .AddJsonFile($"appsettings.{builderContext.HostingEnvironment.EnvironmentName}.json", true, true)
                 ;
            })
                .UseStartup<Startup>();
    }
```

**Comment by snakefoot** [comment]
Same question here:

https://stackoverflow.com/questions/56032275/how-to-turn-off-microsoft-logs-in-aspnetcore-2-2-nlog

Where the answer was to also filter `Microsoft.AspNetCore` and `System.Net.Http.HttpClient`
