### ISSUE TITLE
Not supported exception while trying to get position of stream

### ISSUE THREAD

**Issue by Baklap4** [NLog/NLog.Web#429]
- Bug

**NLog version**: 4.6.4

**NLog.Web.AspNetCore version**: 4.8.2

**NLog.Extensions.Logging version**: 

**Platform**:  .NET Core 2 

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogToConsole="true">

  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
    <add assembly="NLog.Targets.ElasticSearch"/>
  </extensions>
  
  <variable name="verbose" value="${longdate} | ${machinename} | ${aspnet-request-ip} | ${aspnet-request-url} | ${level} | ${logger} | ${message}"/>
  <!--<variable name="verbose" value="${machinename} | ${level} | ${message}"/>-->
  <targets>
    <!--<target name="Console" xsi:type="Console" layout="${longdate} ${callsite} ${level} ${message}" />-->
    <target name="ElasticWrapper" xsi:type="BufferingWrapper" bufferSize="2000" flushTimeout="30000">
      <target name="Elastic" xsi:type="ElasticSearch" index="index-${date:format=yyyy}" uri="uri" disablePing="true" username="user" password="password" requireAuth="true">
        <field name="application" layout="${event-properties:item=application}" />
        <field name="contextId" layout="${event-properties:item=contextId}" />
        <field name="scope" layout="${event-properties:item=scope}" />
        <field name="origin" layout="${event-properties:item=origin}" />
        <field name="message" layout="${event-properties:item=message}" />
        <field name="stacktrace" layout="${event-properties:item=stacktrace}" />
        <field name="aspnet-mvc-action" layout="${aspnet-mvc-action}" />
        <field name="aspnet-mvc-controller" layout="${aspnet-mvc-controller}" />
        <field name="aspnet-request-ip" layout="${aspnet-request-ip}" />
        <field name="aspnet-request-form" layout="${aspnet-request-form}" />
        <field name="aspnet-request-host" layout="${aspnet-request-host}" />
        <field name="aspnet-request-method" layout="${aspnet-request-method}" />
        <!--The layout to blame -->
        <field name="aspnet-request-posted-body" layout="${aspnet-request-posted-body}" />
        <field name="aspnet-request-querystring" layout="${aspnet-request-querystring}" />
        <field name="aspnet-request-referrer" layout="${aspnet-request-referrer}" />
        <field name="aspnet-request-url" layout="${aspnet-request-url:IncludeQueryString=true}" />
        <field name="aspnet-user-authtype" layout="${aspnet-user-authtype}" />
        <field name="aspnet-user-identity" layout="${aspnet-user-identity}" />
        <field name="aspnet-user-isauthenticated" layout="${aspnet-user-isauthenticated}" />
      </target>
    </target>
    <target name="Console" xsi:type="Console" layout="${verbose}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="Console" />
    <logger name="*" minlevel="Debug" writeTo="ElasticWrapper" />
  </rules>
</nlog>

```

In case of a BUG:

- What is the current result?
with `aspnet-request-posted-body` enabled nlog throws an error:
```
2019-06-04 16:09:29.8070 Warn Exception in layout renderer. Exception: System.NotSupportedException: Specified method is not supported.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.get_Position()
   at NLog.Web.LayoutRenderers.AspNetRequestPostedBody.TryGetBody(HttpRequest httpRequest, Nullable`1 contentLength, Stream& body)
   at NLog.Web.LayoutRenderers.AspNetRequestPostedBody.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
```
- What is the expected result?
NLog should gracefully check and catch the NotSupportedException.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
See above.
- Please post full exception details (message, stacktrace, inner exceptions)
See above.
- Are there any workarounds? no
- Is there a version in which it did work? No idea
- Can you help us by writing an unit test?

Within the function [`TryGetBody`](https://github.com/NLog/NLog.Web/blob/da1e926644f16c1c10724bba0946b11fc696b16e/src/Shared/LayoutRenderers/AspNetRequestPostedBody.cs#L83-L134) one calls the get of property: [`Stream.CanSeek()`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canseek?view=netframework-4.8)

If you cannot seek you cannot get the position as stated [here](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canseek?view=netframework-4.8#remarks) This results in a NotSupportedException.

> Remarks
> If a class derived from Stream does **not** support seeking, calls to Length, SetLength, Position, and Seek throw a NotSupportedException.
> If the stream is closed, this property returns false.

I'd love to use this but now it crashes sadly.. :(

**Comment by 304NotModified** [comment]
Thanks for reporting!

Bit strange that it works on my machine, but we will make it more robust if possible

**Comment by Baklap4** [comment]
That'd be weird as the docs of microsoft say: 
> If a class derived from Stream does not support seeking, calls to Length, SetLength, Position, and Seek throw a NotSupportedException.

[Here](https://github.com/NLog/NLog.Web/blob/da1e926644f16c1c10724bba0946b11fc696b16e/src/Shared/LayoutRenderers/AspNetRequestPostedBody.cs#L111-L114) you're trying to read the property `Position` from body which is of type `Stream` making the framework do a call to `Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.get_Position()`

As stated in the docs this throws a [`NotSupportedException`](https://docs.microsoft.com/en-us/dotnet/api/system.notsupportedexception?view=netcore-2.2)

I can't seem to find the usecase to get the stream position aswell.. except for the [one log line](https://github.com/NLog/NLog.Web/blob/da1e926644f16c1c10724bba0946b11fc696b16e/src/Shared/LayoutRenderers/AspNetRequestPostedBody.cs#L116).. Maybe the if statement should be the other way around?

**Comment by 304NotModified** [comment]
working on this now

**Comment by 304NotModified** [comment]
I removed the `body.Position`, and it tested it with the example site :)

**Comment by 304NotModified** [comment]
@Baklap4 this should be fixed and it's live!

**Comment by snakefoot** [comment]
Thanks to @bakgerman now NLog.Web.AspNetCore v5.1 re-introduces [${aspnet-request-posted-body}](https://github.com/NLog/NLog/wiki/AspNet-Request-posted-body-layout-renderer) with help from middleware:
```c#
app.UseMiddleware<NLog.Web.NLogRequestPostedBodyMiddleware>();
```
It is no longer necessary to explicit call `context.Request.EnableBuffering();` as it is handled by the middleware.
