### ISSUE TITLE
DNX: ${aspnet-request:serverVariable} is unsupported

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#44]
Because `Request.ServerVariables` has been removed (without replacement) in DNX. 

As of today (ASP.NET 5 RC1), there is no replacement.

**Comment by vivaunix** [comment]
Will this work?
Request.HttpContext.Connection.RemoteIpAddress
etc...

**Comment by 304NotModified** [comment]
Well not as drop-in replacement for `${aspnet-request:serverVariable}`

But we like to include this in https://github.com/NLog/NLog.Web/issues/45

**Comment by 304NotModified** [comment]
Replaced by the new renderers in https://github.com/NLog/NLog.Web/pull/54
