### ISSUE TITLE
Setting TraceIdentifier breaks aspnet layout rendreres

### ISSUE THREAD

**Issue by ilya-spv** [NLog/NLog.Web#462]
**Type** (choose one):

- Bug

**NLog.Web/NLog.Web.AspNetCore version**:  4.8.5

**Platform**: .NET Core 2 

**Current NLog config** (xml or C#, if relevant)

```c#
var assembly = Assembly.Load("NLog.Web.AspNetCore");
ConfigurationItemFactory.Default.RegisterItemsFromAssembly(assembly);

var consoleTarget = new ColoredConsoleTarget("console")
{
    Layout = new JsonLayout
    {
        Attributes =
        {
            new JsonAttribute("timestamp", new SimpleLayout("${date:format=o}")),
            new JsonAttribute("level", new SimpleLayout("${level}")),
            new JsonAttribute("category", "${logger}"),
            new JsonAttribute("message", new SimpleLayout("${message}")),
            new JsonAttribute("exception", new SimpleLayout("${exception:format=ToString}")),
            new JsonAttribute("customerId", new SimpleLayout("${aspnet-request:header=X-Customer-ID}")),
            new JsonAttribute("correlationId", new SimpleLayout("${aspnet-request:header=X-Correlation-ID}")),
            new JsonAttribute("traceId", new SimpleLayout("${aspnet-TraceIdentifier}"))
        }
    }
};

var loggingConfiguration = new LoggingConfiguration();
loggingConfiguration.AddTarget(consoleTarget);
loggingConfiguration.AddRuleForAllLevels(consoleTarget);

NLog.LogManager.Configuration = loggingConfiguration;

```

I have a middleware registered as the very first middleware in the pipline that does this:

```c#
public async Task Invoke(HttpContext context, IHostingEnvironment environment)
{
    string proxyRequestId = context.Request.Headers["X-Proxy-Request-ID"];

    if (proxyRequestId != null)
    {
        context.TraceIdentifier = proxyRequestId;
    }

    await _next(context);
}
```

After this middleware is called with a header present, NLog stops outputting aspnet layout elements, while this pops up in internal log:

`No available HttpContext. Logging outside valid request context?`

In case of a BUG:

- What is the current result?

  AspNet Layout renderers stop working

- What is the expected result?

 Renderers work as before
 
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

   `No available HttpContext. Logging outside valid request context?`

- Please post full exception details (message, stacktrace, inner exceptions)

   No exception is thrown

- Are there any workarounds? yes/no

   Not change TraceId

- Is there a version in which it did work? 

   Not that I know of

- Can you help us by writing an unit test?

   Not sure how

**Comment by snakefoot** [comment]
NLog lookup the HttpContext-property from the `serviceProvider.GetService<IHttpContextAccessor>()` and don't care about TraceIdentifier:

https://github.com/NLog/NLog.Web/blob/dab12cc420341d337276bb574b0b92c0bb1b74d3/src/Shared/LayoutRenderers/AspNetLayoutRendererBase.cs#L93-L96

But I recall that AspNetCore-framework has internal checks that the internal TraceIdentifier matches the one of the HttpContext, and only returns the HttpContext when it matches.

Instead of overwriting the HttpContext.TraceIdentifier then insert an "magic-string-name" in HttpContext.Items with your Guid-Value. If this is not good enough for you, then you need to contact Microsoft AspNetCore-framework developers and have them help you.

**Comment by ilya-spv** [comment]
Thanks a lot for help, it seems that this is a bug that is fixed in .net core 3.0 and backported to 2.2 as well (https://github.com/aspnet/AspNetCore/issues/5144). I'll try to update dotnet core and see if it's working.

Anyway, your help is greatly appreciated and Nlog is a very good library :)

**Comment by ilya-spv** [comment]
I have updated to dotnet runtime 2.2.7 and it works just fine there. Thanks for help once again, we can just close this issue I guess.

**Comment by 304NotModified** [comment]
Thanks for the confirmation!
