### ISSUE TITLE
License mismatch between license and readme

### ISSUE THREAD

**Issue by thomfre** [NLog/NLog.Web#47]
BSD is specified as license in readme, but GPL is included in license file. Which one is correct?

**Comment by dabide** [comment]
This is actually a rather serious issue: If NLog.Web is GPL licensed, all software that uses it also has to be. Also, all contributors that have contributed code to NLog.Web after Jan 31, 2015 might have to agree to re-license their code under a BSD license.

The conflicting clause about the BSD license in the README wasn't added until June 13, 2015.

**Comment by 304NotModified** [comment]
This indeed serious. It's BSD. Too bad I cannot change the file headers on my own. 

Personally I would never write GPL software.  

I need assistance of @Xharze to change this.  Will send him an email.
