### ISSUE TITLE
Docs for 4.9 release

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#479]
[See items todo](https://github.com/NLog/NLog.Web/issues?q=label%3A%22needs+documentation+on+wiki%22+milestone%3A%22NLog.Web+%2B+NLog.Web.AspNetCore+4.9%22+-label%3A%22docs+done%22 )

**Comment by 304NotModified** [comment]
only https://github.com/NLog/NLog.Web/pull/473 needed now

**Comment by snakefoot** [comment]
> @304NotModified only #473 needed now

Created wiki: https://github.com/NLog/NLog/wiki/AspNetRequest-Headers-Layout-Renderer

**Comment by 304NotModified** [comment]
all done, thanks!
