### ISSUE TITLE
Support ASP.NET Core 3

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#481]
related #480

**Comment by yhnbgfd** [comment]
3.0：When PublishSingleFile, Nlog cannot log to file

**Comment by snakefoot** [comment]
@yhnbgfd Please report the unexpected behavior to Microsoft. AppDomain.BaseDirectory should not point to the temporary-directory. Some good places to write your complaint:

https://github.com/aspnet/AspNetCore/issues/12621
https://github.com/dotnet/core-setup/issues/7491

**Comment by superdevguy** [comment]
Hi there, i wanted to jump in here and ask if .NET Core 3 support is coming soon. I have a .NET Core 3 application and I am using NLog as shown in the .NET Core 2 sample with a database and fallback to file system if fails. I can't get any logs on the file system or in the database. I pulled the example out of my other working .NET Core 2 application.

Any ideas when it might be supported or if there is a workaround for now?

Thanks!

**Comment by 304NotModified** [comment]
> Hi there, i wanted to jump in here and ask if .NET Core 3 support is coming soon. I have a .NET Core 3 application and I am using NLog as shown in the .NET Core 2 sample with a database and fallback to file system if fails. I can't get any logs on the file system or in the database. I pulled the example out of my other working .NET Core 2 application.
> 
> Any ideas when it might be supported or if there is a workaround for now?
> 
> Thanks!

Is this with PublishSingleFile?

I try to get the .NET core 3 stuff get ready this week. I have unfortunately some troubles running .NET Core 3 myself

**Comment by superdevguy** [comment]
Sorry I am not sure what you mean by PublishSingleFile. Can you elaborate a bit more please?

**Comment by 304NotModified** [comment]
> Sorry I am not sure what you mean by PublishSingleFile. Can you elaborate a bit more please?

https://dotnetcoretutorials.com/2019/06/20/publishing-a-single-exe-file-in-net-core-3-0/

> 3.0：When PublishSingleFile, Nlog cannot log to file.
> fix use: `${basedir:processDir=true}`

**Comment by superdevguy** [comment]
I tried adding it, but no luck. It is writing the internal-nlog.txt file, but it won't write any of the errors on the file system, or in the database. My config file:

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Info"
      internalLogFile="${basedir}\logs\internal-nlog.txt">

  
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  
  <targets>

    <target xsi:type="FallbackGroup" name="fb1" returnToFirstOnSuccess="true">
      <target name="db"
       xsi:type="Database"
       connectionString="${configsetting::name=ConnectionStrings.Connection}"
       commandType="StoredProcedure"
       commandText="[dbo].[NLog_AddEntry]">
        <parameter name="@machineName"    layout="${machinename}" />
        <parameter name="@logged"           layout="${date}" />
        <parameter name="@level"          layout="${level}" />
        <parameter name="@message"        layout="${message}" />
        <parameter name="@logger"         layout="${logger}" />
        <parameter name="@properties"     layout="${all-event-properties:separator=|}" />
        <parameter name="@callsite"       layout="${callsite}" />
        <parameter name="@exception"      layout="${exception:tostring}" />
      </target>

      <target xsi:type="File" name="ownFile-web" fileName="${basedir:processDir=true}\logs\nlog-app-${shortdate}.log"
          layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}" />
    </target>
  </targets>

  
  <rules>
    
    

    
    <logger name="Microsoft.*" maxlevel="Error" final="true" />
    
    <logger name="*" minlevel="Error" writeTo="fb1" />
    
  </rules>
</nlog>

**Comment by snakefoot** [comment]
If you can attach a small example project showing the problem with NLog. Then we can try look at it. But it sounds like NLog cannot find the Nlog.config file.


What happens if you enable NLog InternalLogger through code before creating first NLog Logger object. What locations does it scan for nlog.config?


Sent from my Sony Xperia


---- superdevguy wrote ----


Hi there, i wanted to jump in here and ask if .NET Core 3 support is coming soon. I have a .NET Core 3 application and I am using NLog as shown in the .NET Core 2 sample with a database and fallback to file system if fails. I can't get any logs on the file system or in the database. I pulled the example out of my other working .NET Core 2 application.

Any ideas when it might be supported or if there is a workaround for now?

Thanks!

**Comment by superdevguy** [comment]
No problem finding config file. This is from internal log:

2019-09-30 12:20:18.1752 Info Message Template Auto Format enabled
2019-09-30 12:20:18.1910 Info Loading assembly: NLog.Web.AspNetCore
2019-09-30 12:20:18.2572 Info Adding target FallbackGroupTarget(Name=fb1)
2019-09-30 12:20:18.2909 Info Found 57 configuration items

**Comment by superdevguy** [comment]
It is failing to log to the database when an error occurs and also not logging to a file. I am currently just running in development mode on my local machine so it should have 100% access to the stored procedure in the database.

**Comment by snakefoot** [comment]
I'm guessing there is some issue with {config setting} were you load the Nlog.config before you have hooked NLog to NetCore appsettings.json. Think I have created an issue about improving this. Maybe the new AddNLog methods in NLog.Web.AspNetCore ver 4.9 will be helpful for you.


Sent from my Sony Xperia


---- superdevguy wrote ----


It is failing to log to the database when an error occurs and also not logging to a file. I am currently just running in development mode on my local machine so it should have 100% access to the stored procedure in the database.

**Comment by superdevguy** [comment]
Thanks guys, turns out the problem was I forgot to Copy to Output Directory. Working fine now!

**Comment by 304NotModified** [comment]
fixed by https://github.com/NLog/NLog.Web/pull/496, thanks @snakefoot !
