### ISSUE TITLE
Error on  ${aspnet-user-identity} when running project

### ISSUE THREAD

**Issue by feanor91** [NLog/NLog.Web#500]
Hello

I think there is a problem with aps-net.* layout rendere when using appsetings.json file to configure NLog.

All works fine when NLog is configured throughout its own XML config file, but when I transpose this configuration to appsettings.json file I have a crash on startup with this message :

> Warn Error when setting '${aspnet-user-identity}' on attibute 'layout' Exception: NLog.NLogConfigurationException: Error when setting property 'Layout' on NLog.Targets.DatabaseParameterInfo ---> System.ArgumentException: LayoutRenderer cannot be found: 'aspnet-user-identity'. Is NLog.Web not included?

My Nlog config section is like this :

`    "NLog": {
        "autoReload": true,
        "throwConfigExceptions": true,
        "internalLogLevel": "info",
        "internalLogFile": "c:/app/log/dev/internal-appsetting-nlog.txt",
        "extensions": {
            "NLog.Extensions.Logging": {
                "assembly": [
                    "NLog.Extensions.Logging"
                ]
            },
            "NLog.Web.AspNetCore": {
                "assembly": [
                    "NLog.Web.AspNetCore"
                ]
            }
        },
        "variables": {
            "var_logdir": "c:/app/log/dev"
        },
        "default-wrapper": {
            "type": "AsyncWrapper",
            "overflowAction": "Block"
        },
        "targets": 
            "db": {
                "type": "Database",
                "commandText": "INSERT INTO logtable (LOG_TRACETIME, LOG_LOGLEVEL, LOG_LOGGER, LOG_MESSAGE, LOG_MACHINENAME, LOG_CALLSITE, LOG_THREADID, LOG_EXCEPTIONMESSAGE, LOG_STACKTRACE) VALUES (TO_TIMESTAMP(:pTRACETIME, 'YYYY-MM-DD HH24:MI:SS.FF'),:pLEVEL,:pLOGGER,:pMESSAGE,:pMACHINENAME, :pCALLSITE,:pTHREADID,:pEXCEPTIONMESSAGE,:pSTACKTRACE)",
                "parameters": [
                    {
                        "name": "TRACETIME",
                        "layout": "${longdate}"
                    },
                    {
                        "name": "@pLEVEL",
                        "layout": "${level}"
                    },
                    {
                        "name": "@pLOGGER",
                        "layout": "${logger}"
                    },

                    {
                        "name": "@pMESSAGE",
                        "layout": "${message}"
                    },
                    {
                        "name": "@pMACHINENAME",
                        "layout": "${machinename}"
                    },
                    {
                        "name": "@pUSERNAME",
                        "layout": "${aspnet-user-identity}"
                    },
                    {
                        "name": "@pCALLSITE",
                        "layout": "${callsite:filename=true}"
                    },
                    {
                        "name": "@pTHREADID",
                        "layout": "${threadid}"
                    },
                    {
                        "name": "@pEXCEPTIONMESSAGE",
                        "layout": "${exception}"
                    },
                    {
                        "name": "@pSTACKTRACE",
                        "layout": "${stacktrace}"
                    }
                    },
                    //{
                    //    "name": "@pSESSIONID",
                    //    "layout": "${aspnet-sessionid}"
                    //}
                ],
                "dbProvider": "Oracle.ManagedDataAccess.Client.OracleConnection, Oracle.ManagedDataAccess",
                "connectionString": "${configsetting:name=appSettings.myDatabase}"
            }
        },
        "rules": [
            {
                "logger": "Microsoft.*",
                "minLevel": "Warn",
                "writeTo": "db"
            },
            {
                "logger": "*",
                "minLevel": "Info",
                "writeTo": "db"
            }
        ]
    },`

Program.cs is :

`   public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    var env = hostingContext.HostingEnvironment;

                    //Read configuration from appsettings.json
                    config
                        .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                        .AddJsonFile($"appsettings.{env.EnvironmentName}.json",
                                        optional: true, reloadOnChange: true);
                    //Add environment variables to config
                    config.AddEnvironmentVariables();

                    //Read NLog configuration from the nlog config file
                    //env.ConfigureNLog($"nlog.{env.EnvironmentName}.config");
                })
                .ConfigureLogging(logging =>
                {
                    logging.ClearProviders();
                    logging.AddDebug();
                    logging.AddConsole();
                    logging.AddNLog();
                });
    }`

.NetCore  version is 2.2, I uploaded all the moste recents packages from NuGet for all needed packages

**Comment by jenscski** [comment]
What happens if you remove logging.AddNLog(); and instead uses IWebHostBuilder.UseNLog?

```
.ConfigureLogging(logging =>
{
        logging.ClearProviders();
        logging.AddDebug();
        logging.AddConsole();
})
.UseNLog();
```

**Comment by feanor91** [comment]
Hi, thanks, it works, I have no more error, meanwhile, user and session columns are not filed into DB

**Comment by snakefoot** [comment]
Have you checked the Wiki-page for `${aspnet-user-identity}` ?

https://github.com/NLog/NLog/wiki/AspNetUserIdentity-layout-renderer

See also: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity

**Comment by feanor91** [comment]
Nope I didn't read but I do now and applied what I read but it doesn't work too.Meanwhile I wonder if it is not related to something else. I have to dig to try to understand.

I changed back with UseNlog and the new JSON format and this works well.

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
