### ISSUE TITLE
asp.net core 3.0 Unknown element with name 'StaticWebAssets' found in keyring

### ISSUE THREAD

**Issue by jstzwhc** [NLog/NLog.Web#511]
In nlog.config

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Info"
      internalLogFile="c:\temp\internal-nlog.txt">

  
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  
  <targets>
    
    <target xsi:type="File" name="allfile" fileName="c:\temp\nlog-all-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}" />

    
    <target xsi:type="File" name="ownFile-web" fileName="c:\temp\nlog-own-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}" />
  </targets>

  
  <rules>
    
    <logger name="*" minlevel="Trace" writeTo="allfile" />

    
    <logger name="Microsoft.*" maxlevel="Info" final="true" /> 
    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />
  </rules>
</nlog>

      Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[15]
      Unknown element with name 'StaticWebAssets' found in keyring

**Comment by snakefoot** [comment]
@jstzwhc Does not sound like an issue in NLog, but something not setup right in your Asp.Net.Core-application.

Maybe try StackOverflow or create an issue for AspNetCore: https://github.com/aspnet/AspNetCore

**Comment by snakefoot** [comment]
Marking this issue as resolved. If not then please re-open.
