### ISSUE TITLE
No HttpContext in async/await scenario?

### ISSUE THREAD

**Issue by tneuberger** [NLog/NLog.Web#513]
Hey folks,

we use NLog in an ASP.NET Core 2.2 web app running in a WebHost. No matter if the Action called is async or not, seemingly all information from the HttpContext is empty in the log file. What I care about is the traceidentifier, others like activityId or request-url are for testing purposes only.

Am I doing something wrong? How can I put some Information to identify the request into the logfile?

Thanks
Thomas

**Type** (choose one): Question
**NLog version**: 4.6.7
**NLog.Web/NLog.Web.AspNetCore version**: 4.9.0
**NLog.Extensions.Logging version**: 2.2.0
**Platform**: .NET Core 2 
**Current NLog config** (xml or C#, if relevant)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xsi:schemaLocation="NLog NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogFile="c:\temp\console-example-internal.log"
      internalLogLevel="Info"  
      throwExceptions="true">
  
  <!-- enable asp.net core layout renderers -->
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <!-- the targets to write to -->
  <targets async="true">
    <target name="info" xsi:type="File"
            fileName="${basedir}/Logs/Info_${shortdate}.log"
            layout="[${longdate}] [${uppercase:${level}}] [${aspnet-TraceIdentifier}] [${activityid}] [${aspnet-request-url:IncludeQueryString=false}] [${logger}] ${message} ${exception:format=tostring}"
            concurrentWrites="false" keepFileOpen="false"/>
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" maxlevel="Warn" writeTo="info" maxArchiveFiles="10" />
  </rules>
</nlog>

```

**Comment by snakefoot** [comment]
> No matter if the Action called is async or not, seemingly all information from the HttpContext is empty in the log file

If `${aspnet-TraceIdentifier}] [${activityid}] [${aspnet-request-url:IncludeQueryString=false}]` is always empty then you should check out the example project (that works) and see what you do differently:

https://github.com/NLog/NLog.Web/tree/dev/examples/ASP.NET%20Core%202/Visual%20Studio%202017/ASP.NET%20Core%202%20-%20VS2017

Do you remember to call `UseNLog()` or `AddNLog()` ? (Maybe show the code that registers NLog, and the logging code that fails).

Can you include the `internalLogFile`-output with `internalLogLevel="Debug"` from a session where output fails ?

**Comment by tneuberger** [comment]
Thanks for the RTFM, it actually helped. 

The call to UseNlog() was missing in Program.cs.
