### ISSUE TITLE
Wrong trace identifier on ASP.Net Core 3.0

### ISSUE THREAD

**Issue by jenscski** [NLog/NLog.Web#523]
I'm using the ${aspnet-traceidentifier} layout renderer to put the trace identifier in the logs, so I can match it with the value from the problem details report built into ASP.Net Core.

But the value from the problem details and from ${aspnet-traceidentifier} is now different.

ASP.Net Core is now using ActivityId.

Ref.:
https://github.com/dotnet/aspnetcore/blob/2e4274cb67c049055e321c18cc9e64562da52dcf/src/Mvc/Mvc.Core/src/Infrastructure/DefaultProblemDetailsFactory.cs#L90 

Ref.:
https://github.com/dotnet/aspnetcore/issues/18876#issuecomment-583484818

Is it possible to either change the renderer, or create a new one that does the same as asp.net core?

**Comment by 304NotModified** [comment]
A new renderer would be nice. You you please send a pr?

See for example https://github.com/NLog/NLog.Web/blob/dev/src/Shared/LayoutRenderers/AspNetTraceIdentifierLayoutRenderer.cs

As this is only . net core, there is no need to place it the shared folder and make it working for net framework

PS tests would be nice if possible

**Comment by snakefoot** [comment]
@304NotModified  You already have this LayoutRenderer, It lives right here:

https://github.com/NLog/NLog.DiagnosticSource

> `${activity:property=Id}`

**Comment by 304NotModified** [comment]
cool! Thanks!

**Comment by 304NotModified** [comment]
@snakefoot it this https://github.com/NLog/NLog/wiki/Trace-Activity-Id-Layout-Renderer?

**Comment by snakefoot** [comment]
No that is the old one


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


@snakefoot<https://github.com/snakefoot> it this https://github.com/NLog/NLog/wiki/Trace-Activity-Id-Layout-Renderer?

**Comment by 304NotModified** [comment]
Ok the new one is also not listed on nlog-project/config?

**Comment by snakefoot** [comment]
Well it has never been released


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Ok the new one is also not listed on nlog-project/config?

**Comment by jenscski** [comment]
This won't help, as it's not published to nuget.org, so please re-open and look at the PR from @snakefoot 

> @304NotModified You already have this LayoutRenderer, It lives right here:
> 
> https://github.com/NLog/NLog.DiagnosticSource
> 
> > `${activity:property=Id}`

**Comment by 304NotModified** [comment]
@jenscski pre-release is here: https://ci.appveyor.com/project/nlog/nlog-web/branch/master/artifacts (still the same version number currently)

**Comment by 304NotModified** [comment]
FYI, docs are updated for this: https://github.com/NLog/NLog/wiki/AspNetTraceIdentifier-Layout-Renderer
