### ISSUE TITLE
The efficiency of custom log writing to directory is much lower than that of the directory configured by default in the configuration file

### ISSUE THREAD

**Issue by feiyit** [NLog/NLog.Web#528]
- Bug
- Feature request
- Question

**NLog version**: 4.6.8

**NLog.Web/NLog.Web.AspNetCore version**: 4.9.0

**NLog.Extensions.Logging version**: 1.6.0

**Platform**: .NET Core 3.1 

**Current NLog config** (xml)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwConfigExceptions="true"
      internalLogLevel="info">

  <!-- enable asp.net core layout renderers -->
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <!-- the targets to write to -->
  <targets>
    <!-- write logs to file  -->
    <target xsi:type="File" name="allfile" fileName="logs/nlog-all-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId_Id:whenEmpty=0}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}" />

    <!-- another file log, only own logs. Uses some ASP.NET core renderers -->
    <target xsi:type="File" name="ownFile-web" fileName="logs/nlog-all-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId_Id:whenEmpty=0}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}|${callsite}" />
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Trace" writeTo="allfile" />

    <!--Skip non-critical Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" maxlevel="Info" final="true" />
    <!-- BlackHole -->

    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />
  </rules>
</nlog>
```
Custom input log configuration class
```C#
public class Logger
    {
        NLog.Logger _logger;
        private Logger(NLog.Logger logger)
        {
            _logger = logger;
        }
        public Logger(string name) : this(LogManager.GetLogger(name))
        {

        }

        public static Logger Default { get; private set; }
        static Logger()
        {
            Default = new Logger(LogManager.GetCurrentClassLogger());
        }

        private static string _path = "";

        public void Setting(string path)
        {
            if (_path != path)
            {
                _path = path;
                Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
                var config = new NLog.Config.LoggingConfiguration();
                var logfile = new NLog.Targets.FileTarget() { FileName = "logs/${date:format=yyyyMM}/${shortdate}_log.txt", Encoding = Encoding.GetEncoding("GB2312") };
                if (!string.IsNullOrEmpty(path))
                {
                    path += "/";
                    logfile = new NLog.Targets.FileTarget() { FileName = "logs/" + path + "${shortdate}_log.txt", Encoding = Encoding.GetEncoding("GB2312") };
                }
                config.LoggingRules.Add(new NLog.Config.LoggingRule("*", LogLevel.Debug, logfile));
                LogManager.Configuration = config;
            }
        }
        }
```
Startup.cs    Load profile
```C#
NLog.LogManager.LoadConfiguration("nlog.config").GetCurrentClassLogger();
```

Program.cs    
```C#
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .ConfigureLogging(logging =>
                {
                    logging.ClearProviders();
                    logging.SetMinimumLevel(LogLevel.Trace);
                })
                .UseNLog();
```

Test Code:
一、First, read the configuration file, default test。Log output to logs/nlog-all-2020-03-18.log file
```C#
[HttpGet]
        public string Get()
        {
            //Logger.Default.Setting("");
            Stopwatch = new Stopwatch();
            Stopwatch.Start();
            for (int i = 0; i < 10; i++)
            {
                Logger.Default.Info("TestDefault"+i);
            }
            Stopwatch.Stop();
            return Stopwatch.Elapsed.TotalMilliseconds.ToString();
        }
```
Within 20 ms on average 

二、Second: custom input log directory。   Log output to logs/Test/2020-03-18_log.txt file
```C#
[HttpGet("testlog")]
        public string TestLog()
        {
            Logger.Default.Setting("Test");
            Stopwatch = new Stopwatch();
            Stopwatch.Start();
            for (int i = 0; i < 10; i++)
            {
                Logger.Default.Info("Test"+1);
            }
            Stopwatch.Stop();
            return Stopwatch.Elapsed.TotalMilliseconds.ToString();
        }
```
Execution average about 60 ms

Excuse me, how can I optimize the code and get the result of default configuration? Thank you

**Comment by snakefoot** [comment]
If performance is very important then you should read this page:

https://github.com/NLog/NLog/wiki/Performance

Use `KeepFileOpen=true `and `ConcurrentWrites=false` for the FileTarget to get best performance.

You should configure the NLog FileTarget at application startup. Not for every HttpGet-request.

**Comment by snakefoot** [comment]
Has your issue been resolved?

**Comment by feiyit** [comment]
No,
&nbsp;I wrote a demo. Please help me to see how to optimize it.


Demo is based on NETCORE 3.1 web application


Run the default address, access https://localhost:44308/weatherforecast read the NLog default configuration address and write it to the directory.


The custom configuration write directory is: https://localhost:44308/weatherforecast/nlog.


The performance gap between the two is about 3 times.


Thank you





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Rolf Kristensen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 晚上11:53
收件人:&nbsp;"NLog/NLog.Web"<NLog.Web@noreply.github.com&gt;;
抄送:&nbsp;"Jason.付裕"<715515390@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NLog/NLog.Web] The efficiency of custom log writing to directory is much lower than that of the directory configured by default in the configuration file (#528)





 
Has your issue been resolved?

**Comment by snakefoot** [comment]
Again don't change nlog config on every Http request. And measure longer than 30ms


Sent from my Sony Xperia


---- feiyit wrote ----


No,
&nbsp;I wrote a demo. Please help me to see how to optimize it.


Demo is based on NETCORE 3.1 web application


Run the default address, access https://localhost:44308/weatherforecast read the NLog default configuration address and write it to the directory.


The custom configuration write directory is: https://localhost:44308/weatherforecast/nlog.


The performance gap between the two is about 3 times.


Thank you





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Rolf Kristensen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 晚上11:53
收件人:&nbsp;"NLog/NLog.Web"<NLog.Web@noreply.github.com&gt;;
抄送:&nbsp;"Jason.付裕"<715515390@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NLog/NLog.Web] The efficiency of custom log writing to directory is much lower than that of the directory configured by default in the configuration file (#528)






Has your issue been resolved?

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by feiyit** [comment]
Thank you


The problem has been resolved.


"Variable" by variable





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Rolf Kristensen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 晚上6:24
收件人:&nbsp;"NLog/NLog.Web"<NLog.Web@noreply.github.com&gt;;
抄送:&nbsp;"Jason.付裕"<715515390@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NLog/NLog.Web] The efficiency of custom log writing to directory is much lower than that of the directory configured by default in the configuration file (#528)





 Again don't change nlog config on every Http request. And measure longer than 30ms 
 
 
 Sent from my Sony Xperia 
 
 
 ---- feiyit wrote ---- 
 
 
 No, 
 &amp;nbsp;I wrote a demo. Please help me to see how to optimize it. 
 
 
 Demo is based on NETCORE 3.1 web application 
 
 
 Run the default address, access https://localhost:44308/weatherforecast read the NLog default configuration address and write it to the directory. 
 
 
 The custom configuration write directory is: https://localhost:44308/weatherforecast/nlog. 
 
 
 The performance gap between the two is about 3 times. 
 
 
 Thank you 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Rolf Kristensen"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月19日(星期四) 晚上11:53 
 收件人:&amp;nbsp;"NLog/NLog.Web"<NLog.Web@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Jason.付裕"<715515390@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [NLog/NLog.Web] The efficiency of custom log writing to directory is much lower than that of the directory configured by default in the configuration file (#528) 
 
 
 
 
 
 
 Has your issue been resolved? 
 
 ― 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 
 ―
