### ISSUE TITLE
Add RawTarget to AspNetRequestUrlRenderer 

### ISSUE THREAD

**Issue by sm-g** [NLog/NLog.Web#529]
**Type**: Feature request

**NLog version**: 4.6.8

**NLog.Web.AspNetCore version**: 4.9.0

**Platform**: .NET Core 3.1

I am using both Serilog and NLog. Serilog [logs http requests path](https://github.com/serilog/serilog-aspnetcore/blob/dev/src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs) such way (using [RawTarget](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.features.ihttprequestfeature.rawtarget)):

```
httpContext.Features.Get<IHttpRequestFeature>()?.RawTarget ?? httpContext.Request.Path.ToString()
```

It is possible to add options to AspNetRequestUrlRenderer. 
Maybe it should be default choice, like in Serilog.

**Comment by 304NotModified** [comment]
Thanks!

In doubting if we should create a new layout renderer for this instead of adding it to AspNetRequestUrlRenderer

**Comment by 304NotModified** [comment]
@sm-g polite bump

**Comment by 304NotModified** [comment]
@snakefoot what do you think? Separate renderer? I'm thinking aspnet-request-rawtarget

**Comment by snakefoot** [comment]
Since `IncludeScheme` and `IncludeHost` and `IncludePort`  will have to be duplicated, then I don't think it is wrong for it to be part of `${aspnet-request-url}`

**Comment by 304NotModified** [comment]
True, ok thanks!

**Comment by 304NotModified** [comment]
#530 merged!
