### ISSUE TITLE
Additional Renderer - Consolidation - Proposal

### ISSUE THREAD

**Issue by Page-Not-Found** [NLog/NLog.Web#53]
Consolidated List of Additional Renderer from various requests #21, #45 

- [x] 1. aspnet-request-cookie - To Render cookie(s) from the request. Allows comma separated to get multiple cookie values. Can also allow json formatting. 
- [x] 2. aspnet-request-querystring - To Render querystring(s) from the request.   Allows comma separated to get multiple querystring values. Can also allow json formatting. 
- [x] 4. aspnet-request-method - To Render the Http Method for the request.  
- [x] 5. aspnet-request-referrer - To Render the Referrer URL. 
- [x] 6. aspnet-request-url - To Render the Request URL.
- [x] 7. aspnet-mvc-action - To Render the MVC action method. 
- [x] 8. aspnet-mvc-controller - To Render the MVC Controller Name.
- [x] 9. aspnet-host - To Capture the HOST.in MVC Core Apps (a.k.a ASP.NET 5)
- [x] 12. aspnet-useragent - To Capture the Useragent of the request. 

**Nice to Have**

1. aspnet-mvc-routedata - To capture the additional information, not sure if this is possible but can check. 
2. aspnet-machinename - To Capture the machine name where the WebSite is hosted. Not Sure if there is  another NLog Layout Renderer can accommodate the same. This is available in the base NLog Refer https://github.com/NLog/NLog/wiki/Machinename-Layout-Renderer
3. aspnet-host-version - No sure if this is required, but just a thought. Needs more discussion. 

**History**
**04/19/2016**
Changed aspnet-request-referrerurl to aspnet-request-referrer
Changed aspnet-request-requesturl to aspnet-request-url
Added more renderer for User Agent, IP Addressm IsHttps (item 11, 12, 13) above

**06/04/2016** 
Moved this item from above. 
3. aspnet-request-servervariable - To Capture any servervariable. Allows comma separated to get mulitple server variables. Can also allow json formatting. This is specific to Pre MVC CORE 1.0 (a.k.a ASP.NET 5) 
13. aspnet-ipaddress - To Capture the ip address of the machine from where the request is made. 
11. aspnet-ishttps - true/false value which says if the site is setup as https or not.

**Comment by 304NotModified** [comment]
Looks nice,

What do you think about:

- User Agent: 
- IP Address: 
- proxy IP Address (x-Forwarded-For  header)

as discussed in https://github.com/NLog/NLog.Web/issues/21?

Or is it outside this scope?

Also, we were not sure if the MVC prefix is correct. Maybe it should be "aspnet-route-action" instead of "aspnet-mvc-action", but that depends if we can use the same layout renderer for MVC and Web API.

**Comment by Page-Not-Found** [comment]
>> aspnet-request-referrerurl - To Render the Referrer URL.
>> aspnet-request-requesturl - To Render the Request URL.
> I propose: aspnet-request-referrer and aspnet-request-url for those.

Updated in the Main Comment. 

> What do you think about:
> 
> User Agent:
> IP Address:
> proxy IP Address (x-Forwarded-For header)
> as discussed in #21?
> 
> and:
> 
> IsHTTPS
> as discussed in #45?

Included these items except the X-Forwaded-For, Need to discuss on this.

**Comment by 304NotModified** [comment]
Looks complete and :+1:

**Comment by Page-Not-Found** [comment]
Any plans in which version we want to do this?

**Comment by 304NotModified** [comment]
The next minor version would be nice (4.3). This is really helpful for .NET Core

**Comment by 304NotModified** [comment]
@Page-Not-Found 

https://www.nuget.org/packages/NLog/4.3.5-alpha1

**Comment by 304NotModified** [comment]
fixed by https://github.com/NLog/NLog.Web/pull/54

**Comment by DanielLaberge** [comment]
What about getting the client's IP Address? It's not clear whether (or how) this is supported.

Previously was ${aspnet-request:serverVariable=remote_addr}

**Comment by Page-Not-Found** [comment]
@DanielLaberge I guess that was missed out. I vl get to those when I have sometime.

**Comment by 304NotModified** [comment]
Please do create a new Github issue. It's easier to track.
