### ISSUE TITLE
${aspnet-request-posted-body} could throw 'Synchronous operations are disallowed' for ASP.NET Core 3

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#548]
NLog 4.7.0
Nlog.Target.Http 1.0.1
Nlog.web.AspNet.Core 4.9.1
Aspnet.Core 3.1.201

internal logging first was indicating : 
```
Warn Exception in 'NLog.Web.LayoutRenderers.AspNetRequestPostedBody.Append()' 
Exception: System.InvalidOperationException: 
Synchronous operations are disallowed. 
Call ReadAsync or set AllowSynchronousIO to true instead.
```

After googling I found that I must add 

```c#
 services.Configure<IISServerOptions>(options =>
 {
     options.AllowSynchronousIO = true;
  });
````

_Originally posted by @husseinshaib1 in https://github.com/NLog/NLog/issues/3906#issuecomment-616199275_

**Comment by 304NotModified** [comment]
related https://github.com/graphql-dotnet/graphql-dotnet/pull/1325

**Comment by vlmironoff** [comment]
For Kestrel use:
`services.Configure<KestrelServerOptions>(options =>
{
         options.AllowSynchronousIO = true;
});`

**Comment by vlmironoff** [comment]
@304NotModified ${aspnet-request-posted-body} is always empty in logs. I'm using asp.net core 3.1
NLog.Web.AspNetCore assembly is added to nlog.config

**Comment by 304NotModified** [comment]
@vlmironoff  I think it depends when you're doing the logger call and if it's async. Please open a new issue for ths

**Comment by diegosps** [comment]
@vlmironoff  
This might help you or someone.
Like 304 said, if you are doing the logging after the request, you hava to enable the rewind of the stream:

```
public async Task Invoke(HttpContext httpContext, ILogger<RequestLogMiddleware> logger)
        {
            var sw = Stopwatch.StartNew();
            httpContext.Request.EnableBuffering(); //this line is the key (asp.net core 3.1)
            await _next(httpContext);

            sw.Stop();
            var code = httpContext.Response?.StatusCode;
            string usuario = string.Empty;
            if (!string.IsNullOrEmpty(httpContext.User.Identity.Name))
                usuario = httpContext.User.Identity.Name;
            if (httpContext.Request?.Method != "OPTIONS")
                logger.LogInformation("Testando o middleware: {usuario}, {codigo}, {tempo}", usuario, code, (int)Math.Truncate(sw.Elapsed.TotalMilliseconds));
        }
```

I also had to add the `options.AllowSynchronousIO = true` for kestrel and IIS

**Comment by snakefoot** [comment]
Thanks to @bakgerman now NLog.Web.AspNetCore v5.1 re-introduces [${aspnet-request-posted-body}](https://github.com/NLog/NLog/wiki/AspNet-Request-posted-body-layout-renderer) with help from middleware:
```c#
app.UseMiddleware<NLog.Web.NLogRequestPostedBodyMiddleware>();
```
It is no longer necessary to explicit call `context.Request.EnableBuffering();` as it is handled by the middleware.
