### ISSUE TITLE
Logging outside of request scope fails with exception

### ISSUE THREAD

**Issue by vegar** [NLog/NLog.Web#55]
In the [AspNetRequestValueLayoutRenderer.cs](https://github.com/NLog/NLog.Web/blob/master/NLog.Web.ASPNET5/LayoutRenderers/AspNetRequestValueLayoutRenderer.cs#L79) the request is fetched from the http context. Next, it's checked for null before values are appended to the log:

```
 protected override void DoAppend(StringBuilder builder, LogEventInfo logEvent)
 {
     var httpRequest = HttpContextAccessor.HttpContext.Request;
     if (httpRequest == null)
     {
          return;
     }
   ...
 }

```

The problem is that we never get an null return value. Instead an exception is thrown from the [.net framework](http://referencesource.microsoft.com/#System.Web/HttpContext.cs,a6f26bf8c782b8a5):

```
        /// <devdoc>
        ///    <para>
        ///       Retrieves a reference to the target <see cref='System.Web.HttpRequest'/>
        ///       object for the current request.
        ///    </para>
        /// </devdoc>
        public HttpRequest Request {
            get {
                 if (HideRequestResponse)
                    throw new HttpException(SR.GetString(SR.Request_not_available));
                return _request;
            }
        }
```

This is a problem when we use the logger outside a request context, like inside of `Application_Start()`, giving us the 'yellow screen of death':

![image](https://cloud.githubusercontent.com/assets/764517/15110834/8d4e822a-15e3-11e6-942e-22199a8be83f.png)

**Comment by vegar** [comment]
I see that originally, the request was fetched in [two steps](https://github.com/NLog/NLog.Web/commit/1170678c95539cac4e3b7e031caa9fd987456b3c#diff-f74ffe5487d96b60a7cd15d69b9f07acR66):

```
        protected override void Append(StringBuilder builder, LogEventInfo logEvent)
        {
            HttpContext context = HttpContext.Current;
            if (context == null)
            {
                return;
            }

            if (context.Request == null)
            {
                return;
            }
```

**Comment by 304NotModified** [comment]
Hi,

this is a duplicate of https://github.com/NLog/NLog.Web/issues/31?

We cannot check, without exception, if its available.

You need to set throwExceptions=false

**Comment by vegar** [comment]
Yes. Sorry about that. I tried to browse for existing issue, but didn't recognize it.

Setting `throwExceptions=false` can potentially hide other problems, though. Can it not?

Since it's an known issue with the .net framework (throwing on property getter), it could be an option to wrap it in a try catch, don't you think?

**Comment by 304NotModified** [comment]
Well it's in a try-catch, but rethrown when `throwExceptions=true` ;)


> Setting throwExceptions=false can potentially hide other problems, though. Can it not?

yes, but for production env `throwExceptions=false` is recommend.
