### ISSUE TITLE
NLog ignores config file location in .NET Core 3.1 Windows Service

### ISSUE THREAD

**Issue by toddheckel** [NLog/NLog.Web#571]
**Type**: Bug

**NLog version**: 4.7.2

**NLog.Web/NLog.Web.AspNetCore version**: 4.9.2

**NLog.Extensions.Logging version**: N/A

**Platform**: .NET Core 3.1

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        autoReload="true"
        internalLogLevel="Warn"
        internalLogFile="internal.txt">
  <extensions>
    <!--enable NLog.Web for ASP.NET Core-->
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <!-- define various log targets -->
  <targets>
    <target xsi:type="File"
            name="allOutput"
            fileName="${startupdir}\logs\SkyJack-Agent-All-${shortdate}.log"
            layout="${longdate} ${logger} ${uppercase:${level}} ${message} ${exception}" />
    <target xsi:type="File"
            name="ourOutput"
            fileName="${startupdir}\logs\SkyJack-Agent-OurOutput-${shortdate}.log"
            layout="${longdate} ${logger} ${uppercase:${level}} ${message} ${exception}" />
    <target xsi:type="File"
            name="errorsOnly"
            fileName="${startupdir}\logs\SkyJack-Agent-ErrorsOnly-${shortdate}.log"
            layout="${longdate} ${logger} ${uppercase:${level}} ${message} ${exception}" />
    <target name="console" xsi:type="ColoredConsole" layout="${longdate} ${pad:padding=5:inner=-${level}-} ${message}"
                useDefaultRowHighlightingRules="false" >
      <highlight-row condition="level==LogLevel.Trace" foregroundColor="Gray" />
      <highlight-row condition="level==LogLevel.Debug" foregroundColor="DarkGray" />
      <highlight-word text="-Info-"  foregroundColor="DarkGreen" />
      <highlight-word text="-Warn-"  foregroundColor="DarkYellow" />
      <highlight-word text="-Error-"  foregroundColor="DarkMagenta" />
      <highlight-word text="-Fatal-"  foregroundColor="DarkRed" backgroundColor="White"/>
    </target>
  </targets>
  
  <rules>
    <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Debug" writeTo="console" />
    <logger name="*" minlevel="Trace" writeTo="allOutput" />
    <logger name="*" minlevel="Error" writeTo="errorsOnly" />    

    <!--Skip Microsoft logs - no writeTo attribute-->
    <logger name="Microsoft.*" minlevel="Trace" final="true" />
    <logger name="*" minlevel="Trace" writeTo="ourOutput" />
  </rules>
</nlog>
```
I am using NLog in a .NET Core web service published as single file and attempting to install it as a service. NLog works fine when I run it normally, however when running as a service it needs to be told where to find the config file, which I am accomplishing with:
```c#
            var pathToExe = Process.GetCurrentProcess().MainModule.FileName;
            var pathToContentRoot = Path.GetDirectoryName(pathToExe);

            NLog.LogManager.Configuration = new NLog.Config.XmlLoggingConfiguration(Path.Combine(pathToContentRoot, "nlog.config"));
            var logger = NLog.Web.NLogBuilder.ConfigureNLog(NLog.LogManager.Configuration).GetCurrentClassLogger();
```
And the content root with:
```
                builder.UseWindowsService().UseContentRoot(pathToContentRoot);
```
This appears to work, at least at first, and generates some log output, enough to see that I am setting the content root successfully:
```
2020-05-28 15:42:20.5932 SkyJack.Agent.Program INFO ... Initializing SkyJack Agent with content root G:\MSGPS2\SkyJack\SkyJack\src\SkyJack.Agent\bin\Release\netcoreapp3.1\publish... 
2020-05-28 15:42:20.6373 SkyJack.Agent.Program TRACE Entering CreateWebHostBuilder() 
2020-05-28 15:42:20.8023 SkyJack.Agent.Program TRACE Returned from CreateWebHostBuilder() 
2020-05-28 15:42:20.8023 SkyJack.Agent.Program TRACE Entering builder.Build() 
2020-05-28 15:42:20.9446 SkyJack.Agent.Program TRACE Returned from builder.Build() 
```
Eventually, however, it throws an exception:
```
Log Name:      Application
Source:        ServerManagerAgent
Date:          5/28/2020 3:54:04 PM
Event ID:      6
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      HPZEE.redmond.corp.microsoft.com
Description:
Category: Microsoft.AspNetCore.Hosting.Diagnostics
EventId: 6

Application startup exception

Exception: 
System.IO.FileNotFoundException: Failed to load NLog LoggingConfiguration. Searched the following locations:
- C:\WINDOWS\TEMP\.net\ServerManagerAgent\31dyvwga.rkl\nlog.config

File name: 'nlog.config'
   at NLog.LogFactory.LoadConfiguration(String configFile, Boolean optional)
   at NLog.LogFactory.LoadConfiguration(String configFile)
   at NLog.LogManager.LoadConfiguration(String configFile)
   at NLog.Web.NLogBuilder.ConfigureNLog(String configFileName)
   at WebAppService.Startup.Configure(IApplicationBuilder app)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.Extensions.DependencyInjection.AutoRegisterMiddleware.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ServerManagerAgent" />
    <EventID Qualifiers="0">6</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-05-28T22:54:04.0041305Z" />
    <EventRecordID>61154</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>HPZEE.redmond.corp.microsoft.com</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Category: Microsoft.AspNetCore.Hosting.Diagnostics
EventId: 6

Application startup exception

Exception: 
System.IO.FileNotFoundException: Failed to load NLog LoggingConfiguration. Searched the following locations:
- C:\WINDOWS\TEMP\.net\ServerManagerAgent\31dyvwga.rkl\nlog.config

File name: 'nlog.config'
   at NLog.LogFactory.LoadConfiguration(String configFile, Boolean optional)
   at NLog.LogFactory.LoadConfiguration(String configFile)
   at NLog.LogManager.LoadConfiguration(String configFile)
   at NLog.Web.NLogBuilder.ConfigureNLog(String configFileName)
   at WebAppService.Startup.Configure(IApplicationBuilder app)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.&lt;&gt;c__DisplayClass4_0.&lt;Build&gt;b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.&lt;&gt;c__DisplayClass13_0.&lt;UseStartup&gt;b__2(IApplicationBuilder app)
   at Microsoft.Extensions.DependencyInjection.AutoRegisterMiddleware.&lt;&gt;c__DisplayClass4_0.&lt;Configure&gt;b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.&lt;&gt;c__DisplayClass0_0.&lt;Configure&gt;g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.&lt;&gt;c__DisplayClass0_0.&lt;Configure&gt;b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
</Data>
  </EventData>
</Event>
```
WebAppService.Startup.Configure() is calling NLog.Web.NLogBuilder.ConfigureNLog() again, presumably with just "nlog.config" instead of the location or LoggerConfiguration object that I passed in to begin with.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? No
- Are there any workarounds? No
- Is there a version in which it did work? No
- Can you help us by writing an unit test? Possibly

**Comment by toddheckel** [comment]
I was able to get it to work using:
```c#
            NLog.LogManager.LogFactory.SetCandidateConfigFilePaths(new List<string> { $"{Path.Combine(pathToContentRoot, "nlog.config")}" });
            var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
```

**Comment by 304NotModified** [comment]
I guess this is still a bug?

**Comment by toddheckel** [comment]
Works for me!

**Comment by Larry57** [comment]
I have not looked at the NLog code yet, but I bumped into the same issue.
Reading at the [MS documentation](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.1&tabs=visual-studio), I notice that some specifics have to be applied: UseWindowsService() works together with the new File Providers abstractions to help dealing with the root folder of an application (which is windows\system32 when it runs as a service).
I do not known how the NLog AspNetCore Web extensions are dealing with this yet.

**Comment by toddheckel** [comment]
There seems to be a bug in .NET Core 3.1 with the content root when single file publish and running as a service. When not running as a service, .NET sets the content root to the location of the main executable, whether or not you are using single file publish. When running as a service, it sets the content root to the temp folder where the extracted files are located. We "fix" this by forcing the content root to the expected location; however, we can not do this before nlog is loaded so we have to manually point nlog to the correct location, using a method that works for when we configure nlog, as well as when it is configured internally by WebAppService.Startup.Configure(). I will file a bug with the .NET Core team when I have a chance.

**Comment by 304NotModified** [comment]
Ow is this single file publish? This could be a duplicate or at least related: https://github.com/NLog/NLog/issues/3517

**Comment by toddheckel** [comment]
That issue is probably related and likely caused by the same .NET Core issue I described above.

This issue is ultimately about the fact that if you explicitly configure NLog in Main(), it will still be configured again in WebAppService.Startup.Configure(). That's usually okay since it will ordinarily load the same config file, but if you run as a single file published Windows service it will load two different config files, so you have to explicitly point NLog to the "correct" place to find the config file by calling SetCandidateConfigFilePaths() in Main(). It's arguably a workaround if you think WebAppService should just use the configuration you've already loaded.

**Comment by toddheckel** [comment]
Referring to the other issue you linked, I think underlying issue with the content root when using single file publish was fixed, but only when not running as a Windows service.

**Comment by 304NotModified** [comment]
Thanks for the feedback. 

Unfortunately I haven't found time to create and debug a small demo for this issue. (just started a new job)

**Comment by toddheckel** [comment]
Also, looking at the NLog documentation for .NET Core apps versus some other examples, I'm seeing conflicting ways to configure NLog in .NET Core. Should we be calling:
```c#
NLogBuilder.ConfigureNLog("nlog.config")
```
or
```c#
builder.AddNLog("nlog.config")
```

**Comment by toddheckel** [comment]
I'm creating a repro of the underlying .NET Core issue right now; unfortunately they want you to write one and deploy it to github before filing a bug.

**Comment by 304NotModified** [comment]
> Should we be calling:

If you mean, ILoggerFactory.AddLog, that one is obsolete. 

```
#if !NETCORE1_0
        [Obsolete("Instead use ILoggingBuilder.AddNLog() or IHostBuilder.UseNLog()")]
#endif
        public static ILoggerFactory AddNLog(this ILoggerFactory factory)
        {
            return factory.AddNLog(NLogProviderOptions.Default);
        }
```

**Comment by toddheckel** [comment]
Okay this turned out to be a bug on our side, someone else had added an explicit call to ConfigureNLog() in Startup.Configure() which was causing the exception I reported above (I didn't recognize the namespace used for our web app since it sounds so... generic).

I did end up filing a bug on the content root issue when running a .NET Core web app as a service: [https://github.com/dotnet/aspnetcore/issues/22636](url).

**Comment by 304NotModified** [comment]
Thanks for the feedback!

**Comment by toddheckel** [comment]
You bet!

**Comment by Larry57** [comment]
The workaround described here works correctly when logging in files, however, NLog continues to write its internal logs in system32 folder using the internalLogFile parameter.

For example, in here, I end up having c:\windows\system32\logs\internal-logs.txt

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Info"
      internalLogFile="logs\internal-nlog.txt">

**Comment by snakefoot** [comment]
@Larry57 NLog InternalLogger LogToFile uses current directory by default, and it would be a breaking-change to change this.

Newer versions of NLog has support for simple layout-renderer without any options:

- NLog 4.6+: Environment Variables are also supported: e.g. %appdata%
- NLog 4.6+: Supports renderers (without options): ${currentdir}, ${basedir}, ${tempdir}
- NLog 4.7.1+: Supports renderer (without options): ${processdir} 

See also: https://github.com/NLog/NLog/wiki/Internal-Logging
