### ISSUE TITLE
Drop support ASP.NET Core 1

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#575]
Maybe good. But of course it depends when V5 will be there

**Comment by snakefoot** [comment]
Make sense to drop NetCore1 from NLog.Web.AspNetCore since NetCore1 Apps has reached EOL:

https://devblogs.microsoft.com/dotnet/net-core-1-0-and-1-1-will-reach-end-of-life-on-june-27-2019/

Not sure if NLog and NLog.Extensions.Logging should also be dropping their support.

**Comment by snakefoot** [comment]
Should probably also bump NetCore3 to NetCore31 instead of build-warnings about NetCore30 no longer being supported.

**Comment by 304NotModified** [comment]
> Should probably also bump NetCore3 to NetCore31 instead of build-warnings about NetCore30 no longer being supported.

--> https://github.com/NLog/NLog.Web/issues/684
