### ISSUE TITLE
Support such as aspnet-request-routeParameter

### ISSUE THREAD

**Issue by EzrealJ** [NLog/NLog.Web#576]
Are there plans to support features  such as aspnet-request-routeparameter （like aspnet-request-querystring), or had been related implementation

**Comment by 304NotModified** [comment]
No plans, but PR would be great

Only we have to think of the names a current related renders are with the name "mvc" (and not sure if they all work on APIs.) See https://nlog-project.org/config/?tab=layout-renderers&search=Mvc

 I'm a aware the hard distinction between API and mvc is gone these days.

**Comment by 304NotModified** [comment]
If you have the c# call, than it would be probably easy to implement!

**Comment by EzrealJ** [comment]
Sorry i didn't reply in time, I have implemented it (just like AspNetQueryStringLayoutRenderer.cs), but I don’t have an overall understanding of the project, and I don’t have enough time for extreme testing,So, no PR

**Comment by 304NotModified** [comment]
Maybe share the code here? That could help others in the up for grabs.

**Comment by EzrealJ** [comment]
it looks like ...
```C#
public class AspNetRequestRouteParameterRenderer : AspNetLayoutMultiValueRendererBase
    {
        public List<string> RouteParameterKeys { get; set; }
        protected override void DoAppend(StringBuilder builder, LogEventInfo logEvent)
        {
            
            Microsoft.AspNetCore.Http.HttpRequest httpRequest = HttpContextAccessor.HttpContext.Request;
            if (httpRequest == null)
            {
                return;
            }

            bool printAllRouteParameter = this.RouteParameterKeys == null || this.RouteParameterKeys.Count == 0;
            List<string> routeParameterKeys = this.RouteParameterKeys;
            RouteValueDictionary routeParameters = httpRequest.RouteValues;
            if (routeParameters == null || routeParameters.Count == 0)
            {
                return;
            }

            if (printAllRouteParameter)
            {
                routeParameterKeys = routeParameters.Keys.ToList();
            }
            IEnumerable<KeyValuePair<string, string>> pairs = GetPairs(routeParameters, routeParameterKeys);
            SerializePairs(pairs, builder, logEvent);
        }

        private static IEnumerable<KeyValuePair<string, string>> GetPairs(RouteValueDictionary routeParameters, List<string> routeParameterKeys)
        {
            foreach (string key in routeParameterKeys)
            {
                // This platoform specific code is to prevent an unncessary .ToString call otherwise. 

                if (!routeParameters.TryGetValue(key, out object objValue))
                {
                    continue;
                }
                string value = objValue.ToString();
                if (!string.IsNullOrEmpty(value))
                {
                    yield return new KeyValuePair<string, string>(key, value);
                }
            }
        }

    }
```

**Comment by 304NotModified** [comment]
Thanks!

**Comment by ThomasArdal** [comment]
@304NotModified Only looked through this quickly. But route values aren't MVC specific, right? I mean, it wouldn't make much sense (IMO) to name this `aspnet-mvc-routeparameters` or something similar with the `mvc` in there? As I understand route values they are applicable for other types of applications too. Like a Razor pages app would have a route value named `page`, etc.

**Comment by 304NotModified** [comment]
With asp.net core it isn't MVC specific indeed.

**Comment by 304NotModified** [comment]
Thanks @ThomasArdal !
