### ISSUE TITLE
aspnet-request vars are empty in ASPNET Core 3.1 API

### ISSUE THREAD

**Issue by jchapmantcg** [NLog/NLog.Web#584]
**Type**: Question/Bug
- All other vars like ${message} work, only the aspnet-request ones do not.

**NLog version**: 4.7.2

**NLog.Web.AspNetCore version**: 4.9.2

**NLog.Extensions.Logging version**: N/A

**Platform**: .NET Core 3.1

**Current NLog config** (xml or C#, if relevant)

```var config = new LoggingConfiguration();

// Console
config.AddTarget(new ConsoleTarget("logconsole"));

// Papertrail
var paperTrail = new SyslogTarget();
paperTrail.Name = "PaperTrail";
paperTrail.MessageCreation.Facility = NLog.Targets.Syslog.Settings.Facility.Local7;
paperTrail.MessageCreation.Rfc5424.AppName = "TESTAPP";
paperTrail.MessageSend.Protocol = NLog.Targets.Syslog.Settings.ProtocolType.Tcp;
paperTrail.MessageSend.Tcp.Server = "xxxxxxx";
paperTrail.MessageSend.Tcp.Port = xxxxxx;
paperTrail.MessageSend.Tcp.Tls = new NLog.Targets.Syslog.Settings.TlsConfig { Enabled = true };
paperTrail.Layout = "${uppercase:${level}}|${aspnet-Request-Method}|${aspnet-request-url:IncludeQueryString=true}|${message}|${exception:format=tostring}";
config.AddTarget(paperTrail);

config.AddRuleForAllLevels("PaperTrail");


_logger = NLogBuilder.ConfigureNLog(config).GetCurrentClassLogger();
```

In case of a BUG:

- What is the current result?
All ${aspnet-request-xxxx} vars are empty

- What is the expected result?
Values to be valid

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes. It did not show anything related.

- Are there any workarounds? yes/no
Not that I'm aware of.

- Is there a version in which it did work? 
No.

- Can you help us by writing an unit test?
Yes.

**Comment by snakefoot** [comment]
When #540 is merged and released, then things will get easier.

**Comment by jchapmantcg** [comment]
@snakefoot This produced the same results.

**Comment by snakefoot** [comment]
@jchapmantcg The `${aspnet-Request}` will only work after you have setup the service-locator using `AddNLog` or `UseNLog`.

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
      .ConfigureWebHostDefaults(webBuilder =>
      {
          webBuilder.UseStartup<Startup>();
      })
      .ConfigureLogging(logging =>
      {
          logging.ClearProviders();
          logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
      })
      .UseNLog();  // NLog: Setup NLog for Dependency injection (Make ${aspnet-Request} work)
```

**Comment by jchapmantcg** [comment]
This is what I was missing! Thanks @snakefoot
