### ISSUE TITLE
Update docs for 4.9.3

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#589]
- [x] #570

**Comment by snakefoot** [comment]
Maybe wait for NLog 4.7.3 so https://github.com/NLog/NLog/pull/3999 is merged and an updated NLog.Extensions.Logging ver. 1.6.5 can be made that fixes the [todo](https://github.com/NLog/NLog.Extensions.Logging/blob/3c64a51328ace81efa2a6a0696926a29a53a7261/src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs#L87).

**Comment by 304NotModified** [comment]
Is this a hint for NLog 4.7.3? ;)

**Comment by snakefoot** [comment]
Not in a hurry. Just thought it would be nice to bump all when making the NLog.Web v4.9.3 release. Right now all is pure maintenance release, since no major bugs.

**Comment by snakefoot** [comment]
Now https://github.com/NLog/NLog.Extensions.Logging/pull/444 is ready for NLog.Web 4.9.4
