### ISSUE TITLE
NLog logged message in database does not contain exception details

### ISSUE THREAD

**Issue by MattKalafut** [NLog/NLog.Web#594]
**Type:** Question
**NLog Version:** 4.7.2
```xml
    <PackageReference Include="NLog" Version="4.7.2" />
    <PackageReference Include="NLog.Extensions.Logging" Version="1.6.4" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.9.2" />
```
**Platform:** ASP.NET Core 2.2
**Current NLog Config**
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwConfigExceptions="true"
      internalLogLevel="Trace"
      internalLogFile="c:\temp\internal-nlog.txt">

  <!-- enable asp.net core layout renderers -->
  <extensions>
    <add assembly="NLog.Extensions.Logging"/>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <!-- the targets to write to -->
  <targets>
    <!-- write logs to file  -->
    <target xsi:type="File" name="allfile" fileName="c:\temp\nlog-all-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}" />

    <!-- another file log, only own logs. Uses some ASP.NET core renderers -->
    <target xsi:type="File" name="ownFile-web" fileName="c:\temp\nlog-own-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}" />

    <target name="databaseLogger" xsi:type="Database"
          dbProvider="sqlserver"
          dbHost="${configsetting:AppSettings.NlogConnection.DbHost}"
          dbDatabase="${configsetting:AppSettings.NlogConnection.Database}"
          dbUserName="${configsetting:AppSettings.NlogConnection.User}"
          dbPassword="${configsetting:AppSettings.NlogConnection.Password}">

      <commandText>
        insert into dbo.Log (
        CorrelationId, Application, UserName, Logged, Level, Message,
        Logger, CallSite, Exception
        ) values (
        @CorrelationId, @Application, @UserName, @Logged, @Level, @Message,
        @Logger, @Callsite, @Exception
        );
      </commandText>
      <parameter name="@correlationId" layout="${aspnet-traceidentifier}" />
      <parameter name="@application" layout="${configsetting:AppSettings.NlogConnection.AppName}" />
      <parameter name="@UserName" layout="${aspnet-user-identity}" />
      <parameter name="@logged" layout="${date}" />
      <parameter name="@level" layout="${level}" />
      <parameter name="@message" layout="${message}" />
      <parameter name="@logger" layout="${logger}" />
      <parameter name="@callSite" layout="${callsite:filename=true}" />
      <parameter name="@exception" layout="${exception:tostring}" />
    </target>

  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <!--Skip non-critical Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" levels="Warn, Error, Fatal" writeTo="databaseLogger"></logger>
    <logger name="Microsoft.*" minLevel="Trace" final="true" />

    <!--All logs, including from Microsoft unless suppressed (which I do, above)-->
    <logger name="*" minlevel="Trace" writeTo="allfile" />
    <logger name="*" minlevel="${configsetting:AppSettings.NlogConnection.LogLevel" writeTo="databaseLogger" />
    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />
  </rules>
</nlog>
```

Following the ASP.NET Core 2 startup documentation I created the following example code forcing an error to test this out (the commented out code is what gave me the first message in the screenshot).
**Program.cs**
```c#
public class Program
{
    public static void Main(string[] args)
    {
        // NLog: setup the logger first to catch all errors
        var logger = NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
        try
        {
            // These messages are found in the nlog-all-{today} text file
            logger.Debug("init main");
            CreateWebHostBuilder(args).Build().Run();
        }
        catch (Exception ex)
        {
            //NLog: catch setup errors
            logger.Error(ex, "Stopped program because of exception");
            throw;
        }
        finally
        {
            // Ensure to flush and stop internal timers/threads before application-exit
            NLog.LogManager.Shutdown();
        }
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>()
            .ConfigureLogging(logging =>
            {
                logging.ClearProviders();
                // The Logging configuration specified in appsettings.json overrides any call to SetMinimumLevel.
                logging.SetMinimumLevel(LogLevel.Trace);
            })
            .UseNLog();  // NLog: setup NLog for Dependency injection
}
```
**ClientController.cs**
```
public class ClientController : Controller
{
     private readonly ILogger<ClientController> _logger;

     public ClientController(ILogger<ClientController> Logger)
     {
         _logger = Logger;
     }

     [HttpGet]
     public IActionResult Index()
     {
         //_logger.Log(LogLevel.Debug, "Client Controller Index hit");
         //return View();
         Exception ex = new Exception("Example Exception Message");
         _logger.LogError(ex.Message, ex.InnerException);
         throw ex;
      }
...
```
Logger messages in SQL

![image](https://user-images.githubusercontent.com/4413605/89044709-f5cc5280-d30f-11ea-80c7-d8aa32b1c18b.png)

I have explicitly set up the config to allow Warn, Error & Fatal messages on Microsoft's end to come through the log but when I create views to gain application log insights later, I only want to see the messages from my logging - not Microsoft's.  However, the expected result would be that I could write a ```_logger.LogError("Foo", ex.InnerException)``` and see the Message field contain "foo" and my Exception field have the actual exception details within SQL.

Is there something I'm missing here?

**Comment by 304NotModified** [comment]
You need to send the Exception separate,

e.g.

```c#
   _logger.LogError(ex, "Exception when doing....");
```

See also https://github.com/nlog/nlog/wiki/How-to-log-exceptions (this is for the NLog logger, but the same applies for the NLog.Extensions.Logging)

**Comment by MattKalafut** [comment]
D'oh.. I was trying it in reverse by sending the message before the exception in my earlier tests... Thanks so much for the help @304NotModified

**Comment by MattKalafut** [comment]
@304NotModified I guess this may warrant its own specific question but the documentation is not that clear from what I have seen on the differences (both in functionality and setup) between an NLog logger versus the NLog.Extensions logger.  Or if that documentation exists I have not been able to find it?

Because I actually tried setting up an NLog logger that used the ```GetCurrentClassLogger``` way and it did not work for me.  Some of the documentation provides examples from one, and some from the other but it's never really made explicitly clear.

**Comment by 304NotModified** [comment]
> @304NotModified I guess this may warrant its own specific question but the documentation is not that clear from what I have seen on the differences (both in functionality and setup) between an NLog logger versus the NLog.Extensions logger. Or if that documentation exists I have not been able to find it?

There is some, but it hard to find a place where to place it. Also there is a lot of documentation on Microsoft's side.
I've wrote a stackoverflow post in the past on this, hope that make things clear: https://stackoverflow.com/questions/58209076/microsoft-extensions-logging-vs-nlog

**Comment by MattKalafut** [comment]
Okay perfect, so it's not just me then.  Yeah I've read that Microsoft page - very useful.  I will take a look at your SO question and bookmark it.  Thanks again for setting me straight with this issue!  I'll go ahead and close it.

**Comment by 304NotModified** [comment]
Please let me know if you know a good place would be to explain this. :)

**Comment by MattKalafut** [comment]
I would think maybe just its own page on the wiki or the documentation to explain the differences, pros & cons and kind of condense some of the info from your StackOverflow answer and some other useful bits of information on the subject.  Just something to kind of connect all the dots since some examples in the docs show the NLog (non-DI way) and some show the Microsoft.Extensions.Logging way and it's not really made clear that there's even a difference.

For now I just went through and did a bunch of trial and error and figured out some things in a scratch application and took down some of my own notes for later, but at least now knowing that some of the documentation is written with one way in mind and some is the other.  

I do definitely think it's worthwhile to have a page _somewhere_ on the topic even if it's just its own page in the documentation on the side nav.

**Comment by 304NotModified** [comment]
OK thanks, I've created a new issue for this, so we could close this one: NLog/NLog.Extensions.Logging#443
