### ISSUE TITLE
Using NLog from within a class library?

### ISSUE THREAD

**Issue by MattKalafut** [NLog/NLog.Web#601]
I just want to quickly clarify that the reason I'm posting this here and not on StackOverflow is that this is not so much an "ask-and-answered" question and some of what I ask will be opinion-based - both of which go against the StackOverflow format.

**Type**: Question

**NLog version**: 4.7.2

**NLog.Web/NLog.Web.AspNetCore version**: 4.9.2

**NLog.Extensions.Logging version**: 1.6.4

**Platform**: .NET Core 2 

**Current NLog config** (xml or C#, if relevant)

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwConfigExceptions="true"
      internalLogLevel="Debug"
      internalLogFile="c:\temp\internal-nlog.txt">

  <!-- enable asp.net core layout renderers -->
  <extensions>
    <add assembly="NLog.Extensions.Logging"/>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <!-- the targets to write to -->
  <targets>
    <!-- write logs to file  -->
    <target xsi:type="File" name="allfile" fileName="c:\temp\nlog-all-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}" />

    <!-- another file log, only own logs. Uses some ASP.NET core renderers -->
    <target xsi:type="File" name="ownFile-web" fileName="c:\temp\nlog-own-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}" />

    <!-- write to the void aka just remove -->
    <target xsi:type="Null" name="blackhole" />

    <target name="databaseLogger" xsi:type="Database"
          dbProvider="sqlserver"
          dbHost="${configsetting:AppSettings.NlogConnection.DbHost}"
          dbDatabase="${configsetting:AppSettings.NlogConnection.Database}"
          dbUserName="${configsetting:AppSettings.NlogConnection.User}"
          dbPassword="${configsetting:AppSettings.NlogConnection.Password}">

      <!--<target name="databaseLogger" xsi:type="Database" connectionString="${configsetting:AppSettings.NlogConnection.AppLogsConnectionString}">-->

      <commandText>
        insert into dbo.Log (
        CorrelationId, Application, UserName, Logged, Level, Message,
        Logger, CallSite, Exception
        ) values (
        @CorrelationId, @Application, @UserName, @Logged, @Level, @Message,
        @Logger, @Callsite, @Exception
        );
      </commandText>
      <parameter name="@correlationId" layout="${aspnet-traceidentifier}" />
      <parameter name="@application" layout="${configsetting:AppSettings.NlogConnection.AppName}" />
      <parameter name="@UserName" layout="${aspnet-user-identity}" /><!--https://github.com/NLog/NLog/issues/2772-->
      <parameter name="@logged" layout="${date}" />
      <parameter name="@level" layout="${level}" />
      <parameter name="@message" layout="${message}" />
      <parameter name="@logger" layout="${logger}" />
      <parameter name="@callSite" layout="${callsite:filename=false}" />
      <parameter name="@exception" layout="${exception:toString}" />
    </target>

  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <!--Skip non-critical Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" levels="Warn, Error, Fatal" writeTo="databaseLogger"></logger>
    <logger name="Microsoft.*" minLevel="Trace" final="true" />
    
    <!--All logs, including from Microsoft unless suppressed (which I do, above)-->
    <logger name="*" minlevel="Trace" writeTo="allfile" />
    <logger name="*" minlevel="${configsetting:AppSettings.NlogConnection.LogLevel" writeTo="databaseLogger" />
    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />
  </rules>
</nlog>
```

I've [requested](https://github.com/NLog/NLog.Extensions.Logging/issues/443) additional documentation to be provided regarding the differences (both in functionality and setup) between the different NLog settings (One that uses NLog and one that uses Microsoft.Extensions.Logging) and I expect that the answer to this question will be somewhat related to that issue as well.

As it stands I've followed the [.NET Core 2 Startup Guide](https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-2) and have a working logging solution from within my web project that utilizes Microsoft.Extensions.Logging to inject an `ILogger<ClassName>` into the controller constructor of each web controller I've got.

I went ahead and tried doing the same thing in my class library to see what would happen - so I included Microsoft.Extensions.Logging and injected another `ILogger<ClassName>` into the constructor of a service class of mine and without any additional setup I was getting logging messages in the database and file targets in compliance with my NLog.config file (located in a separate project in the solution).  There are no references to NLog, no NuGet packages being included, no additional config or mention of NLog anywhere in this project.  Only Microsoft.Extensions.Logging.

So while this works, I'm not really sure why and would like to understand before proceeding forward.  

**So my questions are:** 

1. Why does this work?  My main points of confusion come from the fact that it's logging to the correct targets even though there's no mention or reference to my NLog config anywhere in this project (although they do share a solution [so maybe that's enough?](https://github.com/nlog/NLog/wiki/Configuration-file#configuration-file-locations)).
2. Is there a better way of doing this than what I've done above?  I want to know any pitfalls about what I've done or any better / safe / easier ways of doing it if any are possible.  Especially since as it stands it seems like NLog isn't really even a factor in this project and I'm relying solely on the Microsoft logger.
3. If I was using the `using NLog;` rather than `using Microsoft.Extensions.Logging;`, how does this process of logging from a class library differ?  What additional setup would be required?

**Comment by snakefoot** [comment]
> Why does this work?

When you acquire `ILogger` from Microsoft Extension Logging (MEL) then you get it from the host-application-dependency-injection-container (servicecollection / serviceprovider). When you use `ILogger` for logging then you are writing into the MEL-engine. MEL-engine allows you to redirect the output any kind of registered logging-provider. When calling `UseNLog` / `AddNLog` then you register NLog as logging-provider in MEL. 

Because all class-libraries loaded by the host-application is sharing the same dependency-injection-container, then all class-libraries gets an `ILogger`-instance that are configured to use the same MEL-engine-instance (and the same registered logging-providers like NLog).

> Is there a better way of doing this than what I've done above? 

No it is perfectly okay make use of the MEL `ILogger`.

> If I was using the using NLog; rather than using Microsoft.Extensions.Logging;, how does this process of logging from a class library differ? What additional setup would be required?

Many feel it generates clutter to pass the `ILogger` as constructor-parameter, and prefer just doing this:

```c#
class Hello
{
    private static NLog.Logger Log = NLog.LogManager.GetCurrentClassLogger();
}
```

But when you use it as constructor-parameter then it possible to have multiple host-application-services each with their own dependency-injection-container but running within the same process.

**Comment by 304NotModified** [comment]
> But when you use it as constructor-parameter then it possible to have multiple host-application-services each with their own dependency-injection-container but running within the same process.

And it's easier to unit test the logger (of course one of the main benefits of DI)

**Comment by MattKalafut** [comment]
@snakefoot @304NotModified 

Thank you both for the explanation and information.  Very insightful and helpful!

**Comment by snakefoot** [comment]
Closing this issue as resolved.
