### ISSUE TITLE
Extend example to include support for Lifetime Startup Messages

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.Web#615]
We have already recognized it is important to perform logging of **Lifetime Startup Messages**:

https://github.com/NLog/NLog.Web/wiki/Hosting-Lifetime-Startup-Messages

But the [example code](https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-3) is this:

```
      .ConfigureLogging(logging =>
      {
          logging.ClearProviders();   // Removes the default console-logger
          logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
      })
```

And the Nlog.config contains these rules:

```
  <rules>
    <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Trace" writeTo="allfile" />

    <!--Skip non-critical Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" maxlevel="Info" final="true" /> <!-- BlackHole without writeTo -->
    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />
  </rules>
```

Maybe ConsoleTarget with Microsoft-Logger should be added to NLog.config in the tutorial, so **Lifetime Startup Messages** will work out of the box with NLog.

**Comment by 304NotModified** [comment]
Good idea :)
