### ISSUE TITLE
Fix possible deadlock issue with AspNetLayoutRendererBase.Register

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.Web#632]
`RetrieveHttpContextAccessor` is a dangerous method, and should not be called frequently, because it can introduce deadlocks. See also: https://github.com/NLog/NLog/issues/2064

Instead one should create a new class `FuncAspNetLayoutRenderer`, that can hold the func-delegate and perform caching of `HttpContextAccessor`.

**Comment by snakefoot** [comment]
Could at the same time suppress `ObjectDisposedException` when logging outside-request-scope. See also: #630

**Comment by 304NotModified** [comment]
We need to change things in NLog for this.

- it should be possible to register FuncLayoutRenderer (or a like)
- FuncLayoutRenderer.RenderMethod method should be settable (protected) and a protected ctor without this method is needed.

Another option is to copy FuncLayoutRenderer, but then you're missing IStringValueRenderer for example and coping code is never really nice (e.g. FormatAsJson)

Also...

- I don't know why FuncLayoutRenderer.RenderMethod is public

**Comment by snakefoot** [comment]
I prefer just to make an internal class in Nlog.Web that takes the input method as constructor parameter.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


We need to change things in NLog for this.

  *   it should be possible to register FuncLayoutRenderer (or a like)
  *   FuncLayoutRenderer.RenderMethod method should be settable (protected) and a protected ctor without this method is needed.

Another option is to copy FuncLayoutRenderer, but then you're missing IStringValueRenderer for example and coping code is never really nice (e.g. FormatAsJson)

Also...

  *   I don't know why FuncLayoutRenderer.RenderMethod is public

**Comment by 304NotModified** [comment]
Yes, but we still need the changes in NLog itself ;)

**Comment by snakefoot** [comment]
Why?


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Yes, but we still need the changes in NLog itself ;)

**Comment by snakefoot** [comment]
Maybe something like this:
```c#
internal class NLogWebLayoutRenderer : FunctionLayoutRenderer
{
     Func<LogEventInfo, HttpContextBase, LoggingConfiguration, object> _func;

     private IHttpContextAccessor HttpContextAccessor { get; set; }   // TODO Missing implementation

     public NLogWebLayoutRenderer(string name, Func<LogEventInfo, HttpContextBase, LoggingConfiguration, object> func)
         :base(name, (event, config) => LookupValue(event, config))
     {
         _func = func;
     }

     private object LookupValue(LogEventInfo logEvent, LoggingConfiguration config)
     {
          var httpContext = HttpContextAccessor?.HttpContext;
          return _func(logEvent, config, httpContext);
     }
}
```

**Comment by 304NotModified** [comment]
I will look into this :)

**Comment by 304NotModified** [comment]
LookupValue needs to be static then. And I don't think we like static "cache"

**Comment by snakefoot** [comment]
Then I guess FunctionLayoutRenderer has to be improved, by adding a new protected virtual method called RenderValue() that returns object.

Add some point this special implementation of FunctionLayoutRenderer will use `Resolve<T>` to lookup the HttpContext-accessor.

**Comment by 304NotModified** [comment]
yes indeed, see https://github.com/NLog/NLog/pull/4326 :)

**Comment by 304NotModified** [comment]
working on this
