### ISSUE TITLE
Add readme to package

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#638]
Maybe nice to add an readme to the package with the example nlog.config of nlog json settings.

See https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli#adding-a-readme-and-other-files

Also nice for NLog package itself.

**Comment by 304NotModified** [comment]
Related https://github.com/NLog/NLog/issues/3882

**Comment by 304NotModified** [comment]
@snakefoot what do you think? Do you think this will work for readme.md?  (and so not .txt)?

**Comment by snakefoot** [comment]
I think a link to a web-page is much more flexible.

**Comment by 304NotModified** [comment]
yes and a link in a .md is much nicer than a .txt :)
