### ISSUE TITLE
Add Additional Renderer for ${aspnet-request:serverVariable=remote_addr}

### ISSUE THREAD

**Issue by Page-Not-Found** [NLog/NLog.Web#65]
Add Additional Renderer for ${aspnet-request:serverVariable=remote_addr}

See below comments from #53 

https://github.com/NLog/NLog.Web/issues/53#issuecomment-234572686
https://github.com/NLog/NLog.Web/issues/53#issuecomment-234666110
https://github.com/NLog/NLog.Web/issues/53#issuecomment-234666689

**Comment by 304NotModified** [comment]
Fixed by 4.3
