### ISSUE TITLE
readme - usage for non-core sites?

### ISSUE THREAD

**Issue by timabell** [NLog/NLog.Web#67]
Hi, thanks for the library.

I'm a bit flummoxed how to use it with a normal asp.net mvc application rather than this new fangled core thing.

The instructions all seem to relate to core, could you assist?

**Comment by 304NotModified** [comment]
Good question. Its (too) easy in non core, just install the package from nuget. No code or config needed.  :)

**Comment by timabell** [comment]
Was about to do a pull request to make the readme clearer and now I see why I misunderstood - the heading "usage" is a subheading of "asp.net core" in the markdown, but the github rendering of headings makes the difference between 2nd and 3rd headings much too subtle.

**Comment by 304NotModified** [comment]
Thanks for the feedback! If you have a proposal to make it more clear, then please send a PR :)

**Comment by 304NotModified** [comment]
Ow you did already :)

**Comment by timabell** [comment]
:-)
