### ISSUE TITLE
Null processing for ${aspnet-session:Variable=User.Name:EvaluateAsNestedProperties=true}

### ISSUE THREAD

**Issue by worldofsites** [NLog/NLog.Web#69]
` Session["user"] = new UserInfo { Name= "johnDoe", Id = 100};` 
` layout="${aspnet-session:Variable=User.Name:EvaluateAsNestedProperties=true}"` 

I think there need to null check for Session["user"]. 
If object is not null, then try to read property of that object, else return.

From NLog.Web.Internal => PropertyReader => method GetPropertyInfo:
` return value.GetType().GetProperty(propertyName); // "value" can be null here`.
Thanks.

**Comment by UgurAldanmaz** [comment]
Thanks for your proposal. 

Did you try it with null value? If yes, what is the result?

**Comment by worldofsites** [comment]
Yes, sure, I tried with null value. And exception is:
`System.NullReferenceException in NLog.Web.Internal.PropertyReader.GetPropertyInfo(Object value, String propertyName)`
Also I tried that hack in config:
`${when:when=${aspnet-session:Variable=User}' != null:inner='${aspnet-session:Variable=User.Name:EvaluateAsNestedProperties=true}'}`
But to no avail

**Comment by UgurAldanmaz** [comment]
So null checking would be useful. But we need to check the side affects.

What do you tkink @304NotModified?

**Comment by 304NotModified** [comment]
I think this is the best approach: 

> I think there need to null check for Session["user"].
> If object is not null, then try to read property of that object, else return.

**Comment by UgurAldanmaz** [comment]
I just opened a bug fix issue for this, #70

@worldofsites,
By the way, you are trying to read `User.Name`
```
${when:when='${aspnet-session:Variable=User}' != null:inner='${aspnet-session:Variable=User.Name:EvaluateAsNestedProperties=true}'}
```
but it is actually `UserInfo`
```
Session["user"] = new UserInfo { Name= "johnDoe", Id = 100};
```

Is it just a typo in the issue or could it be the reason?

Thanks for reporting!

**Comment by worldofsites** [comment]
@UgurAldanmaz 
Key in session = "user", so => in config 'Variable' should "User".
And also it's just example. I tried with the real data with another session keys.

**Comment by UgurAldanmaz** [comment]
You are right. Sorry for my oversight.

**Comment by worldofsites** [comment]
@UgurAldanmaz @304NotModified 
Also, about ${aspnet-request}
Please check AspNetRequestValueLayoutRenderer.cs
`var httpRequest = HttpContextAccessor.HttpContext.TryGetRequest(); `
to 
`var httpRequest = HttpContextAccessor?.HttpContext?.TryGetRequest();`
like in AspNetRequestUrlRenderer.cs
Because all elements of the chain can be null. I tried that and can confirm.
Thanks.

**Comment by 304NotModified** [comment]
PS it's OK for me to move to VS2015 (C# 6)
