### ISSUE TITLE
Release NLog.Web.AspNetCore 4.3

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#71]
https://github.com/NLog/NLog.Web/pull/54

Needs https://github.com/NLog/NLog/pull/1439 (NLog 4.4)

**Comment by Arie-Kanarie** [comment]
First of all thanks for all the work you are doing! It works very nice.
But when will this version be released? I would like to use some of the new renderers in my ASP.NET Core project.
I prefer to use the NuGet package instead of pulling and building it locally.

**Comment by 304NotModified** [comment]
probably this week. Thanks for the kick :)

**Comment by 304NotModified** [comment]
It's waiting on tests. I could release a test package soon. Could you test it then? After that I will release a final version.

**Comment by 304NotModified** [comment]
done!
