### ISSUE TITLE
Remove Codecov integration

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#711]
Not used anymore. We use SonarCloud for showing the coverage

**Comment by bakgerman** [comment]
Is this change still desired?

**Comment by 304NotModified** [comment]
Yes this would be great to fix. 

The test_script in appveyor.yml needs to be cleaned.

**Comment by bakgerman** [comment]
There is a pull request for this now.

**Comment by 304NotModified** [comment]
Where?

**Comment by bakgerman** [comment]
https://github.com/NLog/NLog.Web/pull/897
