### ISSUE TITLE
Layout renderers missing when referencing from .NETStandard 1.6

### ISSUE THREAD

**Issue by mihaikanyaro** [NLog/NLog.Web#74]
Hi,

I've just created a new WebAPI project in Visual Studio 2015, Community Edition. I've then downloaded via NuGet the 4.2.4 version of NLog.Web.AspNetCore. I see only a part of the layout renderers that are supposed to be there. For example, AspNetRequestUrlRenderer  is missing. Have I missed something? 
![untitled](https://cloud.githubusercontent.com/assets/7837110/21076281/21589302-bf30-11e6-8e26-ee2b12cc2763.png)

**Comment by 304NotModified** [comment]
That's correct. That will be in NLog.web 4.3, which is waiting on the release of NLog 4.4 and the new beta of NLog 5

There is a dependency between them, which causes a release delay.

**Comment by mihaikanyaro** [comment]
Thanks for the swift answer! Any approximation of the release date?

**Comment by 304NotModified** [comment]
NLog 4.4 and 5.0 in a few days. NLog.web end of the week/next week.

**Comment by 304NotModified** [comment]
We could use some help for the NLog.web docs ;)

**Comment by mihaikanyaro** [comment]
Ha, got me with that one. Would've enjoyed popping my git cherry on this one, but I have some time consuming engagements, not considering my full time job. Keep up the good work!

**Comment by 304NotModified** [comment]
This is fixed with the release of NLog.Web / NLog.Web.AspNetCore 4.3 :)
