### ISSUE TITLE
Incorrect URL in NuGet Gallery

### ISSUE THREAD

**Issue by webmaniak** [NLog/NLog.Web#76]
Hi,

First of all, thank you for this awesome library!

I noticed an incorrect URL on the [NuGet gallery page of the NLog.Web](https://www.nuget.org/packages/NLog.Web) package. You can in fact find the incorrect link in the description for .NET Core version.

Wrong (referenced but obsolete) package: https://www.nuget.org/packages/NLog.Web.ASPNET5
What should be instead: https://www.nuget.org/packages/NLog.Web.AspNetCore

Best regards,
WebManiaK

**Comment by 304NotModified** [comment]
Thanks for the report !

When publishing the package, it was the correct link. Will update it soon.

**Comment by 304NotModified** [comment]
thanks, also current package has been updated
