### ISSUE TITLE
Configure/Setup programmatically

### ISSUE THREAD

**Issue by oscarjaergren** [NLog/NLog.Web#778]
How would one go about using this programmatically?

I don't like using the config files due to it being way easier to share code across programs using the C# code. 
+ It gives better IDE support and troubleshooting so therefore I don't have the NLOG config files in my projects. 

My biggest concern is how to add the Assembly?

**Comment by snakefoot** [comment]
You can do this with NLog 5.0:
```csharp
NLog.LogManager.Setup().LoadConfiguration(builder => {
   builder.ForLogger().FilterMinLevel(LogLevel.Info).WriteToConsole();
   builder.ForLogger().FilterMinLevel(LogLevel.Debug).WriteToFile(fileName: "file.txt");
});
```

**Comment by oscarjaergren** [comment]
I understand how to do it for the those other, writeToConsole and WriteToFile and have already successfully implemented those, but how do I add in the Web part of the project?

Nlog.Web?

**Comment by snakefoot** [comment]
```csharp
NLog.LogManager.Setup()
   .SetupExtensions(s =>s.RegisterAssembly("NLog.Web.AspNetCore"))
   .LoadConfiguration(builder => {
      builder.ForLogger().FilterMinLevel(LogLevel.Info).WriteToConsole();
      builder.ForLogger().FilterMinLevel(LogLevel.Debug).WriteToFile(fileName: "file.txt");
   });
```

**Comment by snakefoot** [comment]
Closing question as answered, due to inactivity.
