### ISSUE TITLE
Updating from NLog 4.14.0 to 5.0.0 broke my log levels

### ISSUE THREAD

**Issue by paleocomburo** [NLog/NLog.Web#804]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

QUESTIONS are preferred on StackOverflow. You could expect a faster response there (but do include all the info below). Use the tag "nlog" https://stackoverflow.com/questions/ask

Please only post issues here related to NLog.Web. If unsure, please post on https://github.com/NLog/NLog/issues/new

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type**: Bug

**NLog version**: (Not explicitly installed)

**NLog.Web/NLog.Web.AspNetCore version**: 5.0.0

**NLog.Extensions.Logging version**: (Not explicitly installed)

**Platform**: .NET 6

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0"?>
<nlog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true" >
  <time type="AccurateUTC" />
  <targets>
    <target name="GeneralLogAppender" encoding="utf-8" xsi:type="Console">
      <layout xsi:type="JsonLayout" EscapeForwardSlash="false" >
        <attribute name="level" layout="${level:uppercase=true}" />
        <attribute name="timestamp" layout="${longdate}"/>
        <attribute name="traceid" layout="${aspnet-TraceIdentifier:IgnoreActivityId=true}" />
        <attribute name="logger" layout="${logger}" />
        <attribute name="message" layout="${message}"/>
        <attribute name="exception" encode="true" layout="${onexception:${exception:format=Type,Message,StackTrace:innerFormat=Type,Message,StackTrace:maxInnerExceptionLevel=10}" />
      </layout>
    </target>

    <target name="StructuredAppender" encoding="utf-8" xsi:type="Console" >
      <layout xsi:type="JsonLayout" includeAllProperties="true">
        <attribute name="Timestamp" layout="${longdate}" />
        <attribute name="Data" layout="${message}" encode="false"/>
      </layout>
    </target>
  </targets>

  <rules>
    <logger name="structured" writeTo="StructuredAppender" final="true" />
    <logger name="*" minlevel="Trace" writeTo="GeneralLogAppender"/>
  </rules>
</nlog>
```

I updated the Nuget package for `NLog.Web.AspNetCore` from version 4.1.4.0 to 5.0.0 and noticed the log levels configured in the appsettings.json were ignored. I had them set to `Information`, but I got everything, including `Trace` events.
I checked the documentation on the .NET 6 setup and copied that, but it made no difference. Reverting back to version 4.14.0 fixed the issue.

This is the logging setup in code:
```c#
        var builder = WebApplication.CreateBuilder(args);

        builder.WebHost.ConfigureKestrel(options =>
        {
            options.AddServerHeader = false;
        })
        .ConfigureAppConfiguration((context, configure) =>
        {
            var environment = context.HostingEnvironment;
            configure.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
            configure.AddJsonFile($"appsettings.{environment.EnvironmentName}.json", optional: true, reloadOnChange: true);
            configure.AddEnvironmentVariables();
            configure.AddCommandLine(args);
        })
        .ConfigureLogging((context, logging) =>
        {
            logging.ClearProviders();
            logging.AddConfiguration(context.Configuration.GetSection("Logging"));
            logging.AddNLogWeb("nlog.config");
        });
```

And this is the relevant section from the appsettings.json:
```json
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Microsoft.Extensions.Http.DefaultHttpClientFactory": "Warning",
      "System.Net.Http.HttpClient": "Warning",
      "structured": "Information"
    }
  }
```

And the appsettings.Development.json that is alos used on my laptop (`Default` is now back to `Debug`):
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft.AspNetCore": "Warning"
    }
  }
}
```

**Comment by snakefoot** [comment]
You are seeing the breaking change: [NLog.Extensions.Logging without any filter](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#nlogextensionslogging-without-any-filter)

You can update your NLog.config like this:

```xml
  <rules>
    <logger name="Microsoft.AspNetCore*" finalMinLevel="Warn" />
    <logger name="Microsoft.Extensions.Http.DefaultHttpClientFactory*" finalMinLevel="Warn" />
    <logger name="System.Net.Http.HttpClient*" finalMinLevel="Warn" />

    <logger name="structured" minLevel="Info" writeTo="StructuredAppender" final="true" />
    <logger name="*" minlevel="Debug" writeTo="GeneralLogAppender"/>
  </rules>
```

Or you can register NLog like this:

```c#
        .ConfigureLogging((context, logging) =>
        {
            logging.ClearProviders();
            logging.AddNLogWeb(new NLogAspNetCoreOptions() { RemoveLoggerFactoryFilter = false } );
        });
```

**Comment by paleocomburo** [comment]
I had completely missed that. Thanks.
I also saw I can have the complete NLog settings in appsettings. That's also nice.

**Comment by paleocomburo** [comment]
Looking at the documentation again at: https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-6
This was written for 4.x, it would be helpful te mention the documentation there is not correct for 5.x.

**Comment by snakefoot** [comment]
Yes it is a good idea to update NET6 guide now NLog5 is out.

I guess the only thing changed, is that default Loglevel in appsettings.json is not that important?

Sent from my Galaxy



-------- Original message --------
From: Jeroen-bart Engelen ***@***.***>
Date: 16/06/2022 21:57 (GMT+01:00)
To: "NLog/NLog.Web" ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog.Web] Updating from NLog 4.14.0 to 5.0.0 broke my log levels (Issue #804)


Looking at the documentation again at: https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-6
This was written for 4.x, it would be helpful te mention the documentation there is not correct for 5.x.

**Comment by paleocomburo** [comment]
Not just the default log level. The whole "Logging" section in appsettings is ignored. Since that page talks about it specifically, it would make sense to mention there that the default behaviour changed for NLog 5, and the only thing required to make it work is to use the NLogAspNetCoreOptions on UseNLog, or AddNLogWeb.

**Comment by snakefoot** [comment]
Have tried to update the wiki-page:

https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-6

Notice that the wiki-page is open for editing, so please add any improvements you find useful.

**Comment by snakefoot** [comment]
Closing question as answered due to inactivity.
