### ISSUE TITLE
AspNetLayoutRendererBase being scanned, but not invoked

### ISSUE THREAD

**Issue by kevin-verpoort** [NLog/NLog.Web#81]
**I have the following class:**

```
[LayoutRenderer("request-session-id")]
public class RequestSessionIdLayoutRenderer : AspNetLayoutRendererBase
{
    protected override void DoAppend(StringBuilder builder, LogEventInfo logEvent)
    {
       builder.Append("Some value");
    }
}
```

**Which is being registered in Configure() like this:**

`ConfigurationItemFactory.Default.LayoutRenderers.RegisterDefinition("request-session-id", typeof(RequestSessionIdLayoutRenderer));`

**And being used like this:**

```
<extensions>
  <add assembly="My.WebApi"/>
</extensions>

<parameter name="@sessionid" layout="${request-session-id}" />
```

In the trace log I can see the assembly being scanned and the class being found.
However it never executes DoAppend() and the variable will never be filled.

I've tried NLog 4.4.1 and the latest 5.0.0 beta.

**Comment by kevin-verpoort** [comment]
When I use "LayoutRenderer" instead of "AspNetLayoutRendererBase" it gets invoked.

**Comment by 304NotModified** [comment]
Which NLog.web (nuget) version? Or build from source?

**Comment by stuarthunter** [comment]
@kevin-verpoort I think you are missing code in Startup.ConfigureServices to register the NLog HttpContextAccessor:

`services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();`

Without this, AspNetLayoutRendererBase.Append with fail to locate the context and will exit before invoking your DoAppend method.

@304NotModified The docs for this are a little unclear as the comment 'call this in case you need aspnet-user-authtype/aspnet-user-identity' implies that it is only needed if you are using identity layout renderers.

**Comment by 304NotModified** [comment]
Yes, the docs aren't up-to-date for NLog 4.3 and that needs to be done. Any help with it would be great!

**Comment by 304NotModified** [comment]
> @304NotModified The docs for this are a little unclear as the comment 'call this in case you need aspnet-user-authtype/aspnet-user-identity' implies that it is only needed if you are using identity layout renderers.

Could you create a PR to make the docs more clear? Thx!

**Comment by 304NotModified** [comment]
4.3 has been released! This should fix this issue. If not, let me know!
