### ISSUE TITLE
How to use lower case to logging the keys on ${aspnet-request-querystring} ?

### ISSUE THREAD

**Issue by czd890** [NLog/NLog.Web#839]
The querystring similar:
```
https://github.com/?ABC1=a&Abc2=b&abc3=c&m1=1&m1=2
```

Configured:
```
${aspnet-request-querystring:outputFormat=JsonDictionary}
```

Feature1: lower case for keys
```
{"abc1":"a","abc2":"b","abc3":"c"}
```

Feature2: support the array value
```
{"m1":["1","2"]}
```

**Comment by snakefoot** [comment]
PullRequest are wellcome for NLog.Web-repo

**Comment by snakefoot** [comment]
Regarding `Feature 2:` will the request.QueryString["m1"] return an array of values, when using `https://github.com/?m1=1&M1=2

**Comment by czd890** [comment]
Create a [PR](https://github.com/NLog/NLog.Web/issues/840) for `Feature 1:`. 
for case of keys, we use a bool option similar `KeyToLower`. or use a enum option similar `CaseOfKey:[None,Lower,Upper]` 
let me know what you think.

Yes for `Feature 2:`
