### ISSUE TITLE
AspNetSessionValueLayoutRenderer should be threadsafe

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.Web#847]
AspNetSessionValueLayoutRenderer modifies the HttpContext.Items-collection, but this collection is not threadsafe.

Implement other threadsafe way of doing re-entrant checking. Ex. like this: https://github.com/getsentry/sentry-dotnet/commit/e0d6b1de14e66406f0f62b86a1c6091cbb1c6349 (Only possible for ASP_NET_CORE or NET46)

**Comment by snakefoot** [comment]
@bakgerman Maybe something for you ?

**Comment by bakgerman** [comment]
Yes, I accept :)

**Comment by bakgerman** [comment]
I have read the commit above and I now understand the AsyncLocal technique used.  
it should be relatively easy to address this.  
We can keep the old code maybe for NET35 platform.

**Comment by snakefoot** [comment]
Sounds great

**Comment by bakgerman** [comment]
PR submitted
