### ISSUE TITLE
Document middleware example for capture http context response body in log.

### ISSUE THREAD

**Issue by bakgerman** [NLog/NLog.Web#849]
This is so, I can assign this to myself as a documentation task, after I finish my other pull requests.

**Comment by bakgerman** [comment]
I can work on this now, I was ill with different things but now I am better.

After this I will look at the object-path HttpContext.Items.

**Comment by bakgerman** [comment]
@snakefoot this is now complete here:  `https://github.com/NLog/NLog.Web/wiki/HTTP-Response-Body-Capture`

**Comment by snakefoot** [comment]
I think it looks awesome. I have fixed some indenting, and also added a link to .NET6 [UseHttpLogging](https://github.com/NLog/NLog.Web/wiki/HTTP-Request-Logging)

**Comment by bakgerman** [comment]
Thank you for the review.  Good to know about the .NET6 feature, I will read more about that.
