### ISSUE TITLE
aspnet-request-url - change to property-enum instead of booleans

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.Web#855]
It is rather annoying to use `aspnet-request-url` for splitting the url into parts.

It could be nice if one could do this `${aspnet-request-url:properties=port}`

Instead of having to do this: `${aspnet-request-url:IncludeScheme=false:IncludeHost=false:IncludePath=false:IncludePort=true}`

The Properties would have to be a Flags-Enum, and then change all the existing boolean-properties to modify the value of Property-Flags-Enum. The default value of the Properties-value should match the current default-boolean-configuration.

**Comment by bakgerman** [comment]
I might as well take this one.  I see there are 5 boolean-properties.  Can we make the bool properties Obsolete?  That will still allow existing NLog.config files to work.  To match the default bool values, the Enum will default to the Scheme, Host and Path flags on, but the Port and Query flags off.

**Comment by snakefoot** [comment]
Yes the existing boolean-values should stay, so it doesn't become a breaking change.

**Comment by bakgerman** [comment]
Submitted pull request.
