### ISSUE TITLE
Introduce ObjectPath as alternative to EvaluateAsNestedProperties for HttpContext.Items

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.Web#869]
ObjectPath is a "known" way of navigating object-properties when using `${event-properties}`

Could be nice if `${aspnet-httpcontext-item}` also provided this feature for API-consistency.

**Comment by bakgerman** [comment]
Can someone please tell me if any existing class(es) I should be examining in NLog or NLog.Web to understand the feature request better?

**Comment by bakgerman** [comment]
Never mind, I found it in EventPropertiesLayoutRenderer.

**Comment by snakefoot** [comment]
Resolved by #890
