### ISSUE TITLE
Appsettings loglevel does not work in 5.x.x version

### ISSUE THREAD

**Issue by troepolik** [NLog/NLog.Web#875]
Starting with 5.0.0 version  NLog.Web.AspNetCore loglevel setted in appsettings does not work.
With NLog.Web.AspNetCore Version="4.14.0" it works
1) I set log level in NLog.xml file as trace :

    <logger name="*" minlevel="Trace" writeTo="Application"/>
    
2) in appsettings :
"Logging": {
    "LogLevel": {
      "Default": "Information"
    }
  }

3) IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureLogging(logging =>
    {
        logging.ClearProviders();
    })
    .UseNLog()

4) somewere:
private readonly ILogger<MyService> _logger;
_logger.LogInformation("Info");
        _logger.LogDebug("Debug");
        _logger.LogTrace("Trace");

with 4.14.0 only Info was logged - it's correct
with 5.0.0 and higher : info, debug and trace - it's wrong

Was it breaking change or it is bug ?

**Comment by troepolik** [comment]
It would be greate to have link to release noutes in package
I founded it was breaking change :
https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html
NLog LoggingProvider no longer follows the Microsoft Logger filtering configuration.
Workaround: Explicit specify RemoveLoggerFactoryFilter = false for NLogProviderOptions when calling UseNLog() to enable old behavior, where Microsoft LoggerFactory filters specified in appsetting.json also applies to NLog.

**Comment by snakefoot** [comment]
We have tried to announce that NLog v5 contains major changes:

https://www.nuget.org/packages/NLog#release-body-tab

https://www.nuget.org/packages/NLog.Extensions.Logging/#release-body-tab

https://www.nuget.org/packages/NLog.Web.AspNetCore/#release-body-tab

https://github.com/NLog/NLog/releases/tag/v5.0

https://github.com/NLog/NLog.Extensions.Logging/releases/tag/v5.0.0

https://github.com/NLog/NLog.Web/releases/tag/v5.0.0
