### ISSUE TITLE
The base path for the `appsettings.json` do not match the base path of the web host.

### ISSUE THREAD

**Issue by soc-martin** [NLog/NLog.Web#883]
**Type**: Bug

**NLog version**: 5.0.5

**NLog.Web/NLog.Web.AspNetCore version**: 5.1.5

**NLog.Extensions.Logging version**: 5.1.0

While debugging in Visual Studio, I found that custom application settings were getting updated but not those of NLog. I looked up the `appsettings.json` files that were updated and noticed the changes weren't all in the same file.

I browsed the code of NLog and of aspnetcore and discovered they weren't using the same base path.

For NLog, the base path is in the AppContext:
https://github.com/NLog/NLog.Web/blob/v5.1.5/src/NLog.Web.AspNetCore/Config/SetupBuilderExtensions.cs#L25
```C#
            var currentBasePath = basePath;
            if (currentBasePath is null)
            {
                currentBasePath = AppContext.BaseDirectory;
                if (string.IsNullOrEmpty(currentBasePath))
                {
                    currentBasePath = Directory.GetCurrentDirectory();
                }
            }

            var builder = new ConfigurationBuilder()
                // Host Configuration
                .SetBasePath(currentBasePath)
                .AddEnvironmentVariables(prefix: "ASPNETCORE_")
                .AddEnvironmentVariables(prefix: "DOTNET_")
                // App Configuration
                .AddJsonFile("appsettings.json", optional, reloadOnChange)
                .AddJsonFile($"appsettings.{environment}.json", optional: true, reloadOnChange: reloadOnChange)
                .AddEnvironmentVariables();
```

For aspnetcore, the base path is in the environment's content root path:
https://github.com/dotnet/aspnetcore/blob/v6.0.11/src/Hosting/Hosting/src/WebHostBuilder.cs#L282
```C#
            var builder = new ConfigurationBuilder()
                .SetBasePath(_hostingEnvironment.ContentRootPath)
                .AddConfiguration(_config, shouldDisposeConfiguration: true);
```

**Comment by snakefoot** [comment]
NLog.Web.AspNetCore doesn't have access to the same internal classes, which is available to the Microsoft WebHostBuilder.

But we have tried to copy the behavior of `_hostingEnvironment.ContentRootPath`. But if you see places where the illusion is failing, then pull-requests are very wellcome to improve this.

**Comment by snakefoot** [comment]
Closing as resolved, due to inactivity.

**Comment by soc-martin** [comment]
Sorry for the delay. I created a PR with a solution I came up with.

**Comment by snakefoot** [comment]
@soc-martin Thank you again for being persistent about this issue. Will soon make new release, if no new issues arise.

**Comment by snakefoot** [comment]
@soc-martin NLog.Web.AspNetCore v5.2.0 have now been released, where `LoadConfigurationFromAppSettings` prioritize current-directory.
