### ISSUE TITLE
AspNetCore: AspNetRequestUrlRenderer returns nothing/empty string

### ISSUE THREAD

**Issue by Arie-Kanarie** [NLog/NLog.Web#90]
I've updated `NLog.Web.AspNetCore` to 4.3.0, after that updated `NLog` to 5.0.0-beta4 and `NLog.Extensions.Logging` to 1.0.0-rtm-beta1, as required by the `NLog.Web.AspNetCore` package.
Changed the Nlog.config to pass `${aspnet-request-url:IncludePort=true:IncludeQueryString=true}` instead of 'n/a' as value for the SP parameter (I'm logging to MS SQL database via Stored Procedure).
Did a test request, but the column stays empty, where as it was first filled with n/a, so I pass it to the correct parameter. 
Before the update I was using `NLog.Web.AspNetCore` 4.2.4 which would log an internal exception if I use `aspnet-request-url`, as expected, so the update did add support for the renderer, but now it doesn't render any info. Am I missing something?

I'm using the default ILogger interface MS provides by the AspNetCore WebApi project:
```C#
public SomeController(IActionContextAccessor actionContextAccessor, ILogger<SomeController> logger)
    : base(actionContextAccessor)`
{
    this.logger = logger;
}

public IActionResult GetSome(int someId)
{
    this.logger.LogInformation($"Trying to get some. SomeId: {someId}");
}
```

**Comment by 304NotModified** [comment]
do you have 

```
public void ConfigureServices(IServiceCollection Services)
{
    //call this in case you need aspnet-user-authtype/aspnet-user-identity
    services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
}

```?

see https://github.com/NLog/NLog.Web#usage

**Comment by Arie-Kanarie** [comment]
Whoops, overlooked that part in the readme. I did see the part about the extensions in nlog.config, and the 2 lines that go into Configure(..), but missed that single line.
Adding that line solves it.

Thanks for the quick reply. I'll close this question.

**Comment by 304NotModified** [comment]
👍 

We will try if we could register this automatically  in NLog in the future
