### ISSUE TITLE
Add TraceIdentifier for ASP.Net Core

### ISSUE THREAD

**Issue by luciusli** [NLog/NLog.Web#92]
I have a middleware that add a HTTP response header with the value of `HttpContext.TraceIdentifier`. It would be really useful if I could log the corresponding `TraceIdentifier` to find out what went wrong in case of errors. Thank you.

**Comment by 304NotModified** [comment]
Do you have the c# code to read the `TraceIdentifier` in .NET Core?

**Comment by luciusli** [comment]
Something like this

    [LayoutRenderer("aspnet-trace-identifier")]
    public class AspNetTraceIdentifierLayoutRenderer : AspNetLayoutRendererBase
    {
        protected override void DoAppend(StringBuilder builder, LogEventInfo logEvent)
        {
            var context = HttpContextAccessor.HttpContext;

            builder.Append(context.TraceIdentifier);
        }
    }

**Comment by 304NotModified** [comment]
if this works, please create a PR :)

(and or support ASP.NET 4 or exclude with `#if`)

**Comment by 304NotModified** [comment]
Added in 4.3.1! Thanks for the code!
