### ISSUE TITLE
Extend ${aspnet-response-statuscode} to include Enum-ToString value

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.Web#920]
Introduce a Format option, when using Format="d" then it will output integer-value (Default)

Else cast to `HttpStatusCode` and output the [Enum.ToString(Format)](https://learn.microsoft.com/en-us/dotnet/api/system.enum.tostring). Ex. `304` becomes `NotModified`

https://github.com/NLog/NLog/wiki/AspNetResponse-StatusCode-Layout-Renderer

**Comment by bakgerman** [comment]
If I read this properly, if there is no Format specified, default to 'd' and output integer.  
If the Format is 'd', output integer.
If the Format is anything else output the HttpStatusCode.ToString().

You can assign this to me.

**Comment by snakefoot** [comment]
I was thinking to introduce new `Format`-option that is initialized to "d".

When `Format`-option is blank or other value, then call `HttpStatusCode.ToString(Format)`

Was also considering to introduce new `ErrorOnly`-option that is initialized to `bool.True`, and when ErrorOnly=false then it would output the StatusCode when > 0 (Ex. output 200).

**Comment by bakgerman** [comment]
Is ErrorOnly=true then meant to keep the existing behavior, where the output is emitted if >=100 and <=599?
Since we initialize ErrorOnly to bool.True, that implies that should execute the existing behavior.

To the user, ErrorOnly seems to imply only 400-599 are output, as 100-399 are non-error conditions.

**Comment by snakefoot** [comment]
Thank you for the heads up. I now see that it actually both successful and failing error-codes, but only when in the valid range.

Just ignore my suggestion about ErrorOnly-option. I just misread the existing source code.


Sent from my Galaxy



-------- Original message --------
From: Burak Akgerman ***@***.***>
Date: 17/01/2023 22:51 (GMT+01:00)
To: "NLog/NLog.Web" ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Author ***@***.***>
Subject: Re: [NLog/NLog.Web] Extend ${aspnet-response-statuscode} to include Enum-ToString value (Issue #920)


Is ErrorOnly=true then meant to keep the existing behavior, where the output is emitted if >=100 and <=599?
Since we initialize ErrorOnly to bool.True, that implies that should execute the existing behavior.

To the user, ErrorOnly seems to imply only 400-599 are output, as 100-399 are non-error conditions.
