### ISSUE TITLE
aspnet-request-querystring -  QueryStringKeys is required.

### ISSUE THREAD

**Issue by sgutkin** [NLog/NLog.Web#93]
Environment:

 .net 4.6.2
  <package id="NLog" version="4.4.1" targetFramework="net462" />
  <package id="NLog.Web" version="4.3.0" targetFramework="net462" />

This line works:
${aspnet-request-querystring:QueryStringKeys=someKey;OutputFormat=Flat}

This line does not work:
${aspnet-request-querystring:OutputFormat=Flat}

The documentation uses "CAN" instead of "MUST" this implies that the "QueryStringKeys is optional. Ideally this value would not be manadatory, but if it is mandatory then the documentation should reflect that it is.

Link to documentation : https://github.com/NLog/NLog/wiki/AspNetRequest-QueryString-Layout-Renderer

**Comment by 304NotModified** [comment]
Agree, we should change this.

**Comment by 304NotModified** [comment]
Fixed in 4.3.1
