### ISSUE TITLE
Extend AspNetUserClaimLayoutRenderer to handle multi-values

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.Web#949]
Inherit from `AspNetLayoutMultiValueRendererBase` and support outputting all assigned claim-values:
```c#
                foreach (var claim in ctx.Principal.Claims)
                {
                    Console.WriteLine($"{claim.Type} - {claim.Value}");
                }
```
See also: https://nestenius.se/2023/06/02/debugging-jwtbearer-claim-problems-in-asp-net-core/

**Comment by bakgerman** [comment]
I will examine this

**Comment by bakgerman** [comment]
PR submitted
