### ISSUE TITLE
Better diagnostics for AspNetBufferingTargetWrapper without HttpModule or Middleware

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.Web#953]
When initializing AspNetBufferingTargetWrapper then it should output a warning when HttpModule or Middleware is not configured.

See also: https://stackoverflow.com/questions/76322312/how-to-enable-aspnetbufferingwrapper-in-framework-asp-net-webapi-2-project-usin

**Comment by bakgerman** [comment]
Submitted PR

**Comment by snakefoot** [comment]
Resolved by #979
