### ISSUE TITLE
app.UseMiddleware<NLogRequestPostedBodyMiddleware>() does not work in dotnet 7

### ISSUE THREAD

**Issue by ilya-scale** [NLog/NLog.Web#956]
**Type** Bug:

**NLog.Web / NLog.Web.AspNetCore version**: 5.3.0

**Platform**: .Net 7

**Current NLog config** (xml or C#, if relevant)

```csharp
LogManager.Setup()
            .RegisterNLogWeb()
            .LoadConfiguration(c =>
            {
                var attributes = new List<JsonAttribute>
                    {
                         new("message", "${message}"),
                        new("body", "${aspnet-request-posted-body}")
                    }
                    .ToList();

                var layout = new JsonLayout();
                attributes.ForEach(attribute => layout.Attributes.Add(attribute));
                
                c.ForLogger().WriteTo(new ColoredConsoleTarget
                {
                    Layout = layout
                });
            });
```

In case of a BUG:

- What is the current result?

   It does not work even if I add `app.UseMiddleware<NLogRequestPostedBodyMiddleware>()`

- What is the expected result?
  
   It should work

I have debugged it to this line in the middleware:

```csharp
            // If we cannot seek the stream we cannot capture the body
            if (!postedBody.CanSeek)
            {
                InternalLogger.Debug("NLogRequestPostedBodyMiddleware: HttpContext.Request.Body stream is non-seekable");
                return false;
            }
```

It I add this directly before middleware:

```chsarp
     app.Use(async (context, next) => {
         context.Request.EnableBuffering();
         await next();
    });
```

Then the layout works and outputs the body. So the EnableBuffering is not being enabled due to CanSeek check, even though if one does it directly - it would work.

**Comment by snakefoot** [comment]
Thank you for reporting this. You have found a bug, that was introduced with NLog.Web.AspNetCore v5.3. Will prepare a code-fix with an unit-test.

**Comment by snakefoot** [comment]
NLog.Web.AspNetCore v5.3.1 has now been released - https://www.nuget.org/packages/NLog.Web.AspNetCore

Thank you again for taking the time to report this issues.

**Comment by ilya-scale** [comment]
Thanks, that was fast!

**Comment by snakefoot** [comment]
NLog tries to make release once a month, if any improvements/bugfixes has been made. And your bug-report arrived just in time to be included.

**Comment by snakefoot** [comment]
NLog.Web.AspNetCore v5.3.2 has now been released - https://www.nuget.org/packages/NLog.Web.AspNetCore

Thank fixes another bug in NLogRequestPostedBodyMiddleware (and improves the unit-test)
