### ISSUE TITLE
'OutputFormat' can not work in AspNetRequestCookieLayoutRenderer

### ISSUE THREAD

**Issue by ymind** [NLog/NLog.Web#96]
whether x or y are missing the key name.

**Comment by 304NotModified** [comment]
Could you elaborate on this?

**Comment by 304NotModified** [comment]
I think I see the problem :)

**Comment by ymind** [comment]
I'm sorry for coming late. These days I am not online. Today I updated your work and made some test .

### tests:
there still has some error, in my nlog.config, the rule is:
`${aspnet-request-cookie:CookieNames=XSRF-TOKEN;OutputFormat:JSON}`

the output log is:
`{"XSRF-TOKEN;OutputFormat="}`

then I chanage the rule to:
`${aspnet-request-cookie:CookieNames=XSRF-TOKEN,jnp.auth,.AspNetCore.ServerCookie,LAST_ONE;OutputFormat:JSON}`

it's output like:
`{"XSRF-TOKEN=HySuQS4Nv-31w76KQ"},{"jnp.auth=mR5Jsduhrqz_6Wc2zoPtQ"},{".AspNetCore.ServerCookie;OutputFormat="}`

third test rule is:
`${aspnet-request-cookie:CookieNames=XSRF-TOKEN,jnp.auth,.AspNetCore.ServerCookie,LAST_ONE;OutputFormat:JSON}`

output like:
`{"XSRF-TOKEN=HySuQS4Nv-31w76KQ"},{"jnp.auth=mR5Jsduhrqz_6Wc2zoPtQ"},{".AspNetCore.ServerCookie=GH2R-o1Npkj"},{"LAST_ONE;OutputFormat="}`

### the problems are:
1. json format is wrong, should be: `{"key": "value"}`
2. the last cookie name can not get the true value;
3. the string "OutputFormat=" should not in the output;

### some suggestion:
the [AspNetRequestQueryStringLayoutRenderer](https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestQueryStringLayoutRenderer.cs) is working fine, please refer to it.
