### ISSUE TITLE
NLog.Web.AspNetCore dependencies

### ISSUE THREAD

**Issue by kalatchev** [NLog/NLog.Web#963]
**Type**:

- Bug

**NLog version**: 5.3.1
**NLog.Web / NLog.Web.AspNetCore version**: 5.31.
**Platform**:  .NET 6.0

For some (strange for me) reason, `NLog.Web.AspNetCore` **does not depends** on `NLog`?!? I spend few hours wondering what's wrong and why I can't get logging working. Finally, I realize that my project has no reference to `NLog` :-) . IMHO `NLog.Web.AspNetCore` **should depends** on `NLog`, as otherwise it is useless.

**Comment by snakefoot** [comment]
`NLog.Web.AspNetCore` depends on `NLog.Extensions.Logging ` that depends on `NLog`.

So  `NLog.Web.AspNetCore`  depends on `NLog`.

**Comment by kalatchev** [comment]
Thanks for feedback @snakefoot . 

I have checked it and obviously you are correct. It seems that my VS did not resolved deps correctly. Sorry for disturbing :-)

**Comment by snakefoot** [comment]
Happy to hear the mystery was resolved.
